### List of list to DataFrame

In [1]:
import pandas as pd
product_price_list=[['A',12, 3,6],['B',14,6,9],['C',28,7,3],['D',40,9,12]]
df=pd.DataFrame(product_price_list,columns=['product','prices','unit item','sales change(%)'])

In [2]:
df

  product  prices  unit item  sales change(%)
0       A      12          3                6
1       B      14          6                9
2       C      28          7                3
3       D      40          9               12

### List of Dictionaries to DataFrame

In [3]:
product_price_dicts={'A':12,'B':14,'C':28,'D':40}
df_dict=pd.DataFrame(list(product_price_dicts.items()),columns=['product','price'])
df_dict

  product  price
0       A     12
1       B     14
2       C     28
3       D     40

In [4]:
list(product_price_dicts.items())

[('A', 12), ('B', 14), ('C', 28), ('D', 40)]

It's convenient way to see that Python can create a datafram from list of tuples.

In [5]:
import numpy as np
def split_and_stack(df, new_names):
    """Split a DataFrame into two halves and then stack them vertically, returning a new DataFrame with new_names as the column name.
    Args:
    df (DataFrame): The DataFrame to split.
    new_names (iterable of str): The column names for the new DataFrame.
    
    Returns:
    DataFrame
    """
    half=int(len(df.columns)/2)
    left=df.iloc[:, :half]
    right=df.iloc[:,half:]
    return pd.DataFrame(
    data=np.vstack([left.values, right.values]),
    columns=new_names
    )

#### Google Style docstrings
- Description of what the function does.
   - It should be imperative language. For instance: "Split the data frame and...".
- Args description and their types
   - If argument has a default value, mark it as "optional" when describing the type.
- Returns: Description of what kind of return type you expect.
- Finally, if your function intentionally raises any errors, you should add a "Raises" section.

#### Numpydoc

In [6]:
def function(arg1,arg2=42):
    """
    Description of what the function does.
    
    Parameters
    ----------
    arg1 : expected type of agr1
      Description of agr1.
    arg2 : int, optional
      Write optional when an agrument has a default value.
     Default=42
     
    Returns
    -------
    The type of the return value.
      Can include a description of retun value
      Replace """Return" with "Yields" if this function is a generator.
     """

SyntaxError: invalid syntax (<ipython-input-6-0cbef4d47831>, line 17)

In [7]:
def the_answer():
    """Return the answer to life, 
    the universe, and everything.
    
    
    Returns:
      int
    """
    return 42
print(the_answer.__doc__)

Return the answer to life,
    the universe, and everything.


    Returns:
      int

Every function in Python comes with a __doc__ attribute that hold the information.

In [8]:
import inspect
print(inspect.getdoc(the_answer))

Return the answer to life,
the universe, and everything.


Returns:
  int

In [9]:
new_names=['1','2']
split_and_stack(df,new_names)

   1   2
0  A  12
1  B  14
2  C  28
3  D  40
4  3   6
5  6   9
6  7   3
7  9  12

- df.iloc[:,:0]: tüm rowları al, 0'cı columndan önceki her sutünü al
- df.iloc[:,0:]: tüm rowları al, 0'ıncı column ve  sonraki tüm sutünleri al

In [10]:
df.iloc[:,2:]

   unit item  sales change(%)
0          3                6
1          6                9
2          7                3
3          9               12

#### DRY and "Do One Thing"
DRY (also known as "don't repeat yourself") and the "Do One Thing" principle are good ways to ensure that your function are well designed and easy to test.

# WRITING EFFICIENT PYTHON CODE

Writing an efficient Python code requires two main things:
- Minimal completion time
- Minimal memory overhead

In [12]:
# Non-Pythonic
numbers=[1,2,3]
doubled_numbers=[]
for i in range(len(numbers)):
    doubled_numbers.append(numbers[i]*2)

Pythonic code tends to be less verbose and easier to interpret.

In [13]:
doubled_numbers

[2, 4, 6]

In [15]:
# Pythonic (efficient code)
doublend_numbers=[x*2 for x in numbers]

In [16]:
len(numbers)

3

In [17]:
names=['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

In [19]:
name_list=[]
for name in names:
    if len(name)>=6:
        name_list.append(name)
print(name_list)

['Kramer', 'Elaine', 'George', 'Newman']

In [49]:
name_list=[name for name in names if len(name)>=6]

In [50]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!

## Built-in Components
Buit-in components are referred to as the Python Standard Library (part of standard Python installation).
* Built-in types
  - list, tuple, set, dict, and others.
* Built-in functions
  - print(), len(), range(), enumerate(), map(), zip(), and others.
* Built-in modules
  - os, sys, itertools, collections, math, and others.
Note: We should default to using a built-in solution (if exists) rather than developing our own.

In [53]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [54]:
list(range(4,400,40))

[4, 44, 84, 124, 164, 204, 244, 284, 324, 364]

In [55]:
alfabe=['a','b','c','d','e','f','g','h','i','ı']
indexed_letters=enumerate(alfabe)
indexed_letters_list=list(indexed_letters)
print(indexed_letters_list)

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd'), (4, 'e'), (5, 'f'), (6, 'g'), (7, 'h'), (8, 'i'), (9, 'ı')]

In [56]:
alfabe=['a','b','c','d','e','f','g','h','i','ı']
indexed_letters=enumerate(alfabe,start=29)
indexed_letters_list=list(indexed_letters)
print(indexed_letters_list)

[(29, 'a'), (30, 'b'), (31, 'c'), (32, 'd'), (33, 'e'), (34, 'f'), (35, 'g'), (36, 'h'), (37, 'i'), (38, 'ı')]

In [61]:
nums=[1.23,2.345,23.44,23.4113,3.453]
# map(function, object)
rnd_nums=map(round,nums)
print(list(rnd_nums))

[1, 2, 23, 23, 3]

In [66]:
nums=[2,4,6,8]
new_nums=map(lambda x:x**3,nums)
print(list(new_nums))

[8, 64, 216, 512]

In [67]:
# Create a range object that goes from 0 to 5
nums = range(6)
print(type(nums))

# Convert nums to a list
nums_list = list(nums)
print(nums_list)

# Create a new list of odd numbers from 1 to 11 by unpacking a range object
nums_list2 = [*range(1,12,2)]
print(nums_list2)

<class 'range'>
[0, 1, 2, 3, 4, 5]
[1, 3, 5, 7, 9, 11]

In [68]:
nums_list2

[1, 3, 5, 7, 9, 11]

In [69]:
# Use map to apply str.upper to each element in names
names_map  = map(str.upper, names)

# Print the type of the names_map
print(type(names_map))

# Unpack names_map into a list
names_uppercase = [*names_map]

# Print the list created above
print(names_uppercase)

<class 'map'>
['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']

## NumPy
Numpy, or Numerical Python, is an invaluable Python package for Data Scientists.
- Alternative to Python list. It's more fast and memory efficient way.
- numpy.array([list)

In [70]:
nums_list=list(range(5))

In [71]:
nums_list

[0, 1, 2, 3, 4]

In [72]:
nums_np=np.array(range(5))

In [73]:
nums_np

array([0, 1, 2, 3, 4])

- Numpy arrays are homogeneous, which means that they must contain elements of the same type.

In [74]:
nums_np_ints=np.array([1,2,3])

In [75]:
nums_np_ints

array([1, 2, 3])

In [77]:
nums_np_ints.dtype

dtype('int32')

In [78]:
nums_np_floats=np.array([1,2.5,3])

In [79]:
nums_np_floats

array([1. , 2.5, 3. ])

In [80]:
nums_np_floats.dtype

dtype('float64')

NumPy converted the integers to floats to maintain homogeneity nature.

* Python lists don't support broadcasting

In [82]:
nums=[1,5,7,9]
nums*2

[1, 5, 7, 9, 1, 5, 7, 9]

In [84]:
# All elements are squared at once.
np.array(nums)*2

array([ 2, 10, 14, 18])

In [85]:
nums_2=[[2,4,5],[9,12,17]]

In [86]:
nums_2[0][1]

4

In [87]:
[row[0] for row in nums_2]

[2, 9]

In [88]:
nums_2_np=np.array(nums_2)

In [89]:
nums_2_np[0,1]

4

In [90]:
nums_2_np[:,0]

array([2, 9])

In [91]:
nums_2_np>3

array([[False,  True,  True],
       [ True,  True,  True]])

In [98]:
nums_2_np[nums_2_np>3]

array([ 4,  5,  9, 12, 17])

### %timeit

In [103]:
# retuns an array consisting of 1,000 random numbers between 0 and 1.
%timeit rand_nums=np.random.rand(1000)

15.3 µs ± 1.43 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [100]:
rand_nums

array([0.48373042, 0.70416108, 0.44113411, 0.80598321, 0.74139656,
       0.81883349, 0.94736764, 0.73375873, 0.42574975, 0.00544874,
       0.6882194 , 0.70939101, 0.65130509, 0.3400913 , 0.73970671,
       0.90599408, 0.44084286, 0.09571119, 0.10726131, 0.22520246,
       0.39743867, 0.69086883, 0.94607313, 0.04963063, 0.98914082,
       0.89619122, 0.29502002, 0.42175726, 0.6937789 , 0.32999313,
       0.56977284, 0.88623159, 0.16329484, 0.88312699, 0.39785975,
       0.87491899, 0.74435915, 0.76525179, 0.42764682, 0.79134826,
       0.24322441, 0.13375789, 0.4935859 , 0.10743176, 0.512601  ,
       0.05561514, 0.16844845, 0.55494412, 0.8993107 , 0.50598712,
       0.03221035, 0.02913487, 0.22942533, 0.86893849, 0.75634672,
       0.61106232, 0.2728044 , 0.99078792, 0.73740422, 0.8733168 ,
       0.7164699 , 0.78425365, 0.6486823 , 0.30440272, 0.47591932,
       0.41907057, 0.70544436, 0.79044285, 0.97126165, 0.14325514,
       0.31152834, 0.9953504 , 0.15387253, 0.81239995, 0.04077674,
       0.72959529, 0.43283062, 0.89465769, 0.72573209, 0.30121994,
       0.43274604, 0.13113043, 0.06385252, 0.37546599, 0.45902384,
       0.52826691, 0.15697636, 0.00905756, 0.67704349, 0.35850484,
       0.86632748, 0.87683722, 0.62057161, 0.03915213, 0.88667573,
       0.45217179, 0.85115571, 0.46769976, 0.24775845, 0.11863955,
       0.31394244, 0.32752364, 0.99749793, 0.15210364, 0.81324098,
       0.92990889, 0.59524407, 0.8464059 , 0.0023783 , 0.93902309,
       0.62389787, 0.88061327, 0.32431315, 0.41494089, 0.04299071,
       0.36071039, 0.86350219, 0.55430382, 0.34156516, 0.14715447,
       0.75396535, 0.2895941 , 0.7324564 , 0.60825932, 0.18369645,
       0.57487859, 0.60028467, 0.31622488, 0.85393979, 0.32427293,
       0.7108993 , 0.86318937, 0.69309192, 0.31616299, 0.73681601,
       0.46620759, 0.07925704, 0.8729807 , 0.46481681, 0.06687948,
       0.56315506, 0.61109494, 0.11464533, 0.85016559, 0.25545488,
       0.23746222, 0.63555448, 0.73676433, 0.80640832, 0.41468355,
       0.64393901, 0.22693214, 0.87372911, 0.94527623, 0.01410577,
       0.18999058, 0.57573919, 0.99580447, 0.29314958, 0.60416967,
       0.86245562, 0.53116785, 0.85720357, 0.45065991, 0.06211528,
       0.92973667, 0.99016087, 0.45642655, 0.55513121, 0.08120703,
       0.20964824, 0.07455504, 0.61532768, 0.10466483, 0.88445748,
       0.3748483 , 0.8409296 , 0.65057116, 0.47374225, 0.4167101 ,
       0.74169869, 0.07462494, 0.20349444, 0.58244386, 0.43283482,
       0.2468023 , 0.11457189, 0.73476687, 0.78487624, 0.96138862,
       0.84558163, 0.23537046, 0.62415626, 0.80104587, 0.99987319,
       0.12603165, 0.0191518 , 0.56100769, 0.49282259, 0.08146107,
       0.13238203, 0.34525827, 0.90581162, 0.36300047, 0.72081131,
       0.40277169, 0.36243335, 0.33777619, 0.00370045, 0.66703308,
       0.60825173, 0.78838208, 0.09239629, 0.08245793, 0.84820883,
       0.8963903 , 0.58788912, 0.07531172, 0.17821868, 0.86166108,
       0.88493581, 0.27458858, 0.4160246 , 0.28419494, 0.35970298,
       0.59085564, 0.28224942, 0.79831851, 0.07115129, 0.86487665,
       0.74749288, 0.23844376, 0.38652178, 0.52399685, 0.31362292,
       0.78380501, 0.41044108, 0.47557393, 0.23765948, 0.31778122,
       0.32556372, 0.6475117 , 0.06216188, 0.64350006, 0.06685594,
       0.2684191 , 0.74314314, 0.41124839, 0.11325583, 0.02322421,
       0.7073228 , 0.50039271, 0.14302673, 0.20038206, 0.65268089,
       0.03084817, 0.1676233 , 0.70142876, 0.6897151 , 0.01015906,
       0.65227565, 0.31974501, 0.99842919, 0.03552669, 0.76615694,
       0.94169888, 0.98875047, 0.16815782, 0.28937207, 0.21948393,
       0.50660057, 0.88625238, 0.99338781, 0.36538586, 0.36194012,
       0.32378872, 0.6421567 , 0.17369074, 0.50123756, 0.00925898,
       0.08123214, 0.36976386, 0.23961748, 0.46810806, 0.23161099,
       0.12721545, 0.90635859, 0.57693919, 0.73078686, 0.04386189,
       0.40627342, 0.00144419, 0.59671605, 0.06127262, 0.6054428 ,
       0.47158606, 0.3812514 , 0.45149503, 0.96303677, 0.85813754,
       0.52258657, 0.83072109, 0.20767433, 0.17359282, 0.63241026,
       0.99407415, 0.91092832, 0.166494  , 0.73947418, 0.78453835,
       0.81587682, 0.04343157, 0.98524505, 0.40093154, 0.40384972,
       0.65673313, 0.11673098, 0.91316407, 0.4423671 , 0.00389601,
       0.66267361, 0.77500002, 0.6738228 , 0.07352216, 0.13187103,
       0.01793793, 0.46132598, 0.82888922, 0.78801278, 0.26078707,
       0.21726678, 0.33288319, 0.52523936, 0.34628448, 0.91527383,
       0.80763335, 0.3107011 , 0.07579572, 0.64572607, 0.77864849,
       0.87087658, 0.20484382, 0.41874769, 0.62589472, 0.8872872 ,
       0.25456482, 0.07669139, 0.0723845 , 0.79480996, 0.47739474,
       0.27609656, 0.50942828, 0.85523802, 0.79133016, 0.83327398,
       0.72199302, 0.04334284, 0.79562894, 0.38556435, 0.12736859,
       0.71765345, 0.60286847, 0.55543975, 0.44754511, 0.74575246,
       0.69197004, 0.5948482 , 0.70933489, 0.67923475, 0.13391086,
       0.04148757, 0.65760417, 0.77847815, 0.08330797, 0.77718701,
       0.07745946, 0.55387357, 0.93573187, 0.82517787, 0.47457815,
       0.69895171, 0.96277962, 0.98363142, 0.01685496, 0.14047345,
       0.04222188, 0.61294829, 0.05435568, 0.67904381, 0.51313813,
       0.62704571, 0.85664516, 0.43362024, 0.19635516, 0.82984971,
       0.05164516, 0.57672699, 0.73348023, 0.56650247, 0.08292937,
       0.53121654, 0.89368443, 0.9084366 , 0.49708831, 0.52206801,
       0.8095865 , 0.87197274, 0.53682365, 0.17866064, 0.90009184,
       0.45582111, 0.45003958, 0.80904588, 0.93669486, 0.99592855,
       0.95267299, 0.46625394, 0.30740505, 0.28151098, 0.15253148,
       0.84372108, 0.35243048, 0.67832831, 0.45241892, 0.76362426,
       0.63243764, 0.62555595, 0.06157115, 0.02074368, 0.60188533,
       0.49386303, 0.61838659, 0.4361077 , 0.64236175, 0.42297087,
       0.84584937, 0.87355492, 0.8690965 , 0.23769079, 0.83846648,
       0.0112699 , 0.24270057, 0.5125822 , 0.57642218, 0.29039092,
       0.43466723, 0.57913118, 0.79433581, 0.5990713 , 0.68024265,
       0.70581886, 0.28262392, 0.34250869, 0.46782262, 0.50497352,
       0.09833411, 0.30685311, 0.36732625, 0.59270311, 0.98654642,
       0.84279543, 0.83767617, 0.11072499, 0.51766415, 0.42914359,
       0.77186989, 0.9182812 , 0.11679881, 0.17034854, 0.47994988,
       0.87857532, 0.49972259, 0.43602358, 0.84637778, 0.08322171,
       0.64060292, 0.04612456, 0.49012173, 0.57553963, 0.87766742,
       0.85300961, 0.70773392, 0.16956875, 0.27200194, 0.00956746,
       0.07131603, 0.28272488, 0.92149938, 0.60351062, 0.5661361 ,
       0.13054055, 0.97544271, 0.97926258, 0.59471068, 0.2936092 ,
       0.08569254, 0.129724  , 0.35535379, 0.45318348, 0.71989901,
       0.96868634, 0.16024781, 0.44204327, 0.92877693, 0.51791146,
       0.81274003, 0.51566627, 0.35189153, 0.90863346, 0.36374293,
       0.66664559, 0.70905831, 0.569112  , 0.61375936, 0.03490587,
       0.64634279, 0.9409898 , 0.24619551, 0.22472434, 0.21680443,
       0.63380991, 0.41160257, 0.26747305, 0.71710442, 0.73195065,
       0.33977139, 0.14906114, 0.32243892, 0.41102513, 0.97981951,
       0.32354176, 0.13338406, 0.96530454, 0.37697958, 0.58925074,
       0.5118697 , 0.7011616 , 0.56577193, 0.89978856, 0.06694628,
       0.1451009 , 0.78952558, 0.29044126, 0.77462884, 0.70439291,
       0.26220248, 0.0812069 , 0.37428393, 0.60901304, 0.11356039,
       0.8108531 , 0.90922844, 0.3047387 , 0.46115983, 0.12282138,
       0.37409591, 0.29274103, 0.34336415, 0.94420477, 0.59802407,
       0.96621301, 0.52459343, 0.4473097 , 0.23599171, 0.4387869 ,
       0.00711722, 0.49115416, 0.87870283, 0.85252408, 0.03427555,
       0.69993432, 0.80890426, 0.50099422, 0.09823683, 0.4959186 ,
       0.11228455, 0.09399899, 0.37606307, 0.39618657, 0.71827956,
       0.15731519, 0.74143974, 0.25827155, 0.06603793, 0.83218567,
       0.05734466, 0.09995553, 0.37733917, 0.4047782 , 0.7743912 ,
       0.6280954 , 0.31088411, 0.37152657, 0.33036759, 0.3972916 ,
       0.08763603, 0.92893756, 0.0075224 , 0.20324397, 0.25612363,
       0.66078175, 0.45139493, 0.8133588 , 0.03849209, 0.36446788,
       0.33569077, 0.38257042, 0.95437007, 0.50114713, 0.95017012,
       0.85015482, 0.40537681, 0.89228124, 0.2382518 , 0.21142025,
       0.36415521, 0.9537017 , 0.74067014, 0.94395409, 0.27728102,
       0.64649142, 0.07659922, 0.40644907, 0.59164512, 0.51923638,
       0.43035379, 0.87966218, 0.89455495, 0.15593542, 0.33794518,
       0.60243432, 0.45777117, 0.16852112, 0.93135588, 0.96850157,
       0.73015551, 0.90487219, 0.05981706, 0.30891846, 0.1689543 ,
       0.24128966, 0.99696593, 0.39869539, 0.76471649, 0.04302965,
       0.74425306, 0.19246117, 0.91938529, 0.78567403, 0.68578256,
       0.30458019, 0.64942762, 0.05747618, 0.68685997, 0.06788212,
       0.03971885, 0.65076984, 0.74262235, 0.09365935, 0.8217872 ,
       0.27629588, 0.77163632, 0.09311764, 0.7230906 , 0.13517893,
       0.80723625, 0.39405776, 0.88143652, 0.60943674, 0.47260246,
       0.56427518, 0.42990164, 0.07897325, 0.65061639, 0.39909603,
       0.85987968, 0.20289437, 0.76310708, 0.67069814, 0.98963849,
       0.76657601, 0.69473803, 0.63762173, 0.97543309, 0.40838957,
       0.06053334, 0.59528837, 0.17438748, 0.21998998, 0.95291242,
       0.16537175, 0.6779641 , 0.19591758, 0.11273715, 0.69001371,
       0.86965967, 0.85825533, 0.10634147, 0.04929233, 0.42344313,
       0.39377393, 0.04448964, 0.96374066, 0.5914227 , 0.6646387 ,
       0.92009997, 0.58871365, 0.30325872, 0.99753124, 0.80641611,
       0.00394107, 0.5561184 , 0.20471847, 0.07270438, 0.07626532,
       0.94603045, 0.16147787, 0.93477571, 0.84640749, 0.12053339,
       0.82506437, 0.61548349, 0.30895574, 0.28976299, 0.86999097,
       0.63606843, 0.92066642, 0.03870936, 0.52025713, 0.54580177,
       0.65273424, 0.5862381 , 0.3687581 , 0.03786412, 0.4383649 ,
       0.91150514, 0.54104385, 0.85659216, 0.08889009, 0.25126462,
       0.44357343, 0.21314494, 0.84758425, 0.95223245, 0.7241728 ,
       0.27099997, 0.98967991, 0.42047967, 0.99695583, 0.41568848,
       0.69809981, 0.97476563, 0.95505288, 0.1860483 , 0.3360207 ,
       0.97855843, 0.10138034, 0.48091311, 0.474716  , 0.30683955,
       0.21685059, 0.33213064, 0.92186279, 0.85113041, 0.72912674,
       0.06292925, 0.33012646, 0.74454344, 0.74520898, 0.38016061,
       0.63080843, 0.05128158, 0.31954983, 0.18331416, 0.80574227,
       0.54402428, 0.20146088, 0.19544049, 0.97058678, 0.05050276,
       0.27178254, 0.94737236, 0.38720345, 0.49996419, 0.65103777,
       0.51798637, 0.06968636, 0.79598703, 0.96315837, 0.64674035,
       0.89947215, 0.96484312, 0.12825541, 0.98460179, 0.18512496,
       0.94825503, 0.89351525, 0.76902123, 0.46538806, 0.34614961,
       0.3757089 , 0.30082362, 0.52235989, 0.36378383, 0.05267097,
       0.00770014, 0.75020061, 0.24053669, 0.59239142, 0.25238651,
       0.97237425, 0.81940364, 0.31181455, 0.86605559, 0.25056115,
       0.68713875, 0.27191048, 0.04891672, 0.50423455, 0.33105868,
       0.6719223 , 0.47348108, 0.0894574 , 0.54565665, 0.99111773,
       0.24029675, 0.3678311 , 0.992504  , 0.41134443, 0.47320033,
       0.72745273, 0.0155437 , 0.23346991, 0.95402606, 0.32024371,
       0.91307286, 0.09391061, 0.84983745, 0.28583848, 0.31802392,
       0.50736316, 0.39418534, 0.97055908, 0.47765698, 0.14795234,
       0.93277158, 0.49242559, 0.71693412, 0.67153084, 0.40522824,
       0.58479562, 0.84033233, 0.58231323, 0.3833848 , 0.54613725,
       0.84737044, 0.9841668 , 0.15494051, 0.65891349, 0.41543703,
       0.95960315, 0.15632304, 0.89648331, 0.89955472, 0.91330503,
       0.5754215 , 0.88535889, 0.34162404, 0.51420424, 0.06086009,
       0.28973359, 0.08683671, 0.83627772, 0.89486441, 0.41582136,
       0.15136814, 0.65917068, 0.60664823, 0.45033861, 0.55860093,
       0.0420846 , 0.62453864, 0.07646132, 0.78696348, 0.20373452,
       0.64865774, 0.35827   , 0.35213406, 0.03927624, 0.93286269,
       0.38989271, 0.63710376, 0.32240928, 0.42718269, 0.9384704 ,
       0.24793425, 0.24062895, 0.14242501, 0.79495689, 0.15242029,
       0.71280149, 0.38158405, 0.08720126, 0.75094427, 0.03629674,
       0.68702673, 0.45934263, 0.02888943, 0.87816693, 0.98336266,
       0.80125239, 0.81810285, 0.83749074, 0.99409042, 0.45533772,
       0.14565299, 0.95632429, 0.17870716, 0.64176407, 0.27381541,
       0.35029398, 0.53521352, 0.67532661, 0.1815909 , 0.39764766,
       0.14390839, 0.57146137, 0.0798894 , 0.49696472, 0.33225455,
       0.12532163, 0.63531197, 0.11234602, 0.01784642, 0.19662243,
       0.38760177, 0.56479334, 0.50419242, 0.43187519, 0.79919209,
       0.09993416, 0.02584015, 0.46591894, 0.23795671, 0.97461189,
       0.66739422, 0.52359223, 0.06515911, 0.94199719, 0.94089253,
       0.48998151, 0.28605326, 0.62971592, 0.64137941, 0.9346019 ,
       0.67561103, 0.63428812, 0.20380632, 0.20506752, 0.83283749,
       0.75900055, 0.2618975 , 0.51226921, 0.66863906, 0.33030789,
       0.27479984, 0.46732075, 0.81493678, 0.67597326, 0.60775389,
       0.86892143, 0.86132859, 0.82406376, 0.27658263, 0.12871762,
       0.22839314, 0.76255881, 0.39675997, 0.3127158 , 0.79750383,
       0.17779946, 0.81568692, 0.25360429, 0.0863508 , 0.98964108,
       0.03569989, 0.49405302, 0.92784943, 0.24722641, 0.73474994,
       0.81943644, 0.6372986 , 0.34448382, 0.84791812, 0.97713204,
       0.97998883, 0.28578969, 0.49173279, 0.00474334, 0.4439336 ])

## Efficiently combining, counting, and iterating

In [104]:
names=['Bulbasaur','Charmander','Squirtle']
hps=[45,39,44]

In [107]:
combined=[]
for i, pokemon in enumerate(names):
    combined.append((pokemon,hps[i]))
print(combined)

[('Bulbasaur', 45), ('Charmander', 39), ('Squirtle', 44)]

But Python's built-in function zip provides a more elegent solution.

In [125]:
combined_zip=zip(names,hps)

In [126]:
# You can unpack zip in that way
combined_list=[*combined_zip]

In [129]:
combined_list

[('Bulbasaur', 45), ('Charmander', 39), ('Squirtle', 44)]

### Collections Module

Alternatives to general purpose dict, list, set, and tuple.A few notable datatypes are lested here:
* namedtuple: tupble subclasses with named fields
* deque: list-like container with fast appends and pops.
* Counter: dict for counting hashable objects.
* OrderedDict: dict that retains order of entries.
* defaultict: dict that calls a factory function to supply missing values

In [130]:
import pandas as pd
df=pd.read_csv('baseball_stats.csv')
df.head()

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG
0,ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415
1,ATL,NL,2012,700,600,94,0.320,0.389,0.247,1,4.0,5.0,162,0.306,0.378
2,BAL,AL,2012,712,705,93,0.311,0.417,0.247,1,5.0,4.0,162,0.315,0.403
3,BOS,AL,2012,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428
4,CHC,NL,2012,613,759,61,0.302,0.378,0.240,0,NaN,NaN,162,0.335,0.424

In [137]:
df.shape

(1232, 15)

In [138]:
pok=pd.read_csv('Pokemon.csv')
pok.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [142]:
list_pok_types=pok['Type 1'].to_list()

In [146]:
type_counts={}
for types in list_pok_types:
    if types not in type_counts:
        type_counts[types]=1
    else:
        type_counts[types]+=1
print(type_counts)

{'Grass': 70, 'Fire': 52, 'Water': 112, 'Bug': 69, 'Normal': 98, 'Poison': 28, 'Electric': 44, 'Ground': 32, 'Fairy': 17, 'Fighting': 27, 'Psychic': 57, 'Rock': 44, 'Ghost': 32, 'Ice': 24, 'Dragon': 32, 'Dark': 31, 'Steel': 27, 'Flying': 4}

Using Counter is much more efficient way since it does not requires a loop.

In [148]:
from collections import Counter
# No need for a loop
type_counts=Counter(list_pok_types)
print(type_counts)

Counter({'Water': 112, 'Normal': 98, 'Grass': 70, 'Bug': 69, 'Psychic': 57, 'Fire': 52, 'Electric': 44, 'Rock': 44, 'Ground': 32, 'Ghost': 32, 'Dragon': 32, 'Dark': 31, 'Poison': 28, 'Fighting': 27, 'Steel': 27, 'Ice': 24, 'Fairy': 17, 'Flying': 4})

It's ordered by highest to lowest counts. Using Counter takes half the time as the standard dictionary approach.

### Itertools Module
* Functional tools for creating and using iterators.
* Notable:
  - Infinite iterators: count, cycle, repeat
  - Finite iterators: accumulate, chain, zip_longest, etc.
  - Combination generators: product, permutations, combinations.

##### Combination with loop
Suppose we want to gather all combination pairs of Pokemon types possible.

In [169]:
poke_list=['Geodude', 'Cubone', 'Lickitung', 'Persian', 'Diglett']
combos=[]
for x in poke_list:
    for y in poke_list:
        if x==y:
            continue
        if ((x,y) not in combos) & ((y,x) not in combos):
            combos.append((x,y))
print(combos)

[('Geodude', 'Cubone'), ('Geodude', 'Lickitung'), ('Geodude', 'Persian'), ('Geodude', 'Diglett'), ('Cubone', 'Lickitung'), ('Cubone', 'Persian'), ('Cubone', 'Diglett'), ('Lickitung', 'Persian'), ('Lickitung', 'Diglett'), ('Persian', 'Diglett')]

In [170]:
# A more efficient way
from itertools import combinations
combos_obj=combinations(poke_list,2)
combos=[*combos_obj]
print(combos)

[('Geodude', 'Cubone'), ('Geodude', 'Lickitung'), ('Geodude', 'Persian'), ('Geodude', 'Diglett'), ('Cubone', 'Lickitung'), ('Cubone', 'Persian'), ('Cubone', 'Diglett'), ('Lickitung', 'Persian'), ('Lickitung', 'Diglett'), ('Persian', 'Diglett')]

If comparint runtimes, we'd see using combinations is significantly faster than the nested loop.

In [171]:
combos_4 = [*combinations(poke_list, 4)]
print(combos_4)

[('Geodude', 'Cubone', 'Lickitung', 'Persian'), ('Geodude', 'Cubone', 'Lickitung', 'Diglett'), ('Geodude', 'Cubone', 'Persian', 'Diglett'), ('Geodude', 'Lickitung', 'Persian', 'Diglett'), ('Cubone', 'Lickitung', 'Persian', 'Diglett')]

In [157]:
pok

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [160]:
pok_names=pok.Name.to_list()
pok_type_1=pok['Type 1'].to_list()
pok_type_2=pok['Type 2'].to_list()

In [165]:
name_and_type=[*zip(pok_names[:5],pok_type_1[:5])]
print(name_and_type)

[('Bulbasaur', 'Grass'), ('Ivysaur', 'Grass'), ('Venusaur', 'Grass'), ('VenusaurMega Venusaur', 'Grass'), ('Charmander', 'Fire')]

In [167]:
name_and_types=[*zip(pok_names[:5],pok_type_1[:5],pok_type_2[:5])]
print(name_and_types)

[('Bulbasaur', 'Grass', 'Poison'), ('Ivysaur', 'Grass', 'Poison'), ('Venusaur', 'Grass', 'Poison'), ('VenusaurMega Venusaur', 'Grass', 'Poison'), ('Charmander', 'Fire', nan)]

In [168]:
# Collect the count of generations
gen_count = Counter(pok.Generation.to_list())
print(gen_count, '\n')

# Use list comprehension to get each Pokémon's starting letter
starting_letters = [name[0] for name in pok_names]

# Collect the count of Pokémon for each starting_letter
starting_letters_count = Counter(starting_letters)
print(starting_letters_count)

Counter({1: 166, 5: 165, 3: 160, 4: 121, 2: 106, 6: 82})

Counter({'S': 112, 'M': 67, 'C': 58, 'G': 58, 'P': 53, 'D': 46, 'B': 43, 'A': 42, 'T': 40, 'L': 39, 'R': 31, 'H': 31, 'K': 28, 'F': 26, 'V': 23, 'W': 23, 'E': 21, 'N': 16, 'Z': 10, 'J': 7, 'O': 6, 'I': 5, 'U': 5, 'Q': 4, 'Y': 4, 'X': 2})

### Set Theory
Python has built-in set datatype with accompanying methods:
- intersection()
- difference()
- symmetric_difference(): all elements in exactly one set
- union(): all elements that are in either set

In [194]:
list_a=pok_names[:5]
list_b=pok_names[15:20]+['Bulbasaur']
set_a=set(list_a)
print(set_a)
set_b=set(list_b)
print(set_b)

{'Bulbasaur', 'Venusaur', 'Ivysaur', 'VenusaurMega Venusaur', 'Charmander'}
{'Bulbasaur', 'Beedrill', 'Weedle', 'BeedrillMega Beedrill', 'Butterfree', 'Kakuna'}

In [195]:
set_a.intersection(set_b)

{'Bulbasaur'}

In [196]:
set_a.union(set_b)

{'Beedrill',
 'BeedrillMega Beedrill',
 'Bulbasaur',
 'Butterfree',
 'Charmander',
 'Ivysaur',
 'Kakuna',
 'Venusaur',
 'VenusaurMega Venusaur',
 'Weedle'}

In [197]:
set_a.symmetric_difference(set_b)

{'Beedrill',
 'BeedrillMega Beedrill',
 'Butterfree',
 'Charmander',
 'Ivysaur',
 'Kakuna',
 'Venusaur',
 'VenusaurMega Venusaur',
 'Weedle'}

Using sets is a much faster approach.

In [198]:
set_a.difference(set_b)

{'Charmander', 'Ivysaur', 'Venusaur', 'VenusaurMega Venusaur'}

In [199]:
set_b.difference(set_a)

{'Beedrill', 'BeedrillMega Beedrill', 'Butterfree', 'Kakuna', 'Weedle'}

In [202]:
set_types=set(pok_type_1)
print(set_types)

{'Dark', 'Rock', 'Poison', 'Steel', 'Flying', 'Bug', 'Ice', 'Dragon', 'Water', 'Normal', 'Fire', 'Ground', 'Fairy', 'Grass', 'Fighting', 'Electric', 'Ghost', 'Psychic'}

In [203]:
print('Psyduck'  in set_a)
print('Psyduck'  in set_b)

False
False

In [204]:
pok

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [205]:
pok.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [210]:
pok_stats=pok[['HP','Attack','Defense','Sp. Atk','Sp. Def','Speed']]

In [217]:
pok_stats_list=pok_stats[['HP','Attack','Defense','Sp. Atk','Sp. Def','Speed']].values.tolist()

In [218]:
totals_map=[*map(sum, pok_stats_list)]

In [221]:
pok_stats_np=pok_stats[['HP','Attack','Defense','Sp. Atk','Sp. Def','Speed']].values

In [222]:
# Specifiying axis=1 means that we calculate an average across the column values.
avgs_np=pok_stats_np.mean(axis=1)

It's significantly haster than using a loop.

In [228]:
total_np=pok_stats_np.sum(axis=1)

In [229]:
poke_list_np = [*zip(pok_names, total_np, avgs_np)]

In [230]:
poke_list_np

[('Bulbasaur', 318, 53.0),
 ('Ivysaur', 405, 67.5),
 ('Venusaur', 525, 87.5),
 ('VenusaurMega Venusaur', 625, 104.16666666666667),
 ('Charmander', 309, 51.5),
 ('Charmeleon', 405, 67.5),
 ('Charizard', 534, 89.0),
 ('CharizardMega Charizard X', 634, 105.66666666666667),
 ('CharizardMega Charizard Y', 634, 105.66666666666667),
 ('Squirtle', 314, 52.333333333333336),
 ('Wartortle', 405, 67.5),
 ('Blastoise', 530, 88.33333333333333),
 ('BlastoiseMega Blastoise', 630, 105.0),
 ('Caterpie', 195, 32.5),
 ('Metapod', 205, 34.166666666666664),
 ('Butterfree', 395, 65.83333333333333),
 ('Weedle', 195, 32.5),
 ('Kakuna', 205, 34.166666666666664),
 ('Beedrill', 395, 65.83333333333333),
 ('BeedrillMega Beedrill', 495, 82.5),
 ('Pidgey', 251, 41.833333333333336),
 ('Pidgeotto', 349, 58.166666666666664),
 ('Pidgeot', 479, 79.83333333333333),
 ('PidgeotMega Pidgeot', 579, 96.5),
 ('Rattata', 253, 42.166666666666664),
 ('Raticate', 413, 68.83333333333333),
 ('Spearow', 262, 43.666666666666664),
 ('Fearow', 442, 73.66666666666667),
 ('Ekans', 288, 48.0),
 ('Arbok', 438, 73.0),
 ('Pikachu', 320, 53.333333333333336),
 ('Raichu', 485, 80.83333333333333),
 ('Sandshrew', 300, 50.0),
 ('Sandslash', 450, 75.0),
 ('Nidoran♀', 275, 45.833333333333336),
 ('Nidorina', 365, 60.833333333333336),
 ('Nidoqueen', 505, 84.16666666666667),
 ('Nidoran♂', 273, 45.5),
 ('Nidorino', 365, 60.833333333333336),
 ('Nidoking', 505, 84.16666666666667),
 ('Clefairy', 323, 53.833333333333336),
 ('Clefable', 483, 80.5),
 ('Vulpix', 299, 49.833333333333336),
 ('Ninetales', 505, 84.16666666666667),
 ('Jigglypuff', 270, 45.0),
 ('Wigglytuff', 435, 72.5),
 ('Zubat', 245, 40.833333333333336),
 ('Golbat', 455, 75.83333333333333),
 ('Oddish', 320, 53.333333333333336),
 ('Gloom', 395, 65.83333333333333),
 ('Vileplume', 490, 81.66666666666667),
 ('Paras', 285, 47.5),
 ('Parasect', 405, 67.5),
 ('Venonat', 305, 50.833333333333336),
 ('Venomoth', 450, 75.0),
 ('Diglett', 265, 44.166666666666664),
 ('Dugtrio', 405, 67.5),
 ('Meowth', 290, 48.333333333333336),
 ('Persian', 440, 73.33333333333333),
 ('Psyduck', 320, 53.333333333333336),
 ('Golduck', 500, 83.33333333333333),
 ('Mankey', 305, 50.833333333333336),
 ('Primeape', 455, 75.83333333333333),
 ('Growlithe', 350, 58.333333333333336),
 ('Arcanine', 555, 92.5),
 ('Poliwag', 300, 50.0),
 ('Poliwhirl', 385, 64.16666666666667),
 ('Poliwrath', 510, 85.0),
 ('Abra', 310, 51.666666666666664),
 ('Kadabra', 400, 66.66666666666667),
 ('Alakazam', 500, 83.33333333333333),
 ('AlakazamMega Alakazam', 590, 98.33333333333333),
 ('Machop', 305, 50.833333333333336),
 ('Machoke', 405, 67.5),
 ('Machamp', 505, 84.16666666666667),
 ('Bellsprout', 300, 50.0),
 ('Weepinbell', 390, 65.0),
 ('Victreebel', 490, 81.66666666666667),
 ('Tentacool', 335, 55.833333333333336),
 ('Tentacruel', 515, 85.83333333333333),
 ('Geodude', 300, 50.0),
 ('Graveler', 390, 65.0),
 ('Golem', 495, 82.5),
 ('Ponyta', 410, 68.33333333333333),
 ('Rapidash', 500, 83.33333333333333),
 ('Slowpoke', 315, 52.5),
 ('Slowbro', 490, 81.66666666666667),
 ('SlowbroMega Slowbro', 590, 98.33333333333333),
 ('Magnemite', 325, 54.166666666666664),
 ('Magneton', 465, 77.5),
 ("Farfetch'd", 352, 58.666666666666664),
 ('Doduo', 310, 51.666666666666664),
 ('Dodrio', 460, 76.66666666666667),
 ('Seel', 325, 54.166666666666664),
 ('Dewgong', 475, 79.16666666666667),
 ('Grimer', 325, 54.166666666666664),
 ('Muk', 500, 83.33333333333333),
 ('Shellder', 305, 50.833333333333336),
 ('Cloyster', 525, 87.5),
 ('Gastly', 310, 51.666666666666664),
 ('Haunter', 405, 67.5),
 ('Gengar', 500, 83.33333333333333),
 ('GengarMega Gengar', 600, 100.0),
 ('Onix', 385, 64.16666666666667),
 ('Drowzee', 328, 54.666666666666664),
 ('Hypno', 483, 80.5),
 ('Krabby', 325, 54.166666666666664),
 ('Kingler', 475, 79.16666666666667),
 ('Voltorb', 330, 55.0),
 ('Electrode', 480, 80.0),
 ('Exeggcute', 325, 54.166666666666664),
 ('Exeggutor', 520, 86.66666666666667),
 ('Cubone', 320, 53.333333333333336),
 ('Marowak', 425, 70.83333333333333),
 ('Hitmonlee', 455, 75.83333333333333),
 ('Hitmonchan', 455, 75.83333333333333),
 ('Lickitung', 385, 64.16666666666667),
 ('Koffing', 340, 56.666666666666664),
 ('Weezing', 490, 81.66666666666667),
 ('Rhyhorn', 345, 57.5),
 ('Rhydon', 485, 80.83333333333333),
 ('Chansey', 450, 75.0),
 ('Tangela', 435, 72.5),
 ('Kangaskhan', 490, 81.66666666666667),
 ('KangaskhanMega Kangaskhan', 590, 98.33333333333333),
 ('Horsea', 295, 49.166666666666664),
 ('Seadra', 440, 73.33333333333333),
 ('Goldeen', 320, 53.333333333333336),
 ('Seaking', 450, 75.0),
 ('Staryu', 340, 56.666666666666664),
 ('Starmie', 520, 86.66666666666667),
 ('Mr. Mime', 460, 76.66666666666667),
 ('Scyther', 500, 83.33333333333333),
 ('Jynx', 455, 75.83333333333333),
 ('Electabuzz', 490, 81.66666666666667),
 ('Magmar', 495, 82.5),
 ('Pinsir', 500, 83.33333333333333),
 ('PinsirMega Pinsir', 600, 100.0),
 ('Tauros', 490, 81.66666666666667),
 ('Magikarp', 200, 33.333333333333336),
 ('Gyarados', 540, 90.0),
 ('GyaradosMega Gyarados', 640, 106.66666666666667),
 ('Lapras', 535, 89.16666666666667),
 ('Ditto', 288, 48.0),
 ('Eevee', 325, 54.166666666666664),
 ('Vaporeon', 525, 87.5),
 ('Jolteon', 525, 87.5),
 ('Flareon', 525, 87.5),
 ('Porygon', 395, 65.83333333333333),
 ('Omanyte', 355, 59.166666666666664),
 ('Omastar', 495, 82.5),
 ('Kabuto', 355, 59.166666666666664),
 ('Kabutops', 495, 82.5),
 ('Aerodactyl', 515, 85.83333333333333),
 ('AerodactylMega Aerodactyl', 615, 102.5),
 ('Snorlax', 540, 90.0),
 ('Articuno', 580, 96.66666666666667),
 ('Zapdos', 580, 96.66666666666667),
 ('Moltres', 580, 96.66666666666667),
 ('Dratini', 300, 50.0),
 ('Dragonair', 420, 70.0),
 ('Dragonite', 600, 100.0),
 ('Mewtwo', 680, 113.33333333333333),
 ('MewtwoMega Mewtwo X', 780, 130.0),
 ('MewtwoMega Mewtwo Y', 780, 130.0),
 ('Mew', 600, 100.0),
 ('Chikorita', 318, 53.0),
 ('Bayleef', 405, 67.5),
 ('Meganium', 525, 87.5),
 ('Cyndaquil', 309, 51.5),
 ('Quilava', 405, 67.5),
 ('Typhlosion', 534, 89.0),
 ('Totodile', 314, 52.333333333333336),
 ('Croconaw', 405, 67.5),
 ('Feraligatr', 530, 88.33333333333333),
 ('Sentret', 215, 35.833333333333336),
 ('Furret', 415, 69.16666666666667),
 ('Hoothoot', 262, 43.666666666666664),
 ('Noctowl', 442, 73.66666666666667),
 ('Ledyba', 265, 44.166666666666664),
 ('Ledian', 390, 65.0),
 ('Spinarak', 250, 41.666666666666664),
 ('Ariados', 390, 65.0),
 ('Crobat', 535, 89.16666666666667),
 ('Chinchou', 330, 55.0),
 ('Lanturn', 460, 76.66666666666667),
 ('Pichu', 205, 34.166666666666664),
 ('Cleffa', 218, 36.333333333333336),
 ('Igglybuff', 210, 35.0),
 ('Togepi', 245, 40.833333333333336),
 ('Togetic', 405, 67.5),
 ('Natu', 320, 53.333333333333336),
 ('Xatu', 470, 78.33333333333333),
 ('Mareep', 280, 46.666666666666664),
 ('Flaaffy', 365, 60.833333333333336),
 ('Ampharos', 510, 85.0),
 ('AmpharosMega Ampharos', 610, 101.66666666666667),
 ('Bellossom', 490, 81.66666666666667),
 ('Marill', 250, 41.666666666666664),
 ('Azumarill', 420, 70.0),
 ('Sudowoodo', 410, 68.33333333333333),
 ('Politoed', 500, 83.33333333333333),
 ('Hoppip', 250, 41.666666666666664),
 ('Skiploom', 340, 56.666666666666664),
 ('Jumpluff', 460, 76.66666666666667),
 ('Aipom', 360, 60.0),
 ('Sunkern', 180, 30.0),
 ('Sunflora', 425, 70.83333333333333),
 ('Yanma', 390, 65.0),
 ('Wooper', 210, 35.0),
 ('Quagsire', 430, 71.66666666666667),
 ('Espeon', 525, 87.5),
 ('Umbreon', 525, 87.5),
 ('Murkrow', 405, 67.5),
 ('Slowking', 490, 81.66666666666667),
 ('Misdreavus', 435, 72.5),
 ('Unown', 336, 56.0),
 ('Wobbuffet', 405, 67.5),
 ('Girafarig', 455, 75.83333333333333),
 ('Pineco', 290, 48.333333333333336),
 ('Forretress', 465, 77.5),
 ('Dunsparce', 415, 69.16666666666667),
 ('Gligar', 430, 71.66666666666667),
 ('Steelix', 510, 85.0),
 ('SteelixMega Steelix', 610, 101.66666666666667),
 ('Snubbull', 300, 50.0),
 ('Granbull', 450, 75.0),
 ('Qwilfish', 430, 71.66666666666667),
 ('Scizor', 500, 83.33333333333333),
 ('ScizorMega Scizor', 600, 100.0),
 ('Shuckle', 505, 84.16666666666667),
 ('Heracross', 500, 83.33333333333333),
 ('HeracrossMega Heracross', 600, 100.0),
 ('Sneasel', 430, 71.66666666666667),
 ('Teddiursa', 330, 55.0),
 ('Ursaring', 500, 83.33333333333333),
 ('Slugma', 250, 41.666666666666664),
 ('Magcargo', 410, 68.33333333333333),
 ('Swinub', 250, 41.666666666666664),
 ('Piloswine', 450, 75.0),
 ('Corsola', 380, 63.333333333333336),
 ('Remoraid', 300, 50.0),
 ('Octillery', 480, 80.0),
 ('Delibird', 330, 55.0),
 ('Mantine', 465, 77.5),
 ('Skarmory', 465, 77.5),
 ('Houndour', 330, 55.0),
 ('Houndoom', 500, 83.33333333333333),
 ('HoundoomMega Houndoom', 600, 100.0),
 ('Kingdra', 540, 90.0),
 ('Phanpy', 330, 55.0),
 ('Donphan', 500, 83.33333333333333),
 ('Porygon2', 515, 85.83333333333333),
 ('Stantler', 465, 77.5),
 ('Smeargle', 250, 41.666666666666664),
 ('Tyrogue', 210, 35.0),
 ('Hitmontop', 455, 75.83333333333333),
 ('Smoochum', 305, 50.833333333333336),
 ('Elekid', 360, 60.0),
 ('Magby', 365, 60.833333333333336),
 ('Miltank', 490, 81.66666666666667),
 ('Blissey', 540, 90.0),
 ('Raikou', 580, 96.66666666666667),
 ('Entei', 580, 96.66666666666667),
 ('Suicune', 580, 96.66666666666667),
 ('Larvitar', 300, 50.0),
 ('Pupitar', 410, 68.33333333333333),
 ('Tyranitar', 600, 100.0),
 ('TyranitarMega Tyranitar', 700, 116.66666666666667),
 ('Lugia', 680, 113.33333333333333),
 ('Ho-oh', 680, 113.33333333333333),
 ('Celebi', 600, 100.0),
 ('Treecko', 310, 51.666666666666664),
 ('Grovyle', 405, 67.5),
 ('Sceptile', 530, 88.33333333333333),
 ('SceptileMega Sceptile', 630, 105.0),
 ('Torchic', 310, 51.666666666666664),
 ('Combusken', 405, 67.5),
 ('Blaziken', 530, 88.33333333333333),
 ('BlazikenMega Blaziken', 630, 105.0),
 ('Mudkip', 310, 51.666666666666664),
 ('Marshtomp', 405, 67.5),
 ('Swampert', 535, 89.16666666666667),
 ('SwampertMega Swampert', 635, 105.83333333333333),
 ('Poochyena', 220, 36.666666666666664),
 ('Mightyena', 420, 70.0),
 ('Zigzagoon', 240, 40.0),
 ('Linoone', 420, 70.0),
 ('Wurmple', 195, 32.5),
 ('Silcoon', 205, 34.166666666666664),
 ('Beautifly', 395, 65.83333333333333),
 ('Cascoon', 205, 34.166666666666664),
 ('Dustox', 385, 64.16666666666667),
 ('Lotad', 220, 36.666666666666664),
 ('Lombre', 340, 56.666666666666664),
 ('Ludicolo', 480, 80.0),
 ('Seedot', 220, 36.666666666666664),
 ('Nuzleaf', 340, 56.666666666666664),
 ('Shiftry', 480, 80.0),
 ('Taillow', 270, 45.0),
 ('Swellow', 430, 71.66666666666667),
 ('Wingull', 270, 45.0),
 ('Pelipper', 430, 71.66666666666667),
 ('Ralts', 198, 33.0),
 ('Kirlia', 278, 46.333333333333336),
 ('Gardevoir', 518, 86.33333333333333),
 ('GardevoirMega Gardevoir', 618, 103.0),
 ('Surskit', 269, 44.833333333333336),
 ('Masquerain', 414, 69.0),
 ('Shroomish', 295, 49.166666666666664),
 ('Breloom', 460, 76.66666666666667),
 ('Slakoth', 280, 46.666666666666664),
 ('Vigoroth', 440, 73.33333333333333),
 ('Slaking', 670, 111.66666666666667),
 ('Nincada', 266, 44.333333333333336),
 ('Ninjask', 456, 76.0),
 ('Shedinja', 236, 39.333333333333336),
 ('Whismur', 240, 40.0),
 ('Loudred', 360, 60.0),
 ('Exploud', 490, 81.66666666666667),
 ('Makuhita', 237, 39.5),
 ('Hariyama', 474, 79.0),
 ('Azurill', 190, 31.666666666666668),
 ('Nosepass', 375, 62.5),
 ('Skitty', 260, 43.333333333333336),
 ('Delcatty', 380, 63.333333333333336),
 ('Sableye', 380, 63.333333333333336),
 ('SableyeMega Sableye', 480, 80.0),
 ('Mawile', 380, 63.333333333333336),
 ('MawileMega Mawile', 480, 80.0),
 ('Aron', 330, 55.0),
 ('Lairon', 430, 71.66666666666667),
 ('Aggron', 530, 88.33333333333333),
 ('AggronMega Aggron', 630, 105.0),
 ('Meditite', 280, 46.666666666666664),
 ('Medicham', 410, 68.33333333333333),
 ('MedichamMega Medicham', 510, 85.0),
 ('Electrike', 295, 49.166666666666664),
 ('Manectric', 475, 79.16666666666667),
 ('ManectricMega Manectric', 575, 95.83333333333333),
 ('Plusle', 405, 67.5),
 ('Minun', 405, 67.5),
 ('Volbeat', 400, 66.66666666666667),
 ('Illumise', 400, 66.66666666666667),
 ('Roselia', 400, 66.66666666666667),
 ('Gulpin', 302, 50.333333333333336),
 ('Swalot', 467, 77.83333333333333),
 ('Carvanha', 305, 50.833333333333336),
 ('Sharpedo', 460, 76.66666666666667),
 ('SharpedoMega Sharpedo', 560, 93.33333333333333),
 ('Wailmer', 400, 66.66666666666667),
 ('Wailord', 500, 83.33333333333333),
 ('Numel', 305, 50.833333333333336),
 ('Camerupt', 460, 76.66666666666667),
 ('CameruptMega Camerupt', 560, 93.33333333333333),
 ('Torkoal', 470, 78.33333333333333),
 ('Spoink', 330, 55.0),
 ('Grumpig', 470, 78.33333333333333),
 ('Spinda', 360, 60.0),
 ('Trapinch', 290, 48.333333333333336),
 ('Vibrava', 340, 56.666666666666664),
 ('Flygon', 520, 86.66666666666667),
 ('Cacnea', 335, 55.833333333333336),
 ('Cacturne', 475, 79.16666666666667),
 ('Swablu', 310, 51.666666666666664),
 ('Altaria', 490, 81.66666666666667),
 ('AltariaMega Altaria', 590, 98.33333333333333),
 ('Zangoose', 458, 76.33333333333333),
 ('Seviper', 458, 76.33333333333333),
 ('Lunatone', 440, 73.33333333333333),
 ('Solrock', 440, 73.33333333333333),
 ('Barboach', 288, 48.0),
 ('Whiscash', 468, 78.0),
 ('Corphish', 308, 51.333333333333336),
 ('Crawdaunt', 468, 78.0),
 ('Baltoy', 300, 50.0),
 ('Claydol', 500, 83.33333333333333),
 ('Lileep', 355, 59.166666666666664),
 ('Cradily', 495, 82.5),
 ('Anorith', 355, 59.166666666666664),
 ('Armaldo', 495, 82.5),
 ('Feebas', 200, 33.333333333333336),
 ('Milotic', 540, 90.0),
 ('Castform', 420, 70.0),
 ('Kecleon', 440, 73.33333333333333),
 ('Shuppet', 295, 49.166666666666664),
 ('Banette', 455, 75.83333333333333),
 ('BanetteMega Banette', 555, 92.5),
 ('Duskull', 295, 49.166666666666664),
 ('Dusclops', 455, 75.83333333333333),
 ('Tropius', 460, 76.66666666666667),
 ('Chimecho', 425, 70.83333333333333),
 ('Absol', 465, 77.5),
 ('AbsolMega Absol', 565, 94.16666666666667),
 ('Wynaut', 260, 43.333333333333336),
 ('Snorunt', 300, 50.0),
 ('Glalie', 480, 80.0),
 ('GlalieMega Glalie', 580, 96.66666666666667),
 ('Spheal', 290, 48.333333333333336),
 ('Sealeo', 410, 68.33333333333333),
 ('Walrein', 530, 88.33333333333333),
 ('Clamperl', 345, 57.5),
 ('Huntail', 485, 80.83333333333333),
 ('Gorebyss', 485, 80.83333333333333),
 ('Relicanth', 485, 80.83333333333333),
 ('Luvdisc', 330, 55.0),
 ('Bagon', 300, 50.0),
 ('Shelgon', 420, 70.0),
 ('Salamence', 600, 100.0),
 ('SalamenceMega Salamence', 700, 116.66666666666667),
 ('Beldum', 300, 50.0),
 ('Metang', 420, 70.0),
 ('Metagross', 600, 100.0),
 ('MetagrossMega Metagross', 700, 116.66666666666667),
 ('Regirock', 580, 96.66666666666667),
 ('Regice', 580, 96.66666666666667),
 ('Registeel', 580, 96.66666666666667),
 ('Latias', 600, 100.0),
 ('LatiasMega Latias', 700, 116.66666666666667),
 ('Latios', 600, 100.0),
 ('LatiosMega Latios', 700, 116.66666666666667),
 ('Kyogre', 670, 111.66666666666667),
 ('KyogrePrimal Kyogre', 770, 128.33333333333334),
 ('Groudon', 670, 111.66666666666667),
 ('GroudonPrimal Groudon', 770, 128.33333333333334),
 ('Rayquaza', 680, 113.33333333333333),
 ('RayquazaMega Rayquaza', 780, 130.0),
 ('Jirachi', 600, 100.0),
 ('DeoxysNormal Forme', 600, 100.0),
 ('DeoxysAttack Forme', 600, 100.0),
 ('DeoxysDefense Forme', 600, 100.0),
 ('DeoxysSpeed Forme', 600, 100.0),
 ('Turtwig', 318, 53.0),
 ('Grotle', 405, 67.5),
 ('Torterra', 525, 87.5),
 ('Chimchar', 309, 51.5),
 ('Monferno', 405, 67.5),
 ('Infernape', 534, 89.0),
 ('Piplup', 314, 52.333333333333336),
 ('Prinplup', 405, 67.5),
 ('Empoleon', 530, 88.33333333333333),
 ('Starly', 245, 40.833333333333336),
 ('Staravia', 340, 56.666666666666664),
 ('Staraptor', 485, 80.83333333333333),
 ('Bidoof', 250, 41.666666666666664),
 ('Bibarel', 410, 68.33333333333333),
 ('Kricketot', 194, 32.333333333333336),
 ('Kricketune', 384, 64.0),
 ('Shinx', 263, 43.833333333333336),
 ('Luxio', 363, 60.5),
 ('Luxray', 523, 87.16666666666667),
 ('Budew', 280, 46.666666666666664),
 ('Roserade', 515, 85.83333333333333),
 ('Cranidos', 350, 58.333333333333336),
 ('Rampardos', 495, 82.5),
 ('Shieldon', 350, 58.333333333333336),
 ('Bastiodon', 495, 82.5),
 ('Burmy', 224, 37.333333333333336),
 ('WormadamPlant Cloak', 424, 70.66666666666667),
 ('WormadamSandy Cloak', 424, 70.66666666666667),
 ('WormadamTrash Cloak', 424, 70.66666666666667),
 ('Mothim', 424, 70.66666666666667),
 ('Combee', 244, 40.666666666666664),
 ('Vespiquen', 474, 79.0),
 ('Pachirisu', 405, 67.5),
 ('Buizel', 330, 55.0),
 ('Floatzel', 495, 82.5),
 ('Cherubi', 275, 45.833333333333336),
 ('Cherrim', 450, 75.0),
 ('Shellos', 325, 54.166666666666664),
 ('Gastrodon', 475, 79.16666666666667),
 ('Ambipom', 482, 80.33333333333333),
 ('Drifloon', 348, 58.0),
 ('Drifblim', 498, 83.0),
 ('Buneary', 350, 58.333333333333336),
 ('Lopunny', 480, 80.0),
 ('LopunnyMega Lopunny', 580, 96.66666666666667),
 ('Mismagius', 495, 82.5),
 ('Honchkrow', 505, 84.16666666666667),
 ('Glameow', 310, 51.666666666666664),
 ('Purugly', 452, 75.33333333333333),
 ('Chingling', 285, 47.5),
 ('Stunky', 329, 54.833333333333336),
 ('Skuntank', 479, 79.83333333333333),
 ('Bronzor', 300, 50.0),
 ('Bronzong', 500, 83.33333333333333),
 ('Bonsly', 290, 48.333333333333336),
 ('Mime Jr.', 310, 51.666666666666664),
 ('Happiny', 220, 36.666666666666664),
 ('Chatot', 411, 68.5),
 ('Spiritomb', 485, 80.83333333333333),
 ('Gible', 300, 50.0),
 ('Gabite', 410, 68.33333333333333),
 ('Garchomp', 600, 100.0),
 ('GarchompMega Garchomp', 700, 116.66666666666667),
 ('Munchlax', 390, 65.0),
 ('Riolu', 285, 47.5),
 ('Lucario', 525, 87.5),
 ('LucarioMega Lucario', 625, 104.16666666666667),
 ('Hippopotas', 330, 55.0),
 ('Hippowdon', 525, 87.5),
 ('Skorupi', 330, 55.0),
 ('Drapion', 500, 83.33333333333333),
 ('Croagunk', 300, 50.0),
 ('Toxicroak', 490, 81.66666666666667),
 ('Carnivine', 454, 75.66666666666667),
 ('Finneon', 330, 55.0),
 ('Lumineon', 460, 76.66666666666667),
 ('Mantyke', 345, 57.5),
 ('Snover', 334, 55.666666666666664),
 ('Abomasnow', 494, 82.33333333333333),
 ('AbomasnowMega Abomasnow', 594, 99.0),
 ('Weavile', 510, 85.0),
 ('Magnezone', 535, 89.16666666666667),
 ('Lickilicky', 515, 85.83333333333333),
 ('Rhyperior', 535, 89.16666666666667),
 ('Tangrowth', 535, 89.16666666666667),
 ('Electivire', 540, 90.0),
 ('Magmortar', 540, 90.0),
 ('Togekiss', 545, 90.83333333333333),
 ('Yanmega', 515, 85.83333333333333),
 ('Leafeon', 525, 87.5),
 ('Glaceon', 525, 87.5),
 ('Gliscor', 510, 85.0),
 ('Mamoswine', 530, 88.33333333333333),
 ('Porygon-Z', 535, 89.16666666666667),
 ('Gallade', 518, 86.33333333333333),
 ('GalladeMega Gallade', 618, 103.0),
 ('Probopass', 525, 87.5),
 ('Dusknoir', 525, 87.5),
 ('Froslass', 480, 80.0),
 ('Rotom', 440, 73.33333333333333),
 ('RotomHeat Rotom', 520, 86.66666666666667),
 ('RotomWash Rotom', 520, 86.66666666666667),
 ('RotomFrost Rotom', 520, 86.66666666666667),
 ('RotomFan Rotom', 520, 86.66666666666667),
 ('RotomMow Rotom', 520, 86.66666666666667),
 ('Uxie', 580, 96.66666666666667),
 ('Mesprit', 580, 96.66666666666667),
 ('Azelf', 580, 96.66666666666667),
 ('Dialga', 680, 113.33333333333333),
 ('Palkia', 680, 113.33333333333333),
 ('Heatran', 600, 100.0),
 ('Regigigas', 670, 111.66666666666667),
 ('GiratinaAltered Forme', 680, 113.33333333333333),
 ('GiratinaOrigin Forme', 680, 113.33333333333333),
 ('Cresselia', 600, 100.0),
 ('Phione', 480, 80.0),
 ('Manaphy', 600, 100.0),
 ('Darkrai', 600, 100.0),
 ('ShayminLand Forme', 600, 100.0),
 ('ShayminSky Forme', 600, 100.0),
 ('Arceus', 720, 120.0),
 ('Victini', 600, 100.0),
 ('Snivy', 308, 51.333333333333336),
 ('Servine', 413, 68.83333333333333),
 ('Serperior', 528, 88.0),
 ('Tepig', 308, 51.333333333333336),
 ('Pignite', 418, 69.66666666666667),
 ('Emboar', 528, 88.0),
 ('Oshawott', 308, 51.333333333333336),
 ('Dewott', 413, 68.83333333333333),
 ('Samurott', 528, 88.0),
 ('Patrat', 255, 42.5),
 ('Watchog', 420, 70.0),
 ('Lillipup', 275, 45.833333333333336),
 ('Herdier', 370, 61.666666666666664),
 ('Stoutland', 500, 83.33333333333333),
 ('Purrloin', 281, 46.833333333333336),
 ('Liepard', 446, 74.33333333333333),
 ('Pansage', 316, 52.666666666666664),
 ('Simisage', 498, 83.0),
 ('Pansear', 316, 52.666666666666664),
 ('Simisear', 498, 83.0),

In [232]:
top_3 = sorted(poke_list_np, key=lambda x: x[1], reverse=True)[:5]
print('3 strongest Pokémon:\n{}'.format(top_3))

3 strongest Pokémon:
[('MewtwoMega Mewtwo X', 780, 130.0), ('MewtwoMega Mewtwo Y', 780, 130.0), ('RayquazaMega Rayquaza', 780, 130.0), ('KyogrePrimal Kyogre', 770, 128.33333333333334), ('GroudonPrimal Groudon', 770, 128.33333333333334)]

In this section, we'll explore how to make loop more efficient when looping is unavoidable.

In [234]:
names=['Absol','Aron','Jynx','Natu','Onix']
attacks=np.array([130,70,50,50,45])

We'd like to print out the names of each Pokemon with an attack value greater than the average of all attack values.

In [ ]:
x=[name for name in names if ]

In [235]:
names_and_attack=[*zip(names,attacks)]

In [238]:
names_and_attack

[('Absol', 130), ('Aron', 70), ('Jynx', 50), ('Natu', 50), ('Onix', 45)]

In [239]:
names_and_attack[0][1]

130

In [249]:
[name[0] for name in names_and_attack if name[1]>np.mean(attacks)]

['Absol', 'Aron']

Another way is

In [255]:
for pokemon, attack in zip(names, attacks):
    total_attack_avg=attacks.mean()
    if attack>total_attack_avg:
        print(
            "{}'s attack: {} > average: {}!"
            .format(pokemon,attack, total_attack_avg))

Absol's attack: 130 > average: 69.0!
Aron's attack: 70 > average: 69.0!

In this loop, total_attack_avg variable is being created with each iteration of the loop. If you need a certain calculation at once, just use them outside of the for loop.

In [259]:
%timeit
total_attack_avg=attacks.mean()
for pokemon, attack in zip(names, attacks):
    if attack>total_attack_avg:
        print(
            "{}'s attack: {} > average: {}!"
            .format(pokemon,attack, total_attack_avg))

Absol's attack: 130 > average: 69.0!
Aron's attack: 70 > average: 69.0!

#### Using Holistic Conversions

In [262]:
names=pok.Name.to_list()
legend_status=pok.Legendary.to_list()
generations=pok.Generation.to_list()

In [264]:
pok_data=[]
for poke_tuple in zip(names,legend_status,generations):
    poke_list=list(poke_tuple)
    pok_data.append(poke_list)
print(pok_data)

[['Bulbasaur', False, 1], ['Ivysaur', False, 1], ['Venusaur', False, 1], ['VenusaurMega Venusaur', False, 1], ['Charmander', False, 1], ['Charmeleon', False, 1], ['Charizard', False, 1], ['CharizardMega Charizard X', False, 1], ['CharizardMega Charizard Y', False, 1], ['Squirtle', False, 1], ['Wartortle', False, 1], ['Blastoise', False, 1], ['BlastoiseMega Blastoise', False, 1], ['Caterpie', False, 1], ['Metapod', False, 1], ['Butterfree', False, 1], ['Weedle', False, 1], ['Kakuna', False, 1], ['Beedrill', False, 1], ['BeedrillMega Beedrill', False, 1], ['Pidgey', False, 1], ['Pidgeotto', False, 1], ['Pidgeot', False, 1], ['PidgeotMega Pidgeot', False, 1], ['Rattata', False, 1], ['Raticate', False, 1], ['Spearow', False, 1], ['Fearow', False, 1], ['Ekans', False, 1], ['Arbok', False, 1], ['Pikachu', False, 1], ['Raichu', False, 1], ['Sandshrew', False, 1], ['Sandslash', False, 1], ['Nidoran♀', False, 1], ['Nidorina', False, 1], ['Nidoqueen', False, 1], ['Nidoran♂', False, 1], ['Nidorino', False, 1], ['Nidoking', False, 1], ['Clefairy', False, 1], ['Clefable', False, 1], ['Vulpix', False, 1], ['Ninetales', False, 1], ['Jigglypuff', False, 1], ['Wigglytuff', False, 1], ['Zubat', False, 1], ['Golbat', False, 1], ['Oddish', False, 1], ['Gloom', False, 1], ['Vileplume', False, 1], ['Paras', False, 1], ['Parasect', False, 1], ['Venonat', False, 1], ['Venomoth', False, 1], ['Diglett', False, 1], ['Dugtrio', False, 1], ['Meowth', False, 1], ['Persian', False, 1], ['Psyduck', False, 1], ['Golduck', False, 1], ['Mankey', False, 1], ['Primeape', False, 1], ['Growlithe', False, 1], ['Arcanine', False, 1], ['Poliwag', False, 1], ['Poliwhirl', False, 1], ['Poliwrath', False, 1], ['Abra', False, 1], ['Kadabra', False, 1], ['Alakazam', False, 1], ['AlakazamMega Alakazam', False, 1], ['Machop', False, 1], ['Machoke', False, 1], ['Machamp', False, 1], ['Bellsprout', False, 1], ['Weepinbell', False, 1], ['Victreebel', False, 1], ['Tentacool', False, 1], ['Tentacruel', False, 1], ['Geodude', False, 1], ['Graveler', False, 1], ['Golem', False, 1], ['Ponyta', False, 1], ['Rapidash', False, 1], ['Slowpoke', False, 1], ['Slowbro', False, 1], ['SlowbroMega Slowbro', False, 1], ['Magnemite', False, 1], ['Magneton', False, 1], ["Farfetch'd", False, 1], ['Doduo', False, 1], ['Dodrio', False, 1], ['Seel', False, 1], ['Dewgong', False, 1], ['Grimer', False, 1], ['Muk', False, 1], ['Shellder', False, 1], ['Cloyster', False, 1], ['Gastly', False, 1], ['Haunter', False, 1], ['Gengar', False, 1], ['GengarMega Gengar', False, 1], ['Onix', False, 1], ['Drowzee', False, 1], ['Hypno', False, 1], ['Krabby', False, 1], ['Kingler', False, 1], ['Voltorb', False, 1], ['Electrode', False, 1], ['Exeggcute', False, 1], ['Exeggutor', False, 1], ['Cubone', False, 1], ['Marowak', False, 1], ['Hitmonlee', False, 1], ['Hitmonchan', False, 1], ['Lickitung', False, 1], ['Koffing', False, 1], ['Weezing', False, 1], ['Rhyhorn', False, 1], ['Rhydon', False, 1], ['Chansey', False, 1], ['Tangela', False, 1], ['Kangaskhan', False, 1], ['KangaskhanMega Kangaskhan', False, 1], ['Horsea', False, 1], ['Seadra', False, 1], ['Goldeen', False, 1], ['Seaking', False, 1], ['Staryu', False, 1], ['Starmie', False, 1], ['Mr. Mime', False, 1], ['Scyther', False, 1], ['Jynx', False, 1], ['Electabuzz', False, 1], ['Magmar', False, 1], ['Pinsir', False, 1], ['PinsirMega Pinsir', False, 1], ['Tauros', False, 1], ['Magikarp', False, 1], ['Gyarados', False, 1], ['GyaradosMega Gyarados', False, 1], ['Lapras', False, 1], ['Ditto', False, 1], ['Eevee', False, 1], ['Vaporeon', False, 1], ['Jolteon', False, 1], ['Flareon', False, 1], ['Porygon', False, 1], ['Omanyte', False, 1], ['Omastar', False, 1], ['Kabuto', False, 1], ['Kabutops', False, 1], ['Aerodactyl', False, 1], ['AerodactylMega Aerodactyl', False, 1], ['Snorlax', False, 1], ['Articuno', True, 1], ['Zapdos', True, 1], ['Moltres', True, 1], ['Dratini', False, 1], ['Dragonair', False, 1], ['Dragonite', False, 1], ['Mewtwo', True, 1], ['MewtwoMega Mewtwo X', True, 1], ['MewtwoMega Mewtwo Y', True, 1], ['Mew', False, 1], ['Chikorita', False, 2], ['Bayleef', False, 2], ['Meganium', False, 2], ['Cyndaquil', False, 2], ['Quilava', False, 2], ['Typhlosion', False, 2], ['Totodile', False, 2], ['Croconaw', False, 2], ['Feraligatr', False, 2], ['Sentret', False, 2], ['Furret', False, 2], ['Hoothoot', False, 2], ['Noctowl', False, 2], ['Ledyba', False, 2], ['Ledian', False, 2], ['Spinarak', False, 2], ['Ariados', False, 2], ['Crobat', False, 2], ['Chinchou', False, 2], ['Lanturn', False, 2], ['Pichu', False, 2], ['Cleffa', False, 2], ['Igglybuff', False, 2], ['Togepi', False, 2], ['Togetic', False, 2], ['Natu', False, 2], ['Xatu', False, 2], ['Mareep', False, 2], ['Flaaffy', False, 2], ['Ampharos', False, 2], ['AmpharosMega Ampharos', False, 2], ['Bellossom', False, 2], ['Marill', False, 2], ['Azumarill', False, 2], ['Sudowoodo', False, 2], ['Politoed', False, 2], ['Hoppip', False, 2], ['Skiploom', False, 2], ['Jumpluff', False, 2], ['Aipom', False, 2], ['Sunkern', False, 2], ['Sunflora', False, 2], ['Yanma', False, 2], ['Wooper', False, 2], ['Quagsire', False, 2], ['Espeon', False, 2], ['Umbreon', False, 2], ['Murkrow', False, 2], ['Slowking', False, 2], ['Misdreavus', False, 2], ['Unown', False, 2], ['Wobbuffet', False, 2], ['Girafarig', False, 2], ['Pineco', False, 2], ['Forretress', False, 2], ['Dunsparce', False, 2], ['Gligar', False, 2], ['Steelix', False, 2], ['SteelixMega Steelix', False, 2], ['Snubbull', False, 2], ['Granbull', False, 2], ['Qwilfish', False, 2], ['Scizor', False, 2], ['ScizorMega Scizor', False, 2], ['Shuckle', False, 2], ['Heracross', False, 2], ['HeracrossMega Heracross', False, 2], ['Sneasel', False, 2], ['Teddiursa', False, 2], ['Ursaring', False, 2], ['Slugma', False, 2], ['Magcargo', False, 2], ['Swinub', False, 2], ['Piloswine', False, 2], ['Corsola', False, 2], ['Remoraid', False, 2], ['Octillery', False, 2], ['Delibird', False, 2], ['Mantine', False, 2], ['Skarmory', False, 2], ['Houndour', False, 2], ['Houndoom', False, 2], ['HoundoomMega Houndoom', False, 2], ['Kingdra', False, 2], ['Phanpy', False, 2], ['Donphan', False, 2], ['Porygon2', False, 2], ['Stantler', False, 2], ['Smeargle', False, 2], ['Tyrogue', False, 2], ['Hitmontop', False, 2], ['Smoochum', False, 2], ['Elekid', False, 2], ['Magby', False, 2], ['Miltank', False, 2], ['Blissey', False, 2], ['Raikou', True, 2], ['Entei', True, 2], ['Suicune', True, 2], ['Larvitar', False, 2], ['Pupitar', False, 2], ['Tyranitar', False, 2], ['TyranitarMega Tyranitar', False, 2], ['Lugia', True, 2], ['Ho-oh', True, 2], ['Celebi', False, 2], ['Treecko', False, 3], ['Grovyle', False, 3], ['Sceptile', False, 3], ['SceptileMega Sceptile', False, 3], ['Torchic', False, 3], ['Combusken', False, 3], ['Blaziken', False, 3], ['BlazikenMega Blaziken', False, 3], ['Mudkip', False, 3], ['Marshtomp', False, 3], ['Swampert', False, 3], ['SwampertMega Swampert', False, 3], ['Poochyena', False, 3], ['Mightyena', False, 3], ['Zigzagoon', False, 3], ['Linoone', False, 3], ['Wurmple', False, 3], ['Silcoon', False, 3], ['Beautifly', False, 3], ['Cascoon', False, 3], ['Dustox', False, 3], ['Lotad', False, 3], ['Lombre', False, 3], ['Ludicolo', False, 3], ['Seedot', False, 3], ['Nuzleaf', False, 3], ['Shiftry', False, 3], ['Taillow', False, 3], ['Swellow', False, 3], ['Wingull', False, 3], ['Pelipper', False, 3], ['Ralts', False, 3], ['Kirlia', False, 3], ['Gardevoir', False, 3], ['GardevoirMega Gardevoir', False, 3], ['Surskit', False, 3], ['Masquerain', False, 3], ['Shroomish', False, 3], ['Breloom', False, 3], ['Slakoth', False, 3], ['Vigoroth', False, 3], ['Slaking', False, 3], ['Nincada', False, 3], ['Ninjask', False, 3], ['Shedinja', False, 3], ['Whismur', False, 3], ['Loudred', False, 3], ['Exploud', False, 3], ['Makuhita', False, 3], ['Hariyama', False, 3], ['Azurill', False, 3], ['Nosepass', False, 3], ['Skitty', False, 3], ['Delcatty', False, 3], ['Sableye', False, 3], ['SableyeMega Sableye', False, 3], ['Mawile', False, 3], ['MawileMega Mawile', False, 3], ['Aron', False, 3], ['Lairon', False, 3], ['Aggron', False, 3], ['AggronMega Aggron', False, 3], ['Meditite', False, 3], ['Medicham', False, 3], ['MedichamMega Medicham', False, 3], ['Electrike', False, 3], ['Manectric', False, 3], ['ManectricMega Manectric', False, 3], ['Plusle', False, 3], ['Minun', False, 3], ['Volbeat', False, 3], ['Illumise', False, 3], ['Roselia', False, 3], ['Gulpin', False, 3], ['Swalot', False, 3], ['Carvanha', False, 3], ['Sharpedo', False, 3], ['SharpedoMega Sharpedo', False, 3], ['Wailmer', False, 3], ['Wailord', False, 3], ['Numel', False, 3], ['Camerupt', False, 3], ['CameruptMega Camerupt', False, 3], ['Torkoal', False, 3], ['Spoink', False, 3], ['Grumpig', False, 3], ['Spinda', False, 3], ['Trapinch', False, 3], ['Vibrava', False, 3], ['Flygon', False, 3], ['Cacnea', False, 3], ['Cacturne', False, 3], ['Swablu', False, 3], ['Altaria', False, 3], ['AltariaMega Altaria', False, 3], ['Zangoose', False, 3], ['Seviper', False, 3], ['Lunatone', False, 3], ['Solrock', False, 3], ['Barboach', False, 3], ['Whiscash', False, 3], ['Corphish', False, 3], ['Crawdaunt', False, 3], ['Baltoy', False, 3], ['Claydol', False, 3], ['Lileep', False, 3], ['Cradily', False, 3], ['Anorith', False, 3], ['Armaldo', False, 3], ['Feebas', False, 3], ['Milotic', False, 3], ['Castform', False, 3], ['Kecleon', False, 3], ['Shuppet', False, 3], ['Banette', False, 3], ['BanetteMega Banette', False, 3], ['Duskull', False, 3], ['Dusclops', False, 3], ['Tropius', False, 3], ['Chimecho', False, 3], ['Absol', False, 3], ['AbsolMega Absol', False, 3], ['Wynaut', False, 3], ['Snorunt', False, 3], ['Glalie', False, 3], ['GlalieMega Glalie', False, 3], ['Spheal', False, 3], ['Sealeo', False, 3], ['Walrein', False, 3], ['Clamperl', False, 3], ['Huntail', False, 3], ['Gorebyss', False, 3], ['Relicanth', False, 3], ['Luvdisc', False, 3], ['Bagon', False, 3], ['Shelgon', False, 3], ['Salamence', False, 3], ['SalamenceMega Salamence', False, 3], ['Beldum', False, 3], ['Metang', False, 3], ['Metagross', False, 3], ['MetagrossMega Metagross', False, 3], ['Regirock', True, 3], ['Regice', True, 3], ['Registeel', True, 3], ['Latias', True, 3], ['LatiasMega Latias', True, 3], ['Latios', True, 3], ['LatiosMega Latios', True, 3], ['Kyogre', True, 3], ['KyogrePrimal Kyogre', True, 3], ['Groudon', True, 3], ['GroudonPrimal Groudon', True, 3], ['Rayquaza', True, 3], ['RayquazaMega Rayquaza', True, 3], ['Jirachi', True, 3], ['DeoxysNormal Forme', True, 3], ['DeoxysAttack Forme', True, 3], ['DeoxysDefense Forme', True, 3], ['DeoxysSpeed Forme', True, 3], ['Turtwig', False, 4], ['Grotle', False, 4], ['Torterra', False, 4], ['Chimchar', False, 4], ['Monferno', False, 4], ['Infernape', False, 4], ['Piplup', False, 4], ['Prinplup', False, 4], ['Empoleon', False, 4], ['Starly', False, 4], ['Staravia', False, 4], ['Staraptor', False, 4], ['Bidoof', False, 4], ['Bibarel', False, 4], ['Kricketot', False, 4], ['Kricketune', False, 4], ['Shinx', False, 4], ['Luxio', False, 4], ['Luxray', False, 4], ['Budew', False, 4], ['Roserade', False, 4], ['Cranidos', False, 4], ['Rampardos', False, 4], ['Shieldon', False, 4], ['Bastiodon', False, 4], ['Burmy', False, 4], ['WormadamPlant Cloak', False, 4], ['WormadamSandy Cloak', False, 4], ['WormadamTrash Cloak', False, 4], ['Mothim', False, 4], ['Combee', False, 4], ['Vespiquen', False, 4], ['Pachirisu', False, 4], ['Buizel', False, 4], ['Floatzel', False, 4], ['Cherubi', False, 4], ['Cherrim', False, 4], ['Shellos', False, 4], ['Gastrodon', False, 4], ['Ambipom', False, 4], ['Drifloon', False, 4], ['Drifblim', False, 4], ['Buneary', False, 4], ['Lopunny', False, 4], ['LopunnyMega Lopunny', False, 4], ['Mismagius', False, 4], ['Honchkrow', False, 4], ['Glameow', False, 4], ['Purugly', False, 4], ['Chingling', False, 4], ['Stunky', False, 4], ['Skuntank', False, 4], ['Bronzor', False, 4], ['Bronzong', False, 4], ['Bonsly', False, 4], ['Mime Jr.', False, 4], ['Happiny', False, 4], ['Chatot', False, 4], ['Spiritomb', False, 4], ['Gible', False, 4], ['Gabite', False, 4], ['Garchomp', False, 4], ['GarchompMega Garchomp', False, 4], ['Munchlax', False, 4], ['Riolu', False, 4], ['Lucario', False, 4], ['LucarioMega Lucario', False, 4], ['Hippopotas', False, 4], ['Hippowdon', False, 4], ['Skorupi', False, 4], ['Drapion', False, 4], ['Croagunk', False, 4], ['Toxicroak', False, 4], ['Carnivine', False, 4], ['Finneon', False, 4], ['Lumineon', False, 4], ['Mantyke', False, 4], ['Snover', False, 4], ['Abomasnow', False, 4], ['AbomasnowMega Abomasnow', False, 4], ['Weavile', False, 4], ['Magnezone', False, 4], ['Lickilicky', False, 4], ['Rhyperior', False, 4], ['Tangrowth', False, 4], ['Electivire', False, 4], ['Magmortar', False, 4], ['Togekiss', False, 4], ['Yanmega', False, 4], ['Leafeon', False, 4], ['Glaceon', False, 4], ['Gliscor', False, 4], ['Mamoswine', False, 4], ['Porygon-Z', False, 4], ['Gallade', False, 4], ['GalladeMega Gallade', False, 4], ['Probopass', False, 4], ['Dusknoir', False, 4], ['Froslass', False, 4], ['Rotom', False, 4], ['RotomHeat Rotom', False, 4], ['RotomWash Rotom', False, 4], ['RotomFrost Rotom', False, 4], ['RotomFan Rotom', False, 4], ['RotomMow Rotom', False, 4], ['Uxie', True, 4], ['Mesprit', True, 4], ['Azelf', True, 4], ['Dialga', True, 4], ['Palkia', True, 4], ['Heatran', True, 4], ['Regigigas', True, 4], ['GiratinaAltered Forme', True, 4], ['GiratinaOrigin Forme', True, 4], ['Cresselia', False, 4], ['Phione', False, 4], ['Manaphy', False, 4], ['Darkrai', True, 4], ['ShayminLand Forme', True, 4], ['ShayminSky Forme', True, 4], ['Arceus', True, 4], ['Victini', True, 5], ['Snivy', False, 5], ['Servine', False, 5], ['Serperior', False, 5], ['Tepig', False, 5], ['Pignite', False, 5], ['Emboar', False, 5], ['Oshawott', False, 5], ['Dewott', False, 5], ['Samurott', False, 5], ['Patrat', False, 5], ['Watchog', False, 5], ['Lillipup', False, 5], ['Herdier', False, 5], ['Stoutland', False, 5], ['Purrloin', False, 5], ['Liepard', False, 5], ['Pansage', False, 5], ['Simisage', False, 5], ['Pansear', False, 5], ['Simisear', False, 5], ['Panpour', False, 5], ['Simipour', False, 5], ['Munna', False, 5], ['Musharna', False, 5], ['Pidove', False, 5], ['Tranquill', False, 5], ['Unfezant', False, 5], ['Blitzle', False, 5], ['Zebstrika', False, 5], ['Roggenrola', False, 5], ['Boldore', False, 5], ['Gigalith', False, 5], ['Woobat', False, 5], ['Swoobat', False, 5], ['Drilbur', False, 5], ['Excadrill', False, 5], ['Audino', False, 5], ['AudinoMega Audino', False, 5], ['Timburr', False, 5], ['Gurdurr', False, 5], ['Conkeldurr', False, 5], ['Tympole', False, 5], ['Palpitoad', False, 5], ['Seismitoad', False, 5], ['Throh', False, 5], ['Sawk', False, 5], ['Sewaddle', False, 5], ['Swadloon', False, 5], ['Leavanny', False, 5], ['Venipede', False, 5], ['Whirlipede', False, 5], ['Scolipede', False, 5], ['Cottonee', False, 5], ['Whimsicott', False, 5], ['Petilil', False, 5], ['Lilligant', False, 5], ['Basculin', False, 5], ['Sandile', False, 5], ['Krokorok', False, 5], ['Krookodile', False, 5], ['Darumaka', False, 5], ['DarmanitanStandard Mode', False, 5], ['DarmanitanZen Mode', False, 5], ['Maractus', False, 5], ['Dwebble', False, 5], ['Crustle', False, 5], ['Scraggy', False, 5], ['Scrafty', False, 5], ['Sigilyph', False, 5], ['Yamask', False, 5], ['Cofagrigus', False, 5], ['Tirtouga', False, 5], ['Carracosta', False, 5], ['Archen', False, 5], ['Archeops', False, 5], ['Trubbish', False, 5], ['Garbodor', False, 5], ['Zorua', False, 5], ['Zoroark', False, 5], ['Minccino', False, 5], ['Cinccino', False, 5], ['Gothita', False, 5], ['Gothorita', False, 5], ['Gothitelle', False, 5], ['Solosis', False, 5], ['Duosion', False, 5], ['Reuniclus', False, 5], ['Ducklett', False, 5], ['Swanna', False, 5], ['Vanillite', False, 5], ['Vanillish', False, 5], ['Vanilluxe', False, 5], ['Deerling', False, 5], ['Sawsbuck', False, 5], ['Emolga', False, 5], ['Karrablast', False, 5], ['Escavalier', False, 5], ['Foongus', False, 5], ['Amoonguss', False, 5], ['Frillish', False, 5], ['Jellicent', False, 5], ['Alomomola', False, 5], ['Joltik', False, 5], ['Galvantula', False, 5], ['Ferroseed', False, 5], ['Ferrothorn', False, 5], ['Klink', False, 5], ['Klang', False, 5], ['Klinklang', False, 5], ['Tynamo', False, 5], ['Eelektrik', False, 5], ['Eelektross', False, 5], ['Elgyem', False, 5], ['Beheeyem', False, 5], ['Litwick', False, 5], ['Lampent', False, 5], ['Chandelure', False, 5], ['Axew', False, 5], ['Fraxure', False, 5], ['Haxorus', False, 5], ['Cubchoo', False, 5], ['Beartic', False, 5], ['Cryogonal', False, 5], ['Shelmet', False, 5], ['Accelgor', False, 5], ['Stunfisk', False, 5], ['Mienfoo', False, 5], ['Mienshao', False, 5], ['Druddigon', False, 5], ['Golett', False, 5], ['Golurk', False, 5], ['Pawniard', False, 5], ['Bisharp', False, 5], ['Bouffalant', False, 5], ['Rufflet', False, 5], ['Braviary', False, 5], ['Vullaby', False, 5], ['Mandibuzz', False, 5], ['Heatmor', False, 5], ['Durant', False, 5], ['Deino', False, 5], ['Zweilous', False, 5], ['Hydreigon', False, 5], ['Larvesta', False, 5], ['Volcarona', False, 5], ['Cobalion', True, 5], ['Terrakion', True, 5], ['Virizion', True, 5], ['TornadusIncarnate Forme', True, 5], ['TornadusTherian Forme', True, 5], ['ThundurusIncarnate Forme', True, 5], ['ThundurusTherian Forme', True, 5], ['Reshiram', True, 5], ['Zekrom', True, 5], ['LandorusIncarnate Forme', True, 5], ['LandorusTherian Forme', True, 5], ['Kyurem', True, 5], ['KyuremBlack Kyurem', True, 5], ['KyuremWhite Kyurem', True, 5], ['KeldeoOrdinary Forme', False, 5], ['KeldeoResolute Forme', False, 5], ['MeloettaAria Forme', False, 5], ['MeloettaPirouette Forme', False, 5], ['Genesect', False, 5], ['Chespin', False, 6], ['Quilladin', False, 6], ['Chesnaught', False, 6], ['Fennekin', False, 6], ['Braixen', False, 6], ['Delphox', False, 6], ['Froakie', False, 6], ['Frogadier', False, 6], ['Greninja', False, 6], ['Bunnelby', False, 6], ['Diggersby', False, 6], ['Fletchling', False, 6], ['Fletchinder', False, 6], ['Talonflame', False, 6], ['Scatterbug', False, 6], ['Spewpa', False, 6], ['Vivillon', False, 6], ['Litleo', False, 6], ['Pyroar', False, 6], ['Flabébé', False, 6], ['Floette', False, 6], ['Florges', False, 6], ['Skiddo', False, 6], ['Gogoat', False, 6], ['Pancham', False, 6], ['Pangoro', False, 6], ['Furfrou', False, 6], ['Espurr', False, 6], ['MeowsticMale', False, 6], ['MeowsticFemale', False, 6], ['Honedge', False, 6], ['Doublade', False, 6], ['AegislashBlade Forme', False, 6], ['AegislashShield Forme', False, 6], ['Spritzee', False, 6], ['Aromatisse', False, 6], ['Swirlix', False, 6], ['Slurpuff', False, 6], ['Inkay', False, 6], ['Malamar', False, 6], ['Binacle', False, 6], ['Barbaracle', False, 6], ['Skrelp', False, 6], ['Dragalge', False, 6], ['Clauncher', False, 6], ['Clawitzer', False, 6], ['Helioptile', False, 6], ['Heliolisk', False, 6], ['Tyrunt', False, 6], ['Tyrantrum', False, 6], ['Amaura', False, 6], ['Aurorus', False, 6], ['Sylveon', False, 6], ['Hawlucha', False, 6], ['Dedenne', False, 6], ['Carbink', False, 6], ['Goomy', False, 6], ['Sliggoo', False, 6], ['Goodra', False, 6], ['Klefki', False, 6], ['Phantump', False, 6], ['Trevenant', False, 6], ['PumpkabooAverage Size', False, 6], ['PumpkabooSmall Size', False, 6], ['PumpkabooLarge Size', False, 6], ['PumpkabooSuper Size', False, 6], ['GourgeistAverage Size', False, 6], ['GourgeistSmall Size', False, 6], ['GourgeistLarge Size', False, 6], ['GourgeistSuper Size', False, 6], ['Bergmite', False, 6], ['Avalugg', False, 6], ['Noibat', False, 6], ['Noivern', False, 6], ['Xerneas', True, 6], ['Yveltal', True, 6], ['Zygarde50% Forme', True, 6], ['Diancie', True, 6], ['DiancieMega Diancie', True, 6], ['HoopaHoopa Confined', True, 6], ['HoopaHoopa Unbound', True, 6], ['Volcanion', True, 6]]

Instead, we should collect all of our poke_tuples together, and use the map function to convert each tuple to a list.

In [265]:
poke_data_tuples=[]
for poke_tuple in zip(names,legend_status,generations):
    poke_data_tuples.append(poke_tuple)
poke_data=[*map(list,poke_data_tuples)]
print(poke_data)

[['Bulbasaur', False, 1], ['Ivysaur', False, 1], ['Venusaur', False, 1], ['VenusaurMega Venusaur', False, 1], ['Charmander', False, 1], ['Charmeleon', False, 1], ['Charizard', False, 1], ['CharizardMega Charizard X', False, 1], ['CharizardMega Charizard Y', False, 1], ['Squirtle', False, 1], ['Wartortle', False, 1], ['Blastoise', False, 1], ['BlastoiseMega Blastoise', False, 1], ['Caterpie', False, 1], ['Metapod', False, 1], ['Butterfree', False, 1], ['Weedle', False, 1], ['Kakuna', False, 1], ['Beedrill', False, 1], ['BeedrillMega Beedrill', False, 1], ['Pidgey', False, 1], ['Pidgeotto', False, 1], ['Pidgeot', False, 1], ['PidgeotMega Pidgeot', False, 1], ['Rattata', False, 1], ['Raticate', False, 1], ['Spearow', False, 1], ['Fearow', False, 1], ['Ekans', False, 1], ['Arbok', False, 1], ['Pikachu', False, 1], ['Raichu', False, 1], ['Sandshrew', False, 1], ['Sandslash', False, 1], ['Nidoran♀', False, 1], ['Nidorina', False, 1], ['Nidoqueen', False, 1], ['Nidoran♂', False, 1], ['Nidorino', False, 1], ['Nidoking', False, 1], ['Clefairy', False, 1], ['Clefable', False, 1], ['Vulpix', False, 1], ['Ninetales', False, 1], ['Jigglypuff', False, 1], ['Wigglytuff', False, 1], ['Zubat', False, 1], ['Golbat', False, 1], ['Oddish', False, 1], ['Gloom', False, 1], ['Vileplume', False, 1], ['Paras', False, 1], ['Parasect', False, 1], ['Venonat', False, 1], ['Venomoth', False, 1], ['Diglett', False, 1], ['Dugtrio', False, 1], ['Meowth', False, 1], ['Persian', False, 1], ['Psyduck', False, 1], ['Golduck', False, 1], ['Mankey', False, 1], ['Primeape', False, 1], ['Growlithe', False, 1], ['Arcanine', False, 1], ['Poliwag', False, 1], ['Poliwhirl', False, 1], ['Poliwrath', False, 1], ['Abra', False, 1], ['Kadabra', False, 1], ['Alakazam', False, 1], ['AlakazamMega Alakazam', False, 1], ['Machop', False, 1], ['Machoke', False, 1], ['Machamp', False, 1], ['Bellsprout', False, 1], ['Weepinbell', False, 1], ['Victreebel', False, 1], ['Tentacool', False, 1], ['Tentacruel', False, 1], ['Geodude', False, 1], ['Graveler', False, 1], ['Golem', False, 1], ['Ponyta', False, 1], ['Rapidash', False, 1], ['Slowpoke', False, 1], ['Slowbro', False, 1], ['SlowbroMega Slowbro', False, 1], ['Magnemite', False, 1], ['Magneton', False, 1], ["Farfetch'd", False, 1], ['Doduo', False, 1], ['Dodrio', False, 1], ['Seel', False, 1], ['Dewgong', False, 1], ['Grimer', False, 1], ['Muk', False, 1], ['Shellder', False, 1], ['Cloyster', False, 1], ['Gastly', False, 1], ['Haunter', False, 1], ['Gengar', False, 1], ['GengarMega Gengar', False, 1], ['Onix', False, 1], ['Drowzee', False, 1], ['Hypno', False, 1], ['Krabby', False, 1], ['Kingler', False, 1], ['Voltorb', False, 1], ['Electrode', False, 1], ['Exeggcute', False, 1], ['Exeggutor', False, 1], ['Cubone', False, 1], ['Marowak', False, 1], ['Hitmonlee', False, 1], ['Hitmonchan', False, 1], ['Lickitung', False, 1], ['Koffing', False, 1], ['Weezing', False, 1], ['Rhyhorn', False, 1], ['Rhydon', False, 1], ['Chansey', False, 1], ['Tangela', False, 1], ['Kangaskhan', False, 1], ['KangaskhanMega Kangaskhan', False, 1], ['Horsea', False, 1], ['Seadra', False, 1], ['Goldeen', False, 1], ['Seaking', False, 1], ['Staryu', False, 1], ['Starmie', False, 1], ['Mr. Mime', False, 1], ['Scyther', False, 1], ['Jynx', False, 1], ['Electabuzz', False, 1], ['Magmar', False, 1], ['Pinsir', False, 1], ['PinsirMega Pinsir', False, 1], ['Tauros', False, 1], ['Magikarp', False, 1], ['Gyarados', False, 1], ['GyaradosMega Gyarados', False, 1], ['Lapras', False, 1], ['Ditto', False, 1], ['Eevee', False, 1], ['Vaporeon', False, 1], ['Jolteon', False, 1], ['Flareon', False, 1], ['Porygon', False, 1], ['Omanyte', False, 1], ['Omastar', False, 1], ['Kabuto', False, 1], ['Kabutops', False, 1], ['Aerodactyl', False, 1], ['AerodactylMega Aerodactyl', False, 1], ['Snorlax', False, 1], ['Articuno', True, 1], ['Zapdos', True, 1], ['Moltres', True, 1], ['Dratini', False, 1], ['Dragonair', False, 1], ['Dragonite', False, 1], ['Mewtwo', True, 1], ['MewtwoMega Mewtwo X', True, 1], ['MewtwoMega Mewtwo Y', True, 1], ['Mew', False, 1], ['Chikorita', False, 2], ['Bayleef', False, 2], ['Meganium', False, 2], ['Cyndaquil', False, 2], ['Quilava', False, 2], ['Typhlosion', False, 2], ['Totodile', False, 2], ['Croconaw', False, 2], ['Feraligatr', False, 2], ['Sentret', False, 2], ['Furret', False, 2], ['Hoothoot', False, 2], ['Noctowl', False, 2], ['Ledyba', False, 2], ['Ledian', False, 2], ['Spinarak', False, 2], ['Ariados', False, 2], ['Crobat', False, 2], ['Chinchou', False, 2], ['Lanturn', False, 2], ['Pichu', False, 2], ['Cleffa', False, 2], ['Igglybuff', False, 2], ['Togepi', False, 2], ['Togetic', False, 2], ['Natu', False, 2], ['Xatu', False, 2], ['Mareep', False, 2], ['Flaaffy', False, 2], ['Ampharos', False, 2], ['AmpharosMega Ampharos', False, 2], ['Bellossom', False, 2], ['Marill', False, 2], ['Azumarill', False, 2], ['Sudowoodo', False, 2], ['Politoed', False, 2], ['Hoppip', False, 2], ['Skiploom', False, 2], ['Jumpluff', False, 2], ['Aipom', False, 2], ['Sunkern', False, 2], ['Sunflora', False, 2], ['Yanma', False, 2], ['Wooper', False, 2], ['Quagsire', False, 2], ['Espeon', False, 2], ['Umbreon', False, 2], ['Murkrow', False, 2], ['Slowking', False, 2], ['Misdreavus', False, 2], ['Unown', False, 2], ['Wobbuffet', False, 2], ['Girafarig', False, 2], ['Pineco', False, 2], ['Forretress', False, 2], ['Dunsparce', False, 2], ['Gligar', False, 2], ['Steelix', False, 2], ['SteelixMega Steelix', False, 2], ['Snubbull', False, 2], ['Granbull', False, 2], ['Qwilfish', False, 2], ['Scizor', False, 2], ['ScizorMega Scizor', False, 2], ['Shuckle', False, 2], ['Heracross', False, 2], ['HeracrossMega Heracross', False, 2], ['Sneasel', False, 2], ['Teddiursa', False, 2], ['Ursaring', False, 2], ['Slugma', False, 2], ['Magcargo', False, 2], ['Swinub', False, 2], ['Piloswine', False, 2], ['Corsola', False, 2], ['Remoraid', False, 2], ['Octillery', False, 2], ['Delibird', False, 2], ['Mantine', False, 2], ['Skarmory', False, 2], ['Houndour', False, 2], ['Houndoom', False, 2], ['HoundoomMega Houndoom', False, 2], ['Kingdra', False, 2], ['Phanpy', False, 2], ['Donphan', False, 2], ['Porygon2', False, 2], ['Stantler', False, 2], ['Smeargle', False, 2], ['Tyrogue', False, 2], ['Hitmontop', False, 2], ['Smoochum', False, 2], ['Elekid', False, 2], ['Magby', False, 2], ['Miltank', False, 2], ['Blissey', False, 2], ['Raikou', True, 2], ['Entei', True, 2], ['Suicune', True, 2], ['Larvitar', False, 2], ['Pupitar', False, 2], ['Tyranitar', False, 2], ['TyranitarMega Tyranitar', False, 2], ['Lugia', True, 2], ['Ho-oh', True, 2], ['Celebi', False, 2], ['Treecko', False, 3], ['Grovyle', False, 3], ['Sceptile', False, 3], ['SceptileMega Sceptile', False, 3], ['Torchic', False, 3], ['Combusken', False, 3], ['Blaziken', False, 3], ['BlazikenMega Blaziken', False, 3], ['Mudkip', False, 3], ['Marshtomp', False, 3], ['Swampert', False, 3], ['SwampertMega Swampert', False, 3], ['Poochyena', False, 3], ['Mightyena', False, 3], ['Zigzagoon', False, 3], ['Linoone', False, 3], ['Wurmple', False, 3], ['Silcoon', False, 3], ['Beautifly', False, 3], ['Cascoon', False, 3], ['Dustox', False, 3], ['Lotad', False, 3], ['Lombre', False, 3], ['Ludicolo', False, 3], ['Seedot', False, 3], ['Nuzleaf', False, 3], ['Shiftry', False, 3], ['Taillow', False, 3], ['Swellow', False, 3], ['Wingull', False, 3], ['Pelipper', False, 3], ['Ralts', False, 3], ['Kirlia', False, 3], ['Gardevoir', False, 3], ['GardevoirMega Gardevoir', False, 3], ['Surskit', False, 3], ['Masquerain', False, 3], ['Shroomish', False, 3], ['Breloom', False, 3], ['Slakoth', False, 3], ['Vigoroth', False, 3], ['Slaking', False, 3], ['Nincada', False, 3], ['Ninjask', False, 3], ['Shedinja', False, 3], ['Whismur', False, 3], ['Loudred', False, 3], ['Exploud', False, 3], ['Makuhita', False, 3], ['Hariyama', False, 3], ['Azurill', False, 3], ['Nosepass', False, 3], ['Skitty', False, 3], ['Delcatty', False, 3], ['Sableye', False, 3], ['SableyeMega Sableye', False, 3], ['Mawile', False, 3], ['MawileMega Mawile', False, 3], ['Aron', False, 3], ['Lairon', False, 3], ['Aggron', False, 3], ['AggronMega Aggron', False, 3], ['Meditite', False, 3], ['Medicham', False, 3], ['MedichamMega Medicham', False, 3], ['Electrike', False, 3], ['Manectric', False, 3], ['ManectricMega Manectric', False, 3], ['Plusle', False, 3], ['Minun', False, 3], ['Volbeat', False, 3], ['Illumise', False, 3], ['Roselia', False, 3], ['Gulpin', False, 3], ['Swalot', False, 3], ['Carvanha', False, 3], ['Sharpedo', False, 3], ['SharpedoMega Sharpedo', False, 3], ['Wailmer', False, 3], ['Wailord', False, 3], ['Numel', False, 3], ['Camerupt', False, 3], ['CameruptMega Camerupt', False, 3], ['Torkoal', False, 3], ['Spoink', False, 3], ['Grumpig', False, 3], ['Spinda', False, 3], ['Trapinch', False, 3], ['Vibrava', False, 3], ['Flygon', False, 3], ['Cacnea', False, 3], ['Cacturne', False, 3], ['Swablu', False, 3], ['Altaria', False, 3], ['AltariaMega Altaria', False, 3], ['Zangoose', False, 3], ['Seviper', False, 3], ['Lunatone', False, 3], ['Solrock', False, 3], ['Barboach', False, 3], ['Whiscash', False, 3], ['Corphish', False, 3], ['Crawdaunt', False, 3], ['Baltoy', False, 3], ['Claydol', False, 3], ['Lileep', False, 3], ['Cradily', False, 3], ['Anorith', False, 3], ['Armaldo', False, 3], ['Feebas', False, 3], ['Milotic', False, 3], ['Castform', False, 3], ['Kecleon', False, 3], ['Shuppet', False, 3], ['Banette', False, 3], ['BanetteMega Banette', False, 3], ['Duskull', False, 3], ['Dusclops', False, 3], ['Tropius', False, 3], ['Chimecho', False, 3], ['Absol', False, 3], ['AbsolMega Absol', False, 3], ['Wynaut', False, 3], ['Snorunt', False, 3], ['Glalie', False, 3], ['GlalieMega Glalie', False, 3], ['Spheal', False, 3], ['Sealeo', False, 3], ['Walrein', False, 3], ['Clamperl', False, 3], ['Huntail', False, 3], ['Gorebyss', False, 3], ['Relicanth', False, 3], ['Luvdisc', False, 3], ['Bagon', False, 3], ['Shelgon', False, 3], ['Salamence', False, 3], ['SalamenceMega Salamence', False, 3], ['Beldum', False, 3], ['Metang', False, 3], ['Metagross', False, 3], ['MetagrossMega Metagross', False, 3], ['Regirock', True, 3], ['Regice', True, 3], ['Registeel', True, 3], ['Latias', True, 3], ['LatiasMega Latias', True, 3], ['Latios', True, 3], ['LatiosMega Latios', True, 3], ['Kyogre', True, 3], ['KyogrePrimal Kyogre', True, 3], ['Groudon', True, 3], ['GroudonPrimal Groudon', True, 3], ['Rayquaza', True, 3], ['RayquazaMega Rayquaza', True, 3], ['Jirachi', True, 3], ['DeoxysNormal Forme', True, 3], ['DeoxysAttack Forme', True, 3], ['DeoxysDefense Forme', True, 3], ['DeoxysSpeed Forme', True, 3], ['Turtwig', False, 4], ['Grotle', False, 4], ['Torterra', False, 4], ['Chimchar', False, 4], ['Monferno', False, 4], ['Infernape', False, 4], ['Piplup', False, 4], ['Prinplup', False, 4], ['Empoleon', False, 4], ['Starly', False, 4], ['Staravia', False, 4], ['Staraptor', False, 4], ['Bidoof', False, 4], ['Bibarel', False, 4], ['Kricketot', False, 4], ['Kricketune', False, 4], ['Shinx', False, 4], ['Luxio', False, 4], ['Luxray', False, 4], ['Budew', False, 4], ['Roserade', False, 4], ['Cranidos', False, 4], ['Rampardos', False, 4], ['Shieldon', False, 4], ['Bastiodon', False, 4], ['Burmy', False, 4], ['WormadamPlant Cloak', False, 4], ['WormadamSandy Cloak', False, 4], ['WormadamTrash Cloak', False, 4], ['Mothim', False, 4], ['Combee', False, 4], ['Vespiquen', False, 4], ['Pachirisu', False, 4], ['Buizel', False, 4], ['Floatzel', False, 4], ['Cherubi', False, 4], ['Cherrim', False, 4], ['Shellos', False, 4], ['Gastrodon', False, 4], ['Ambipom', False, 4], ['Drifloon', False, 4], ['Drifblim', False, 4], ['Buneary', False, 4], ['Lopunny', False, 4], ['LopunnyMega Lopunny', False, 4], ['Mismagius', False, 4], ['Honchkrow', False, 4], ['Glameow', False, 4], ['Purugly', False, 4], ['Chingling', False, 4], ['Stunky', False, 4], ['Skuntank', False, 4], ['Bronzor', False, 4], ['Bronzong', False, 4], ['Bonsly', False, 4], ['Mime Jr.', False, 4], ['Happiny', False, 4], ['Chatot', False, 4], ['Spiritomb', False, 4], ['Gible', False, 4], ['Gabite', False, 4], ['Garchomp', False, 4], ['GarchompMega Garchomp', False, 4], ['Munchlax', False, 4], ['Riolu', False, 4], ['Lucario', False, 4], ['LucarioMega Lucario', False, 4], ['Hippopotas', False, 4], ['Hippowdon', False, 4], ['Skorupi', False, 4], ['Drapion', False, 4], ['Croagunk', False, 4], ['Toxicroak', False, 4], ['Carnivine', False, 4], ['Finneon', False, 4], ['Lumineon', False, 4], ['Mantyke', False, 4], ['Snover', False, 4], ['Abomasnow', False, 4], ['AbomasnowMega Abomasnow', False, 4], ['Weavile', False, 4], ['Magnezone', False, 4], ['Lickilicky', False, 4], ['Rhyperior', False, 4], ['Tangrowth', False, 4], ['Electivire', False, 4], ['Magmortar', False, 4], ['Togekiss', False, 4], ['Yanmega', False, 4], ['Leafeon', False, 4], ['Glaceon', False, 4], ['Gliscor', False, 4], ['Mamoswine', False, 4], ['Porygon-Z', False, 4], ['Gallade', False, 4], ['GalladeMega Gallade', False, 4], ['Probopass', False, 4], ['Dusknoir', False, 4], ['Froslass', False, 4], ['Rotom', False, 4], ['RotomHeat Rotom', False, 4], ['RotomWash Rotom', False, 4], ['RotomFrost Rotom', False, 4], ['RotomFan Rotom', False, 4], ['RotomMow Rotom', False, 4], ['Uxie', True, 4], ['Mesprit', True, 4], ['Azelf', True, 4], ['Dialga', True, 4], ['Palkia', True, 4], ['Heatran', True, 4], ['Regigigas', True, 4], ['GiratinaAltered Forme', True, 4], ['GiratinaOrigin Forme', True, 4], ['Cresselia', False, 4], ['Phione', False, 4], ['Manaphy', False, 4], ['Darkrai', True, 4], ['ShayminLand Forme', True, 4], ['ShayminSky Forme', True, 4], ['Arceus', True, 4], ['Victini', True, 5], ['Snivy', False, 5], ['Servine', False, 5], ['Serperior', False, 5], ['Tepig', False, 5], ['Pignite', False, 5], ['Emboar', False, 5], ['Oshawott', False, 5], ['Dewott', False, 5], ['Samurott', False, 5], ['Patrat', False, 5], ['Watchog', False, 5], ['Lillipup', False, 5], ['Herdier', False, 5], ['Stoutland', False, 5], ['Purrloin', False, 5], ['Liepard', False, 5], ['Pansage', False, 5], ['Simisage', False, 5], ['Pansear', False, 5], ['Simisear', False, 5], ['Panpour', False, 5], ['Simipour', False, 5], ['Munna', False, 5], ['Musharna', False, 5], ['Pidove', False, 5], ['Tranquill', False, 5], ['Unfezant', False, 5], ['Blitzle', False, 5], ['Zebstrika', False, 5], ['Roggenrola', False, 5], ['Boldore', False, 5], ['Gigalith', False, 5], ['Woobat', False, 5], ['Swoobat', False, 5], ['Drilbur', False, 5], ['Excadrill', False, 5], ['Audino', False, 5], ['AudinoMega Audino', False, 5], ['Timburr', False, 5], ['Gurdurr', False, 5], ['Conkeldurr', False, 5], ['Tympole', False, 5], ['Palpitoad', False, 5], ['Seismitoad', False, 5], ['Throh', False, 5], ['Sawk', False, 5], ['Sewaddle', False, 5], ['Swadloon', False, 5], ['Leavanny', False, 5], ['Venipede', False, 5], ['Whirlipede', False, 5], ['Scolipede', False, 5], ['Cottonee', False, 5], ['Whimsicott', False, 5], ['Petilil', False, 5], ['Lilligant', False, 5], ['Basculin', False, 5], ['Sandile', False, 5], ['Krokorok', False, 5], ['Krookodile', False, 5], ['Darumaka', False, 5], ['DarmanitanStandard Mode', False, 5], ['DarmanitanZen Mode', False, 5], ['Maractus', False, 5], ['Dwebble', False, 5], ['Crustle', False, 5], ['Scraggy', False, 5], ['Scrafty', False, 5], ['Sigilyph', False, 5], ['Yamask', False, 5], ['Cofagrigus', False, 5], ['Tirtouga', False, 5], ['Carracosta', False, 5], ['Archen', False, 5], ['Archeops', False, 5], ['Trubbish', False, 5], ['Garbodor', False, 5], ['Zorua', False, 5], ['Zoroark', False, 5], ['Minccino', False, 5], ['Cinccino', False, 5], ['Gothita', False, 5], ['Gothorita', False, 5], ['Gothitelle', False, 5], ['Solosis', False, 5], ['Duosion', False, 5], ['Reuniclus', False, 5], ['Ducklett', False, 5], ['Swanna', False, 5], ['Vanillite', False, 5], ['Vanillish', False, 5], ['Vanilluxe', False, 5], ['Deerling', False, 5], ['Sawsbuck', False, 5], ['Emolga', False, 5], ['Karrablast', False, 5], ['Escavalier', False, 5], ['Foongus', False, 5], ['Amoonguss', False, 5], ['Frillish', False, 5], ['Jellicent', False, 5], ['Alomomola', False, 5], ['Joltik', False, 5], ['Galvantula', False, 5], ['Ferroseed', False, 5], ['Ferrothorn', False, 5], ['Klink', False, 5], ['Klang', False, 5], ['Klinklang', False, 5], ['Tynamo', False, 5], ['Eelektrik', False, 5], ['Eelektross', False, 5], ['Elgyem', False, 5], ['Beheeyem', False, 5], ['Litwick', False, 5], ['Lampent', False, 5], ['Chandelure', False, 5], ['Axew', False, 5], ['Fraxure', False, 5], ['Haxorus', False, 5], ['Cubchoo', False, 5], ['Beartic', False, 5], ['Cryogonal', False, 5], ['Shelmet', False, 5], ['Accelgor', False, 5], ['Stunfisk', False, 5], ['Mienfoo', False, 5], ['Mienshao', False, 5], ['Druddigon', False, 5], ['Golett', False, 5], ['Golurk', False, 5], ['Pawniard', False, 5], ['Bisharp', False, 5], ['Bouffalant', False, 5], ['Rufflet', False, 5], ['Braviary', False, 5], ['Vullaby', False, 5], ['Mandibuzz', False, 5], ['Heatmor', False, 5], ['Durant', False, 5], ['Deino', False, 5], ['Zweilous', False, 5], ['Hydreigon', False, 5], ['Larvesta', False, 5], ['Volcarona', False, 5], ['Cobalion', True, 5], ['Terrakion', True, 5], ['Virizion', True, 5], ['TornadusIncarnate Forme', True, 5], ['TornadusTherian Forme', True, 5], ['ThundurusIncarnate Forme', True, 5], ['ThundurusTherian Forme', True, 5], ['Reshiram', True, 5], ['Zekrom', True, 5], ['LandorusIncarnate Forme', True, 5], ['LandorusTherian Forme', True, 5], ['Kyurem', True, 5], ['KyuremBlack Kyurem', True, 5], ['KyuremWhite Kyurem', True, 5], ['KeldeoOrdinary Forme', False, 5], ['KeldeoResolute Forme', False, 5], ['MeloettaAria Forme', False, 5], ['MeloettaPirouette Forme', False, 5], ['Genesect', False, 5], ['Chespin', False, 6], ['Quilladin', False, 6], ['Chesnaught', False, 6], ['Fennekin', False, 6], ['Braixen', False, 6], ['Delphox', False, 6], ['Froakie', False, 6], ['Frogadier', False, 6], ['Greninja', False, 6], ['Bunnelby', False, 6], ['Diggersby', False, 6], ['Fletchling', False, 6], ['Fletchinder', False, 6], ['Talonflame', False, 6], ['Scatterbug', False, 6], ['Spewpa', False, 6], ['Vivillon', False, 6], ['Litleo', False, 6], ['Pyroar', False, 6], ['Flabébé', False, 6], ['Floette', False, 6], ['Florges', False, 6], ['Skiddo', False, 6], ['Gogoat', False, 6], ['Pancham', False, 6], ['Pangoro', False, 6], ['Furfrou', False, 6], ['Espurr', False, 6], ['MeowsticMale', False, 6], ['MeowsticFemale', False, 6], ['Honedge', False, 6], ['Doublade', False, 6], ['AegislashBlade Forme', False, 6], ['AegislashShield Forme', False, 6], ['Spritzee', False, 6], ['Aromatisse', False, 6], ['Swirlix', False, 6], ['Slurpuff', False, 6], ['Inkay', False, 6], ['Malamar', False, 6], ['Binacle', False, 6], ['Barbaracle', False, 6], ['Skrelp', False, 6], ['Dragalge', False, 6], ['Clauncher', False, 6], ['Clawitzer', False, 6], ['Helioptile', False, 6], ['Heliolisk', False, 6], ['Tyrunt', False, 6], ['Tyrantrum', False, 6], ['Amaura', False, 6], ['Aurorus', False, 6], ['Sylveon', False, 6], ['Hawlucha', False, 6], ['Dedenne', False, 6], ['Carbink', False, 6], ['Goomy', False, 6], ['Sliggoo', False, 6], ['Goodra', False, 6], ['Klefki', False, 6], ['Phantump', False, 6], ['Trevenant', False, 6], ['PumpkabooAverage Size', False, 6], ['PumpkabooSmall Size', False, 6], ['PumpkabooLarge Size', False, 6], ['PumpkabooSuper Size', False, 6], ['GourgeistAverage Size', False, 6], ['GourgeistSmall Size', False, 6], ['GourgeistLarge Size', False, 6], ['GourgeistSuper Size', False, 6], ['Bergmite', False, 6], ['Avalugg', False, 6], ['Noibat', False, 6], ['Noivern', False, 6], ['Xerneas', True, 6], ['Yveltal', True, 6], ['Zygarde50% Forme', True, 6], ['Diancie', True, 6], ['DiancieMega Diancie', True, 6], ['HoopaHoopa Confined', True, 6], ['HoopaHoopa Unbound', True, 6], ['Volcanion', True, 6]]

The loop no longer convers tuples to lists with each iteration. Instead, we moved this tuple to list conversion outside (or below) the loop. That way, we convert data types all at once (or holistically) rahter than converting each iteration.

In [267]:
pokemon_types=list(set(pok['Type 1']))

In [268]:
pokemon_types

['Dark',
 'Rock',
 'Poison',
 'Steel',
 'Flying',
 'Bug',
 'Ice',
 'Dragon',
 'Water',
 'Normal',
 'Fire',
 'Ground',
 'Fairy',
 'Grass',
 'Fighting',
 'Electric',
 'Ghost',
 'Psychic']

In [269]:
# Collect all possible pairs using combinations()
possible_pairs = [*combinations(pokemon_types, 2)]

# Create an empty list called enumerated_tuples
enumerated_tuples = []

# Append each enumerated_pair_tuple to the empty list above
for i,pair in enumerate(possible_pairs, 1):
    enumerated_pair_tuple = (i,) + pair
    enumerated_tuples.append(enumerated_pair_tuple)

# Convert all tuples in enumerated_tuples to a list
enumerated_pairs = [*map(list, enumerated_tuples)]
print(enumerated_pairs)

[[1, 'Dark', 'Rock'], [2, 'Dark', 'Poison'], [3, 'Dark', 'Steel'], [4, 'Dark', 'Flying'], [5, 'Dark', 'Bug'], [6, 'Dark', 'Ice'], [7, 'Dark', 'Dragon'], [8, 'Dark', 'Water'], [9, 'Dark', 'Normal'], [10, 'Dark', 'Fire'], [11, 'Dark', 'Ground'], [12, 'Dark', 'Fairy'], [13, 'Dark', 'Grass'], [14, 'Dark', 'Fighting'], [15, 'Dark', 'Electric'], [16, 'Dark', 'Ghost'], [17, 'Dark', 'Psychic'], [18, 'Rock', 'Poison'], [19, 'Rock', 'Steel'], [20, 'Rock', 'Flying'], [21, 'Rock', 'Bug'], [22, 'Rock', 'Ice'], [23, 'Rock', 'Dragon'], [24, 'Rock', 'Water'], [25, 'Rock', 'Normal'], [26, 'Rock', 'Fire'], [27, 'Rock', 'Ground'], [28, 'Rock', 'Fairy'], [29, 'Rock', 'Grass'], [30, 'Rock', 'Fighting'], [31, 'Rock', 'Electric'], [32, 'Rock', 'Ghost'], [33, 'Rock', 'Psychic'], [34, 'Poison', 'Steel'], [35, 'Poison', 'Flying'], [36, 'Poison', 'Bug'], [37, 'Poison', 'Ice'], [38, 'Poison', 'Dragon'], [39, 'Poison', 'Water'], [40, 'Poison', 'Normal'], [41, 'Poison', 'Fire'], [42, 'Poison', 'Ground'], [43, 'Poison', 'Fairy'], [44, 'Poison', 'Grass'], [45, 'Poison', 'Fighting'], [46, 'Poison', 'Electric'], [47, 'Poison', 'Ghost'], [48, 'Poison', 'Psychic'], [49, 'Steel', 'Flying'], [50, 'Steel', 'Bug'], [51, 'Steel', 'Ice'], [52, 'Steel', 'Dragon'], [53, 'Steel', 'Water'], [54, 'Steel', 'Normal'], [55, 'Steel', 'Fire'], [56, 'Steel', 'Ground'], [57, 'Steel', 'Fairy'], [58, 'Steel', 'Grass'], [59, 'Steel', 'Fighting'], [60, 'Steel', 'Electric'], [61, 'Steel', 'Ghost'], [62, 'Steel', 'Psychic'], [63, 'Flying', 'Bug'], [64, 'Flying', 'Ice'], [65, 'Flying', 'Dragon'], [66, 'Flying', 'Water'], [67, 'Flying', 'Normal'], [68, 'Flying', 'Fire'], [69, 'Flying', 'Ground'], [70, 'Flying', 'Fairy'], [71, 'Flying', 'Grass'], [72, 'Flying', 'Fighting'], [73, 'Flying', 'Electric'], [74, 'Flying', 'Ghost'], [75, 'Flying', 'Psychic'], [76, 'Bug', 'Ice'], [77, 'Bug', 'Dragon'], [78, 'Bug', 'Water'], [79, 'Bug', 'Normal'], [80, 'Bug', 'Fire'], [81, 'Bug', 'Ground'], [82, 'Bug', 'Fairy'], [83, 'Bug', 'Grass'], [84, 'Bug', 'Fighting'], [85, 'Bug', 'Electric'], [86, 'Bug', 'Ghost'], [87, 'Bug', 'Psychic'], [88, 'Ice', 'Dragon'], [89, 'Ice', 'Water'], [90, 'Ice', 'Normal'], [91, 'Ice', 'Fire'], [92, 'Ice', 'Ground'], [93, 'Ice', 'Fairy'], [94, 'Ice', 'Grass'], [95, 'Ice', 'Fighting'], [96, 'Ice', 'Electric'], [97, 'Ice', 'Ghost'], [98, 'Ice', 'Psychic'], [99, 'Dragon', 'Water'], [100, 'Dragon', 'Normal'], [101, 'Dragon', 'Fire'], [102, 'Dragon', 'Ground'], [103, 'Dragon', 'Fairy'], [104, 'Dragon', 'Grass'], [105, 'Dragon', 'Fighting'], [106, 'Dragon', 'Electric'], [107, 'Dragon', 'Ghost'], [108, 'Dragon', 'Psychic'], [109, 'Water', 'Normal'], [110, 'Water', 'Fire'], [111, 'Water', 'Ground'], [112, 'Water', 'Fairy'], [113, 'Water', 'Grass'], [114, 'Water', 'Fighting'], [115, 'Water', 'Electric'], [116, 'Water', 'Ghost'], [117, 'Water', 'Psychic'], [118, 'Normal', 'Fire'], [119, 'Normal', 'Ground'], [120, 'Normal', 'Fairy'], [121, 'Normal', 'Grass'], [122, 'Normal', 'Fighting'], [123, 'Normal', 'Electric'], [124, 'Normal', 'Ghost'], [125, 'Normal', 'Psychic'], [126, 'Fire', 'Ground'], [127, 'Fire', 'Fairy'], [128, 'Fire', 'Grass'], [129, 'Fire', 'Fighting'], [130, 'Fire', 'Electric'], [131, 'Fire', 'Ghost'], [132, 'Fire', 'Psychic'], [133, 'Ground', 'Fairy'], [134, 'Ground', 'Grass'], [135, 'Ground', 'Fighting'], [136, 'Ground', 'Electric'], [137, 'Ground', 'Ghost'], [138, 'Ground', 'Psychic'], [139, 'Fairy', 'Grass'], [140, 'Fairy', 'Fighting'], [141, 'Fairy', 'Electric'], [142, 'Fairy', 'Ghost'], [143, 'Fairy', 'Psychic'], [144, 'Grass', 'Fighting'], [145, 'Grass', 'Electric'], [146, 'Grass', 'Ghost'], [147, 'Grass', 'Psychic'], [148, 'Fighting', 'Electric'], [149, 'Fighting', 'Ghost'], [150, 'Fighting', 'Psychic'], [151, 'Electric', 'Ghost'], [152, 'Electric', 'Psychic'], [153, 'Ghost', 'Psychic']]

In [275]:
hps=pok.HP.to_list()
hps=np.array(hps)

In [276]:
# Calculate the total HP avg and total HP standard deviation
hp_avg = hps.mean()
hp_std = hps.std()

# Use NumPy to eliminate the previous for loop
z_scores = (hps - hp_avg)/hp_std

# Combine names, hps, and z_scores
poke_zscores2 = [*zip(names, hps, z_scores)]
print(*poke_zscores2[:3], sep='\n')

('Bulbasaur', 45, -0.9506262218221118)
('Ivysaur', 60, -0.3628220964103872)
('Venusaur', 80, 0.42091673747191216)

In [277]:
# Use list comprehension with the same logic as the highest_hp_pokemon code block
highest_hp_pokemon2 = [(name, hp, zscore) for name,hp,zscore in poke_zscores2 if zscore > 2]
print(*highest_hp_pokemon2, sep='\n')

('Wigglytuff', 140, 2.7721332391188103)
('Chansey', 250, 7.082696825471457)
('Lapras', 130, 2.380263822177661)
('Vaporeon', 130, 2.380263822177661)
('Snorlax', 160, 3.55587207300111)
('Lanturn', 125, 2.184329113707086)
('Wobbuffet', 190, 4.731480323824559)
('Blissey', 255, 7.278631533942032)
('Slaking', 150, 3.16400265605996)
('Hariyama', 144, 2.92888100589527)
('Wailmer', 130, 2.380263822177661)
('Wailord', 170, 3.9477414899422594)
('Drifblim', 150, 3.16400265605996)
('Munchlax', 135, 2.5761985306482353)
('GiratinaAltered Forme', 150, 3.16400265605996)
('GiratinaOrigin Forme', 150, 3.16400265605996)
('Alomomola', 165, 3.7518067814716844)
('Kyurem', 125, 2.184329113707086)
('KyuremBlack Kyurem', 125, 2.184329113707086)
('KyuremWhite Kyurem', 125, 2.184329113707086)
('Gogoat', 123, 2.105955230318856)
('Aurorus', 123, 2.105955230318856)
('Xerneas', 126, 2.223516055401201)
('Yveltal', 126, 2.223516055401201)

## Pandas Optimization

In [279]:
df.head()

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG
0,ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415
1,ATL,NL,2012,700,600,94,0.320,0.389,0.247,1,4.0,5.0,162,0.306,0.378
2,BAL,AL,2012,712,705,93,0.311,0.417,0.247,1,5.0,4.0,162,0.315,0.403
3,BOS,AL,2012,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428
4,CHC,NL,2012,613,759,61,0.302,0.378,0.240,0,NaN,NaN,162,0.335,0.424

### A Team's Win Percentage

In [321]:
def win_perc(wins, game_played):
    win_percentage=wins/game_played
    return np.round(win_percentage,2)
win_perc(50,100)

0.5

I'd like to create a new column storing each teman's win percantages. To do this, we'll need to iterate over the DataFrame's rows and apply win_perc function.

In [302]:
win_perc_list=[]
for i in range(len(df)):
    row=df.iloc[i]
    wins=row['W']
    games_played=row['G']
    win_perc_df=win_perc(wins,games_played)
    win_perc_list.append(win_perc_df)
df['WP']=win_perc_list

Pandas comes with a few efficient methods for looping over a DataFrame.

### .iterrows()
This is similar as .iloc method, but .iterrows() method returns each DataFrame row as a tuple of index, pandas Series pairs. This means each object returned from .iterrows contains the index of each row as the first element and the data in each row as a pandas Series as the second element. Now we don't have to create an index variable to look up each row within the DataFrame.

In [322]:
win_perc_list_1=[]
for i, row in df.iterrows():
    wins=row['W']
    games_played=row['G']
    
    win_perc_df=win_perc(wins,games_played)
    win_perc_list_1.append(win_perc_df)
df['WP']=win_perc_list_1

In [325]:
df.shape

(1232, 16)

In [333]:
pit_df=df[(df['Team']=='PIT')&(df['Year']>=2007)]

In [336]:
for i,row in pit_df.iterrows():
    print(row)

Team              PIT
League             NL
Year             2012
RS                651
RA                674
W                  79
OBP             0.304
SLG             0.395
BA              0.243
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.314
OSLG             0.39
WP               0.49
Name: 21, dtype: object
Team              PIT
League             NL
Year             2011
RS                610
RA                712
W                  72
OBP             0.309
SLG             0.368
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.338
OSLG            0.409
WP               0.44
Name: 51, dtype: object
Team              PIT
League             NL
Year             2010
RS                587
RA                866
W                  57
OBP             0.304
SLG             0.373
BA              0.242
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.348
OSLG            0.449
WP               0.35
Name: 81, dtype: object
Team              PIT
League             NL
Year             2009
RS                636
RA                768
W                  62
OBP             0.318
SLG             0.387
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.346
OSLG            0.442
WP               0.39
Name: 111, dtype: object
Team              PIT
League             NL
Year             2008
RS                735
RA                884
W                  67
OBP              0.32
SLG             0.403
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.362
OSLG            0.454
WP               0.41
Name: 141, dtype: object
Team              PIT
League             NL
Year             2007
RS                724
RA                846
W                  68
OBP             0.325
SLG             0.411
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.352
OSLG            0.447
WP               0.42
Name: 171, dtype: object

In [338]:
for i,row in pit_df.iterrows():
    print(i)
    print(row)
    print(type(row))

21
Team              PIT
League             NL
Year             2012
RS                651
RA                674
W                  79
OBP             0.304
SLG             0.395
BA              0.243
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.314
OSLG             0.39
WP               0.49
Name: 21, dtype: object
<class 'pandas.core.series.Series'>
51
Team              PIT
League             NL
Year             2011
RS                610
RA                712
W                  72
OBP             0.309
SLG             0.368
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.338
OSLG            0.409
WP               0.44
Name: 51, dtype: object
<class 'pandas.core.series.Series'>
81
Team              PIT
League             NL
Year             2010
RS                587
RA                866
W                  57
OBP             0.304
SLG             0.373
BA              0.242
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.348
OSLG            0.449
WP               0.35
Name: 81, dtype: object
<class 'pandas.core.series.Series'>
111
Team              PIT
League             NL
Year             2009
RS                636
RA                768
W                  62
OBP             0.318
SLG             0.387
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.346
OSLG            0.442
WP               0.39
Name: 111, dtype: object
<class 'pandas.core.series.Series'>
141
Team              PIT
League             NL
Year             2008
RS                735
RA                884
W                  67
OBP              0.32
SLG             0.403
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.362
OSLG            0.454
WP               0.41
Name: 141, dtype: object
<class 'pandas.core.series.Series'>
171
Team              PIT
League             NL
Year             2007
RS                724
RA                846
W                  68
OBP             0.325
SLG             0.411
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.352
OSLG            0.447
WP               0.42
Name: 171, dtype: object
<class 'pandas.core.series.Series'>

In [339]:
for row_tuple in pit_df.iterrows():
    print(row_tuple)

(21, Team              PIT
League             NL
Year             2012
RS                651
RA                674
W                  79
OBP             0.304
SLG             0.395
BA              0.243
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.314
OSLG             0.39
WP               0.49
Name: 21, dtype: object)
(51, Team              PIT
League             NL
Year             2011
RS                610
RA                712
W                  72
OBP             0.309
SLG             0.368
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.338
OSLG            0.409
WP               0.44
Name: 51, dtype: object)
(81, Team              PIT
League             NL
Year             2010
RS                587
RA                866
W                  57
OBP             0.304
SLG             0.373
BA              0.242
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.348
OSLG            0.449
WP               0.35
Name: 81, dtype: object)
(111, Team              PIT
League             NL
Year             2009
RS                636
RA                768
W                  62
OBP             0.318
SLG             0.387
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.346
OSLG            0.442
WP               0.39
Name: 111, dtype: object)
(141, Team              PIT
League             NL
Year             2008
RS                735
RA                884
W                  67
OBP              0.32
SLG             0.403
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.362
OSLG            0.454
WP               0.41
Name: 141, dtype: object)
(171, Team              PIT
League             NL
Year             2007
RS                724
RA                846
W                  68
OBP             0.325
SLG             0.411
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.352
OSLG            0.447
WP               0.42
Name: 171, dtype: object)

### .itertuples()
It's often more efficient than .iterrows()

In [343]:
team_wins_df=df[['Team','Year','W']]
team_wins_df.head()

  Team  Year   W
0  ARI  2012  81
1  ATL  2012  94
2  BAL  2012  93
3  BOS  2012  69
4  CHC  2012  61

In [344]:
for row_namedtuple in team_wins_df.itertuples():
    print(row_namedtuple)

Pandas(Index=0, Team='ARI', Year=2012, W=81)
Pandas(Index=1, Team='ATL', Year=2012, W=94)
Pandas(Index=2, Team='BAL', Year=2012, W=93)
Pandas(Index=3, Team='BOS', Year=2012, W=69)
Pandas(Index=4, Team='CHC', Year=2012, W=61)
Pandas(Index=5, Team='CHW', Year=2012, W=85)
Pandas(Index=6, Team='CIN', Year=2012, W=97)
Pandas(Index=7, Team='CLE', Year=2012, W=68)
Pandas(Index=8, Team='COL', Year=2012, W=64)
Pandas(Index=9, Team='DET', Year=2012, W=88)
Pandas(Index=10, Team='HOU', Year=2012, W=55)
Pandas(Index=11, Team='KCR', Year=2012, W=72)
Pandas(Index=12, Team='LAA', Year=2012, W=89)
Pandas(Index=13, Team='LAD', Year=2012, W=86)
Pandas(Index=14, Team='MIA', Year=2012, W=69)
Pandas(Index=15, Team='MIL', Year=2012, W=83)
Pandas(Index=16, Team='MIN', Year=2012, W=66)
Pandas(Index=17, Team='NYM', Year=2012, W=74)
Pandas(Index=18, Team='NYY', Year=2012, W=95)
Pandas(Index=19, Team='OAK', Year=2012, W=94)
Pandas(Index=20, Team='PHI', Year=2012, W=81)
Pandas(Index=21, Team='PIT', Year=2012, W=79)
Pandas(Index=22, Team='SDP', Year=2012, W=76)
Pandas(Index=23, Team='SEA', Year=2012, W=75)
Pandas(Index=24, Team='SFG', Year=2012, W=94)
Pandas(Index=25, Team='STL', Year=2012, W=88)
Pandas(Index=26, Team='TBR', Year=2012, W=90)
Pandas(Index=27, Team='TEX', Year=2012, W=93)
Pandas(Index=28, Team='TOR', Year=2012, W=73)
Pandas(Index=29, Team='WSN', Year=2012, W=98)
Pandas(Index=30, Team='ARI', Year=2011, W=94)
Pandas(Index=31, Team='ATL', Year=2011, W=89)
Pandas(Index=32, Team='BAL', Year=2011, W=69)
Pandas(Index=33, Team='BOS', Year=2011, W=90)
Pandas(Index=34, Team='CHC', Year=2011, W=71)
Pandas(Index=35, Team='CHW', Year=2011, W=79)
Pandas(Index=36, Team='CIN', Year=2011, W=79)
Pandas(Index=37, Team='CLE', Year=2011, W=80)
Pandas(Index=38, Team='COL', Year=2011, W=73)
Pandas(Index=39, Team='DET', Year=2011, W=95)
Pandas(Index=40, Team='FLA', Year=2011, W=72)
Pandas(Index=41, Team='HOU', Year=2011, W=56)
Pandas(Index=42, Team='KCR', Year=2011, W=71)
Pandas(Index=43, Team='LAA', Year=2011, W=86)
Pandas(Index=44, Team='LAD', Year=2011, W=82)
Pandas(Index=45, Team='MIL', Year=2011, W=96)
Pandas(Index=46, Team='MIN', Year=2011, W=63)
Pandas(Index=47, Team='NYM', Year=2011, W=77)
Pandas(Index=48, Team='NYY', Year=2011, W=97)
Pandas(Index=49, Team='OAK', Year=2011, W=74)
Pandas(Index=50, Team='PHI', Year=2011, W=102)
Pandas(Index=51, Team='PIT', Year=2011, W=72)
Pandas(Index=52, Team='SDP', Year=2011, W=71)
Pandas(Index=53, Team='SEA', Year=2011, W=67)
Pandas(Index=54, Team='SFG', Year=2011, W=86)
Pandas(Index=55, Team='STL', Year=2011, W=90)
Pandas(Index=56, Team='TBR', Year=2011, W=91)
Pandas(Index=57, Team='TEX', Year=2011, W=96)
Pandas(Index=58, Team='TOR', Year=2011, W=81)
Pandas(Index=59, Team='WSN', Year=2011, W=80)
Pandas(Index=60, Team='ARI', Year=2010, W=65)
Pandas(Index=61, Team='ATL', Year=2010, W=91)
Pandas(Index=62, Team='BAL', Year=2010, W=66)
Pandas(Index=63, Team='BOS', Year=2010, W=89)
Pandas(Index=64, Team='CHC', Year=2010, W=75)
Pandas(Index=65, Team='CHW', Year=2010, W=88)
Pandas(Index=66, Team='CIN', Year=2010, W=91)
Pandas(Index=67, Team='CLE', Year=2010, W=69)
Pandas(Index=68, Team='COL', Year=2010, W=83)
Pandas(Index=69, Team='DET', Year=2010, W=81)
Pandas(Index=70, Team='FLA', Year=2010, W=80)
Pandas(Index=71, Team='HOU', Year=2010, W=76)
Pandas(Index=72, Team='KCR', Year=2010, W=67)
Pandas(Index=73, Team='LAA', Year=2010, W=80)
Pandas(Index=74, Team='LAD', Year=2010, W=80)
Pandas(Index=75, Team='MIL', Year=2010, W=77)
Pandas(Index=76, Team='MIN', Year=2010, W=94)
Pandas(Index=77, Team='NYM', Year=2010, W=79)
Pandas(Index=78, Team='NYY', Year=2010, W=95)
Pandas(Index=79, Team='OAK', Year=2010, W=81)
Pandas(Index=80, Team='PHI', Year=2010, W=97)
Pandas(Index=81, Team='PIT', Year=2010, W=57)
Pandas(Index=82, Team='SDP', Year=2010, W=90)
Pandas(Index=83, Team='SEA', Year=2010, W=61)
Pandas(Index=84, Team='SFG', Year=2010, W=92)
Pandas(Index=85, Team='STL', Year=2010, W=86)
Pandas(Index=86, Team='TBR', Year=2010, W=96)
Pandas(Index=87, Team='TEX', Year=2010, W=90)
Pandas(Index=88, Team='TOR', Year=2010, W=85)
Pandas(Index=89, Team='WSN', Year=2010, W=69)
Pandas(Index=90, Team='ARI', Year=2009, W=70)
Pandas(Index=91, Team='ATL', Year=2009, W=86)
Pandas(Index=92, Team='BAL', Year=2009, W=64)
Pandas(Index=93, Team='BOS', Year=2009, W=95)
Pandas(Index=94, Team='CHC', Year=2009, W=83)
Pandas(Index=95, Team='CHW', Year=2009, W=79)
Pandas(Index=96, Team='CIN', Year=2009, W=78)
Pandas(Index=97, Team='CLE', Year=2009, W=65)
Pandas(Index=98, Team='COL', Year=2009, W=92)
Pandas(Index=99, Team='DET', Year=2009, W=86)
Pandas(Index=100, Team='FLA', Year=2009, W=87)
Pandas(Index=101, Team='HOU', Year=2009, W=74)
Pandas(Index=102, Team='KCR', Year=2009, W=65)
Pandas(Index=103, Team='LAA', Year=2009, W=97)
Pandas(Index=104, Team='LAD', Year=2009, W=95)
Pandas(Index=105, Team='MIL', Year=2009, W=80)
Pandas(Index=106, Team='MIN', Year=2009, W=87)
Pandas(Index=107, Team='NYM', Year=2009, W=70)
Pandas(Index=108, Team='NYY', Year=2009, W=103)
Pandas(Index=109, Team='OAK', Year=2009, W=75)
Pandas(Index=110, Team='PHI', Year=2009, W=93)
Pandas(Index=111, Team='PIT', Year=2009, W=62)
Pandas(Index=112, Team='SDP', Year=2009, W=75)
Pandas(Index=113, Team='SEA', Year=2009, W=85)
Pandas(Index=114, Team='SFG', Year=2009, W=88)
Pandas(Index=115, Team='STL', Year=2009, W=91)
Pandas(Index=116, Team='TBR', Year=2009, W=84)
Pandas(Index=117, Team='TEX', Year=2009, W=87)
Pandas(Index=118, Team='TOR', Year=2009, W=75)
Pandas(Index=119, Team='WSN', Year=2009, W=59)
Pandas(Index=120, Team='ARI', Year=2008, W=82)
Pandas(Index=121, Team='ATL', Year=2008, W=72)
Pandas(Index=122, Team='BAL', Year=2008, W=68)
Pandas(Index=123, Team='BOS', Year=2008, W=95)
Pandas(Index=124, Team='CHC', Year=2008, W=97)
Pandas(Index=125, Team='CHW', Year=2008, W=89)
Pandas(Index=126, Team='CIN', Year=2008, W=74)
Pandas(Index=127, Team='CLE', Year=2008, W=81)
Pandas(Index=128, Team='COL', Year=2008, W=74)
Pandas(Index=129, Team='DET', Year=2008, W=74)
Pandas(Index=130, Team='FLA', Year=2008, W=84)
Pandas(Index=131, Team='HOU', Year=2008, W=86)
Pandas(Index=132, Team='KCR', Year=2008, W=75)
Pandas(Index=133, Team='LAA', Year=2008, W=100)
Pandas(Index=134, Team='LAD', Year=2008, W=84)
Pandas(Index=135, Team='MIL', Year=2008, W=90)
Pandas(Index=136, Team='MIN', Year=2008, W=88)
Pandas(Index=137, Team='NYM', Year=2008, W=89)
Pandas(Index=138, Team='NYY', Year=2008, W=89)
Pandas(Index=139, Team='OAK', Year=2008, W=75)
Pandas(Index=140, Team='PHI', Year=2008, W=92)
Pandas(Index=141, Team='PIT', Year=2008, W=67)
Pandas(Index=142, Team='SDP', Year=2008, W=63)
Pandas(Index=143, Team='SEA', Year=2008, W=61)
Pandas(Index=144, Team='SFG', Year=2008, W=72)
Pandas(Index=145, Team='STL', Year=2008, W=86)
Pandas(Index=146, Team='TBR', Year=2008, W=97)
Pandas(Index=147, Team='TEX', Year=2008, W=79)
Pandas(Index=148, Team='TOR', Year=2008, W=86)
Pandas(Index=149, Team='WSN', Year=2008, W=59)
Pandas(Index=150, Team='ARI', Year=2007, W=90)
Pandas(Index=151, Team='ATL', Year=2007, W=84)
Pandas(Index=152, Team='BAL', Year=2007, W=69)
Pandas(Index=153, Team='BOS', Year=2007, W=96)
Pandas(Index=154, Team='CHC', Year=2007, W=85)
Pandas(Index=155, Team='CHW', Year=2007, W=72)
Pandas(Index=156, Team='CIN', Year=2007, W=72)
Pandas(Index=157, Team='CLE', Year=2007, W=96)
Pandas(Index=158, Team='COL', Year=2007, W=90)
Pandas(Index=159, Team='DET', Year=2007, W=88)
Pandas(Index=160, Team='FLA', Year=2007, W=71)
Pandas(Index=161, Team='HOU', Year=2007, W=73)
Pandas(Index=162, Team='KCR', Year=2007, W=69)
Pandas(Index=163, Team='LAA', Year=2007, W=94)
Pandas(Index=164, Team='LAD', Year=2007, W=82)
Pandas(Index=165, Team='MIL', Year=2007, W=83)
Pandas(Index=166, Team='MIN', Year=2007, W=79)
Pandas(Index=167, Team='NYM', Year=2007, W=88)
Pandas(Index=168, Team='NYY', Year=2007, W=94)
Pandas(Index=169, Team='OAK', Year=2007, W=76)
Pandas(Index=170, Team='PHI', Year=2007, W=89)
Pandas(Index=171, Team='PIT', Year=2007, W=68)
Pandas(Index=172, Team='SDP', Year=2007, W=89)
Pandas(Index=173, Team='SEA', Year=2007, W=88)
Pandas(Index=174, Team='SFG', Year=2007, W=71)
Pandas(Index=175, Team='STL', Year=2007, W=78)
Pandas(Index=176, Team='TBD', Year=2007, W=66)
Pandas(Index=177, Team='TEX', Year=2007, W=75)
Pandas(Index=178, Team='TOR', Year=2007, W=83)
Pandas(Index=179, Team='WSN', Year=2007, W=73)
Pandas(Index=180, Team='ARI', Year=2006, W=76)
Pandas(Index=181, Team='ATL', Year=2006, W=79)
Pandas(Index=182, Team='BAL', Year=2006, W=70)
Pandas(Index=183, Team='BOS', Year=2006, W=86)
Pandas(Index=184, Team='CHC', Year=2006, W=66)
Pandas(Index=185, Team='CHW', Year=2006, W=90)
Pandas(Index=186, Team='CIN', Year=2006, W=80)
Pandas(Index=187, Team='CLE', Year=2006, W=78)
Pandas(Index=188, Team='COL', Year=2006, W=76)
Pandas(Index=189, Team='DET', Year=2006, W=95)
Pandas(Index=190, Team='FLA', Year=2006, W=78)
Pandas(Index=191, Team='HOU', Year=2006, W=82)
Pandas(Index=192, Team='KCR', Year=2006, W=62)
Pandas(Index=193, Team='LAA', Year=2006, W=89)
Pandas(Index=194, Team='LAD', Year=2006, W=88)
Pandas(Index=195, Team='MIL', Year=2006, W=75)
Pandas(Index=196, Team='MIN', Year=2006, W=96)
Pandas(Index=197, Team='NYM', Year=2006, W=97)
Pandas(Index=198, Team='NYY', Year=2006, W=97)
Pandas(Index=199, Team='OAK', Year=2006, W=93)
Pandas(Index=200, Team='PHI', Year=2006, W=85)
Pandas(Index=201, Team='PIT', Year=2006, W=67)
Pandas(Index=202, Team='SDP', Year=2006, W=88)
Pandas(Index=203, Team='SEA', Year=2006, W=78)
Pandas(Index=204, Team='SFG', Year=2006, W=76)
Pandas(Index=205, Team='STL', Year=2006, W=83)
Pandas(Index=206, Team='TBD', Year=2006, W=61)
Pandas(Index=207, Team='TEX', Year=2006, W=80)
Pandas(Index=208, Team='TOR', Year=2006, W=87)
Pandas(Index=209, Team='WSN', Year=2006, W=71)
Pandas(Index=210, Team='ARI', Year=2005, W=77)
Pandas(Index=211, Team='ATL', Year=2005, W=90)
Pandas(Index=212, Team='BAL', Year=2005, W=74)
Pandas(Index=213, Team='BOS', Year=2005, W=95)
Pandas(Index=214, Team='CHC', Year=2005, W=79)
Pandas(Index=215, Team='CHW', Year=2005, W=99)
Pandas(Index=216, Team='CIN', Year=2005, W=73)
Pandas(Index=217, Team='CLE', Year=2005, W=93)
Pandas(Index=218, Team='COL', Year=2005, W=67)
Pandas(Index=219, Team='DET', Year=2005, W=71)
Pandas(Index=220, Team='FLA', Year=2005, W=83)
Pandas(Index=221, Team='HOU', Year=2005, W=89)
Pandas(Index=222, Team='KCR', Year=2005, W=56)
Pandas(Index=223, Team='LAA', Year=2005, W=95)
Pandas(Index=224, Team='LAD', Year=2005, W=71)
Pandas(Index=225, Team='MIL', Year=2005, W=81)
Pandas(Index=226, Team='MIN', Year=2005, W=83)
Pandas(Index=227, Team='NYM', Year=2005, W=83)
Pandas(Index=228, Team='NYY', Year=2005, W=95)
Pandas(Index=229, Team='OAK', Year=2005, W=88)
Pandas(Index=230, Team='PHI', Year=2005, W=88)
Pandas(Index=231, Team='PIT', Year=2005, W=67)
Pandas(Index=232, Team='SDP', Year=2005, W=82)
Pandas(Index=233, Team='SEA', Year=2005, W=69)
Pandas(Index=234, Team='SFG', Year=2005, W=75)
Pandas(Index=235, Team='STL', Year=2005, W=100)
Pandas(Index=236, Team='TBD', Year=2005, W=67)
Pandas(Index=237, Team='TEX', Year=2005, W=79)
Pandas(Index=238, Team='TOR', Year=2005, W=80)
Pandas(Index=239, Team='WSN', Year=2005, W=81)
Pandas(Index=240, Team='ANA', Year=2004, W=92)
Pandas(Index=241, Team='ARI', Year=2004, W=51)
Pandas(Index=242, Team='ATL', Year=2004, W=96)
Pandas(Index=243, Team='BAL', Year=2004, W=78)
Pandas(Index=244, Team='BOS', Year=2004, W=98)
Pandas(Index=245, Team='CHC', Year=2004, W=89)
Pandas(Index=246, Team='CHW', Year=2004, W=83)
Pandas(Index=247, Team='CIN', Year=2004, W=76)
Pandas(Index=248, Team='CLE', Year=2004, W=80)
Pandas(Index=249, Team='COL', Year=2004, W=68)
Pandas(Index=250, Team='DET', Year=2004, W=72)
Pandas(Index=251, Team='FLA', Year=2004, W=83)
Pandas(Index=252, Team='HOU', Year=2004, W=92)
Pandas(Index=253, Team='KCR', Year=2004, W=58)
Pandas(Index=254, Team='LAD', Year=2004, W=93)
Pandas(Index=255, Team='MIL', Year=2004, W=67)
Pandas(Index=256, Team='MIN', Year=2004, W=92)
Pandas(Index=257, Team='MON', Year=2004, W=67)
Pandas(Index=258, Team='NYM', Year=2004, W=71)
Pandas(Index=259, Team='NYY', Year=2004, W=101)
Pandas(Index=260, Team='OAK', Year=2004, W=91)
Pandas(Index=261, Team='PHI', Year=2004, W=86)
Pandas(Index=262, Team='PIT', Year=2004, W=72)
Pandas(Index=263, Team='SDP', Year=2004, W=87)
Pandas(Index=264, Team='SEA', Year=2004, W=63)
Pandas(Index=265, Team='SFG', Year=2004, W=91)
Pandas(Index=266, Team='STL', Year=2004, W=105)
Pandas(Index=267, Team='TBD', Year=2004, W=70)
Pandas(Index=268, Team='TEX', Year=2004, W=89)
Pandas(Index=269, Team='TOR', Year=2004, W=67)
Pandas(Index=270, Team='ANA', Year=2003, W=77)
Pandas(Index=271, Team='ARI', Year=2003, W=84)
Pandas(Index=272, Team='ATL', Year=2003, W=101)
Pandas(Index=273, Team='BAL', Year=2003, W=71)
Pandas(Index=274, Team='BOS', Year=2003, W=95)
Pandas(Index=275, Team='CHC', Year=2003, W=88)
Pandas(Index=276, Team='CHW', Year=2003, W=86)
Pandas(Index=277, Team='CIN', Year=2003, W=69)
Pandas(Index=278, Team='CLE', Year=2003, W=68)
Pandas(Index=279, Team='COL', Year=2003, W=74)
Pandas(Index=280, Team='DET', Year=2003, W=43)
Pandas(Index=281, Team='FLA', Year=2003, W=91)
Pandas(Index=282, Team='HOU', Year=2003, W=87)
Pandas(Index=283, Team='KCR', Year=2003, W=83)
Pandas(Index=284, Team='LAD', Year=2003, W=85)
Pandas(Index=285, Team='MIL', Year=2003, W=68)
Pandas(Index=286, Team='MIN', Year=2003, W=90)
Pandas(Index=287, Team='MON', Year=2003, W=83)
Pandas(Index=288, Team='NYM', Year=2003, W=66)
Pandas(Index=289, Team='NYY', Year=2003, W=101)
Pandas(Index=290, Team='OAK', Year=2003, W=96)
Pandas(Index=291, Team='PHI', Year=2003, W=86)
Pandas(Index=292, Team='PIT', Year=2003, W=75)
Pandas(Index=293, Team='SDP', Year=2003, W=64)
Pandas(Index=294, Team='SEA', Year=2003, W=93)
Pandas(Index=295, Team='SFG', Year=2003, W=100)
Pandas(Index=296, Team='STL', Year=2003, W=85)
Pandas(Index=297, Team='TBD', Year=2003, W=63)
Pandas(Index=298, Team='TEX', Year=2003, W=71)
Pandas(Index=299, Team='TOR', Year=2003, W=86)
Pandas(Index=300, Team='ANA', Year=2002, W=99)
Pandas(Index=301, Team='ARI', Year=2002, W=98)
Pandas(Index=302, Team='ATL', Year=2002, W=101)
Pandas(Index=303, Team='BAL', Year=2002, W=67)
Pandas(Index=304, Team='BOS', Year=2002, W=93)
Pandas(Index=305, Team='CHC', Year=2002, W=67)
Pandas(Index=306, Team='CHW', Year=2002, W=81)
Pandas(Index=307, Team='CIN', Year=2002, W=78)
Pandas(Index=308, Team='CLE', Year=2002, W=74)
Pandas(Index=309, Team='COL', Year=2002, W=73)
Pandas(Index=310, Team='DET', Year=2002, W=55)
Pandas(Index=311, Team='FLA', Year=2002, W=79)
Pandas(Index=312, Team='HOU', Year=2002, W=84)
Pandas(Index=313, Team='KCR', Year=2002, W=62)
Pandas(Index=314, Team='LAD', Year=2002, W=92)
Pandas(Index=315, Team='MIL', Year=2002, W=56)
Pandas(Index=316, Team='MIN', Year=2002, W=94)
Pandas(Index=317, Team='MON', Year=2002, W=83)
Pandas(Index=318, Team='NYM', Year=2002, W=75)
Pandas(Index=319, Team='NYY', Year=2002, W=103)
Pandas(Index=320, Team='OAK', Year=2002, W=103)
Pandas(Index=321, Team='PHI', Year=2002, W=80)
Pandas(Index=322, Team='PIT', Year=2002, W=72)
Pandas(Index=323, Team='SDP', Year=2002, W=66)
Pandas(Index=324, Team='SEA', Year=2002, W=93)
Pandas(Index=325, Team='SFG', Year=2002, W=95)
Pandas(Index=326, Team='STL', Year=2002, W=97)
Pandas(Index=327, Team='TBD', Year=2002, W=55)
Pandas(Index=328, Team='TEX', Year=2002, W=72)
Pandas(Index=329, Team='TOR', Year=2002, W=78)
Pandas(Index=330, Team='ANA', Year=2001, W=75)
Pandas(Index=331, Team='ARI', Year=2001, W=92)
Pandas(Index=332, Team='ATL', Year=2001, W=88)
Pandas(Index=333, Team='BAL', Year=2001, W=63)
Pandas(Index=334, Team='BOS', Year=2001, W=82)
Pandas(Index=335, Team='CHC', Year=2001, W=88)
Pandas(Index=336, Team='CHW', Year=2001, W=83)
Pandas(Index=337, Team='CIN', Year=2001, W=66)
Pandas(Index=338, Team='CLE', Year=2001, W=91)
Pandas(Index=339, Team='COL', Year=2001, W=73)
Pandas(Index=340, Team='DET', Year=2001, W=66)
Pandas(Index=341, Team='FLA', Year=2001, W=76)
Pandas(Index=342, Team='HOU', Year=2001, W=93)
Pandas(Index=343, Team='KCR', Year=2001, W=65)
Pandas(Index=344, Team='LAD', Year=2001, W=86)
Pandas(Index=345, Team='MIL', Year=2001, W=68)
Pandas(Index=346, Team='MIN', Year=2001, W=85)
Pandas(Index=347, Team='MON', Year=2001, W=68)
Pandas(Index=348, Team='NYM', Year=2001, W=82)
Pandas(Index=349, Team='NYY', Year=2001, W=95)
Pandas(Index=350, Team='OAK', Year=2001, W=102)
Pandas(Index=351, Team='PHI', Year=2001, W=86)
Pandas(Index=352, Team='PIT', Year=2001, W=62)
Pandas(Index=353, Team='SDP', Year=2001, W=79)
Pandas(Index=354, Team='SEA', Year=2001, W=116)
Pandas(Index=355, Team='SFG', Year=2001, W=90)
Pandas(Index=356, Team='STL', Year=2001, W=93)
Pandas(Index=357, Team='TBD', Year=2001, W=62)
Pandas(Index=358, Team='TEX', Year=2001, W=73)
Pandas(Index=359, Team='TOR', Year=2001, W=80)
Pandas(Index=360, Team='ANA', Year=2000, W=82)
Pandas(Index=361, Team='ARI', Year=2000, W=85)
Pandas(Index=362, Team='ATL', Year=2000, W=95)
Pandas(Index=363, Team='BAL', Year=2000, W=74)
Pandas(Index=364, Team='BOS', Year=2000, W=85)
Pandas(Index=365, Team='CHC', Year=2000, W=65)
Pandas(Index=366, Team='CHW', Year=2000, W=95)
Pandas(Index=367, Team='CIN', Year=2000, W=85)
Pandas(Index=368, Team='CLE', Year=2000, W=90)
Pandas(Index=369, Team='COL', Year=2000, W=82)
Pandas(Index=370, Team='DET', Year=2000, W=79)
Pandas(Index=371, Team='FLA', Year=2000, W=79)
Pandas(Index=372, Team='HOU', Year=2000, W=72)
Pandas(Index=373, Team='KCR', Year=2000, W=77)
Pandas(Index=374, Team='LAD', Year=2000, W=86)
Pandas(Index=375, Team='MIL', Year=2000, W=73)
Pandas(Index=376, Team='MIN', Year=2000, W=69)
Pandas(Index=377, Team='MON', Year=2000, W=67)
Pandas(Index=378, Team='NYM', Year=2000, W=94)
Pandas(Index=379, Team='NYY', Year=2000, W=87)
Pandas(Index=380, Team='OAK', Year=2000, W=91)
Pandas(Index=381, Team='PHI', Year=2000, W=65)
Pandas(Index=382, Team='PIT', Year=2000, W=69)
Pandas(Index=383, Team='SDP', Year=2000, W=76)
Pandas(Index=384, Team='SEA', Year=2000, W=91)
Pandas(Index=385, Team='SFG', Year=2000, W=97)
Pandas(Index=386, Team='STL', Year=2000, W=95)
Pandas(Index=387, Team='TBD', Year=2000, W=69)
Pandas(Index=388, Team='TEX', Year=2000, W=71)
Pandas(Index=389, Team='TOR', Year=2000, W=83)
Pandas(Index=390, Team='ANA', Year=1999, W=70)
Pandas(Index=391, Team='ARI', Year=1999, W=100)
Pandas(Index=392, Team='ATL', Year=1999, W=103)
Pandas(Index=393, Team='BAL', Year=1999, W=78)
Pandas(Index=394, Team='BOS', Year=1999, W=94)
Pandas(Index=395, Team='CHC', Year=1999, W=67)
Pandas(Index=396, Team='CHW', Year=1999, W=75)
Pandas(Index=397, Team='CIN', Year=1999, W=96)
Pandas(Index=398, Team='CLE', Year=1999, W=97)
Pandas(Index=399, Team='COL', Year=1999, W=72)
Pandas(Index=400, Team='DET', Year=1999, W=69)
Pandas(Index=401, Team='FLA', Year=1999, W=64)
Pandas(Index=402, Team='HOU', Year=1999, W=97)
Pandas(Index=403, Team='KCR', Year=1999, W=64)
Pandas(Index=404, Team='LAD', Year=1999, W=77)
Pandas(Index=405, Team='MIL', Year=1999, W=74)
Pandas(Index=406, Team='MIN', Year=1999, W=63)
Pandas(Index=407, Team='MON', Year=1999, W=68)
Pandas(Index=408, Team='NYM', Year=1999, W=97)
Pandas(Index=409, Team='NYY', Year=1999, W=98)
Pandas(Index=410, Team='OAK', Year=1999, W=87)
Pandas(Index=411, Team='PHI', Year=1999, W=77)
Pandas(Index=412, Team='PIT', Year=1999, W=78)
Pandas(Index=413, Team='SDP', Year=1999, W=74)
Pandas(Index=414, Team='SEA', Year=1999, W=79)
Pandas(Index=415, Team='SFG', Year=1999, W=86)
Pandas(Index=416, Team='STL', Year=1999, W=75)
Pandas(Index=417, Team='TBD', Year=1999, W=69)
Pandas(Index=418, Team='TEX', Year=1999, W=95)
Pandas(Index=419, Team='TOR', Year=1999, W=84)
Pandas(Index=420, Team='ANA', Year=1998, W=85)
Pandas(Index=421, Team='ARI', Year=1998, W=65)
Pandas(Index=422, Team='ATL', Year=1998, W=106)
Pandas(Index=423, Team='BAL', Year=1998, W=79)
Pandas(Index=424, Team='BOS', Year=1998, W=92)
Pandas(Index=425, Team='CHC', Year=1998, W=90)
Pandas(Index=426, Team='CHW', Year=1998, W=80)

In [359]:
for row_tuple in team_wins_df.iterrows():
    print(row_tuple[1]['Team'])

ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
HOU
KCR
LAA
LAD
MIA
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBR
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBR
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBR
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBR
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBR
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
WSN
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SFG
STL
TEX
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SFG
STL
TEX
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SFG
STL
TEX
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SFG
STL
TEX
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SFG
STL
WSA
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SFG
STL
WSA
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEP
SFG
STL
WSA
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
LAD
MIN
NYM
NYY
OAK
PHI
PIT
SFG
STL
WSA
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCA
LAD
MIN
NYM
NYY
PHI
PIT
SFG
STL
WSA
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCA
LAD
MIN
NYM
NYY
PHI
PIT
SFG
STL
WSA
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCA
LAD
MIN
MLN
NYM
NYY
PHI
PIT
SFG
STL
WSA
BAL
BOS
CHC
CHW
CIN
CLE
DET
HOU
KCA
LAA
LAD
MIN
MLN
NYM
NYY
PHI
PIT
SFG
STL
WSA
BAL
BOS
CHC
CHW
CIN
CLE
DET
HOU
KCA
LAA
LAD
MIN
MLN
NYM
NYY
PHI
PIT
SFG
STL
WSA
BAL
BOS
CHC
CHW
CIN
CLE
DET
HOU
KCA
LAA
LAD
MIN
MLN
NYM
NYY
PHI
PIT
SFG
STL
WSA

In [357]:
for row_namedtuple in team_wins_df.itertuples():
    print(row_namedtuple.Team)

ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
HOU
KCR
LAA
LAD
MIA
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBR
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBR
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBR
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBR
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBR
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
WSN
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SFG
STL
TEX
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SFG
STL
TEX
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SFG
STL
TEX
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SFG
STL
TEX
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SFG
STL
WSA
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SFG
STL
WSA
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEP
SFG
STL
WSA
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
LAD
MIN
NYM
NYY
OAK
PHI
PIT
SFG
STL
WSA
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCA
LAD
MIN
NYM
NYY
PHI
PIT
SFG
STL
WSA
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCA
LAD
MIN
NYM
NYY
PHI
PIT
SFG
STL
WSA
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCA
LAD
MIN
MLN
NYM
NYY
PHI
PIT
SFG
STL
WSA
BAL
BOS
CHC
CHW
CIN
CLE
DET
HOU
KCA
LAA
LAD
MIN
MLN
NYM
NYY
PHI
PIT
SFG
STL
WSA
BAL
BOS
CHC
CHW
CIN
CLE
DET
HOU
KCA
LAA
LAD
MIN
MLN
NYM
NYY
PHI
PIT
SFG
STL
WSA
BAL
BOS
CHC
CHW
CIN
CLE
DET
HOU
KCA
LAA
LAD
MIN
MLN
NYM
NYY
PHI
PIT
SFG
STL
WSA

Namedtuples does not support square bracket like a pandas Series does.

In [360]:
for row in team_wins_df.itertuples():
  i = row.Index
  year = row.Year
  wins = row.W
  print(i, year, wins)

0 2012 81
1 2012 94
2 2012 93
3 2012 69
4 2012 61
5 2012 85
6 2012 97
7 2012 68
8 2012 64
9 2012 88
10 2012 55
11 2012 72
12 2012 89
13 2012 86
14 2012 69
15 2012 83
16 2012 66
17 2012 74
18 2012 95
19 2012 94
20 2012 81
21 2012 79
22 2012 76
23 2012 75
24 2012 94
25 2012 88
26 2012 90
27 2012 93
28 2012 73
29 2012 98
30 2011 94
31 2011 89
32 2011 69
33 2011 90
34 2011 71
35 2011 79
36 2011 79
37 2011 80
38 2011 73
39 2011 95
40 2011 72
41 2011 56
42 2011 71
43 2011 86
44 2011 82
45 2011 96
46 2011 63
47 2011 77
48 2011 97
49 2011 74
50 2011 102
51 2011 72
52 2011 71
53 2011 67
54 2011 86
55 2011 90
56 2011 91
57 2011 96
58 2011 81
59 2011 80
60 2010 65
61 2010 91
62 2010 66
63 2010 89
64 2010 75
65 2010 88
66 2010 91
67 2010 69
68 2010 83
69 2010 81
70 2010 80
71 2010 76
72 2010 67
73 2010 80
74 2010 80
75 2010 77
76 2010 94
77 2010 79
78 2010 95
79 2010 81
80 2010 97
81 2010 57
82 2010 90
83 2010 61
84 2010 92
85 2010 86
86 2010 96
87 2010 90
88 2010 85
89 2010 69
90 2009 70
91 2009 86
92 2009 64
93 2009 95
94 2009 83
95 2009 79
96 2009 78
97 2009 65
98 2009 92
99 2009 86
100 2009 87
101 2009 74
102 2009 65
103 2009 97
104 2009 95
105 2009 80
106 2009 87
107 2009 70
108 2009 103
109 2009 75
110 2009 93
111 2009 62
112 2009 75
113 2009 85
114 2009 88
115 2009 91
116 2009 84
117 2009 87
118 2009 75
119 2009 59
120 2008 82
121 2008 72
122 2008 68
123 2008 95
124 2008 97
125 2008 89
126 2008 74
127 2008 81
128 2008 74
129 2008 74
130 2008 84
131 2008 86
132 2008 75
133 2008 100
134 2008 84
135 2008 90
136 2008 88
137 2008 89
138 2008 89
139 2008 75
140 2008 92
141 2008 67
142 2008 63
143 2008 61
144 2008 72
145 2008 86
146 2008 97
147 2008 79
148 2008 86
149 2008 59
150 2007 90
151 2007 84
152 2007 69
153 2007 96
154 2007 85
155 2007 72
156 2007 72
157 2007 96
158 2007 90
159 2007 88
160 2007 71
161 2007 73
162 2007 69
163 2007 94
164 2007 82
165 2007 83
166 2007 79
167 2007 88
168 2007 94
169 2007 76
170 2007 89
171 2007 68
172 2007 89
173 2007 88
174 2007 71
175 2007 78
176 2007 66
177 2007 75
178 2007 83
179 2007 73
180 2006 76
181 2006 79
182 2006 70
183 2006 86
184 2006 66
185 2006 90
186 2006 80
187 2006 78
188 2006 76
189 2006 95
190 2006 78
191 2006 82
192 2006 62
193 2006 89
194 2006 88
195 2006 75
196 2006 96
197 2006 97
198 2006 97
199 2006 93
200 2006 85
201 2006 67
202 2006 88
203 2006 78
204 2006 76
205 2006 83
206 2006 61
207 2006 80
208 2006 87
209 2006 71
210 2005 77
211 2005 90
212 2005 74
213 2005 95
214 2005 79
215 2005 99
216 2005 73
217 2005 93
218 2005 67
219 2005 71
220 2005 83
221 2005 89
222 2005 56
223 2005 95
224 2005 71
225 2005 81
226 2005 83
227 2005 83
228 2005 95
229 2005 88
230 2005 88
231 2005 67
232 2005 82
233 2005 69
234 2005 75
235 2005 100
236 2005 67
237 2005 79
238 2005 80
239 2005 81
240 2004 92
241 2004 51
242 2004 96
243 2004 78
244 2004 98
245 2004 89
246 2004 83
247 2004 76
248 2004 80
249 2004 68
250 2004 72
251 2004 83
252 2004 92
253 2004 58
254 2004 93
255 2004 67
256 2004 92
257 2004 67
258 2004 71
259 2004 101
260 2004 91
261 2004 86
262 2004 72
263 2004 87
264 2004 63
265 2004 91
266 2004 105
267 2004 70
268 2004 89
269 2004 67
270 2003 77
271 2003 84
272 2003 101
273 2003 71
274 2003 95
275 2003 88
276 2003 86
277 2003 69
278 2003 68
279 2003 74
280 2003 43
281 2003 91
282 2003 87
283 2003 83
284 2003 85
285 2003 68
286 2003 90
287 2003 83
288 2003 66
289 2003 101
290 2003 96
291 2003 86
292 2003 75
293 2003 64
294 2003 93
295 2003 100
296 2003 85
297 2003 63
298 2003 71
299 2003 86
300 2002 99
301 2002 98
302 2002 101
303 2002 67
304 2002 93
305 2002 67
306 2002 81
307 2002 78
308 2002 74
309 2002 73
310 2002 55
311 2002 79
312 2002 84
313 2002 62
314 2002 92
315 2002 56
316 2002 94
317 2002 83
318 2002 75
319 2002 103
320 2002 103
321 2002 80
322 2002 72
323 2002 66
324 2002 93
325 2002 95
326 2002 97
327 2002 55
328 2002 72
329 2002 78
330 2001 75
331 2001 92
332 2001 88
333 2001 63
334 2001 82
335 2001 88
336 2001 83
337 2001 66
338 2001 91
339 2001 73
340 2001 66
341 2001 76
342 2001 93
343 2001 65
344 2001 86
345 2001 68
346 2001 85
347 2001 68
348 2001 82
349 2001 95
350 2001 102
351 2001 86
352 2001 62
353 2001 79
354 2001 116
355 2001 90
356 2001 93
357 2001 62
358 2001 73
359 2001 80
360 2000 82
361 2000 85
362 2000 95
363 2000 74
364 2000 85
365 2000 65
366 2000 95
367 2000 85
368 2000 90
369 2000 82
370 2000 79
371 2000 79
372 2000 72
373 2000 77
374 2000 86
375 2000 73
376 2000 69
377 2000 67
378 2000 94
379 2000 87
380 2000 91
381 2000 65
382 2000 69
383 2000 76
384 2000 91
385 2000 97
386 2000 95
387 2000 69
388 2000 71
389 2000 83
390 1999 70
391 1999 100
392 1999 103
393 1999 78
394 1999 94
395 1999 67
396 1999 75
397 1999 96
398 1999 97
399 1999 72
400 1999 69
401 1999 64
402 1999 97
403 1999 64
404 1999 77
405 1999 74
406 1999 63
407 1999 68
408 1999 97
409 1999 98
410 1999 87
411 1999 77
412 1999 78
413 1999 74
414 1999 79
415 1999 86
416 1999 75
417 1999 69
418 1999 95
419 1999 84
420 1998 85
421 1998 65
422 1998 106
423 1998 79
424 1998 92
425 1998 90
426 1998 80
427 1998 77
428 1998 89
429 1998 77
430 1998 65
431 1998 54
432 1998 102
433 1998 72
434 1998 83
435 1998 74
436 1998 70
437 1998 65
438 1998 88
439 1998 114
440 1998 74
441 1998 75
442 1998 69
443 1998 98
444 1998 76
445 1998 89
446 1998 83
447 1998 63
448 1998 88
449 1998 88
450 1997 84
451 1997 101
452 1997 98
453 1997 78
454 1997 68
455 1997 80
456 1997 76
457 1997 86
458 1997 83
459 1997 79
460 1997 92
461 1997 84
462 1997 67
463 1997 88
464 1997 78
465 1997 68
466 1997 78
467 1997 88
468 1997 96
469 1997 65
470 1997 68
471 1997 79
472 1997 76
473 1997 90
474 1997 90
475 1997 73
476 1997 77
477 1997 76
478 1996 96
479 1996 88
480 1996 85
481 1996 70
482 1996 76
483 1996 85
484 1996 81
485 1996 99
486 1996 83
487 1996 53
488 1996 80
489 1996 82
490 1996 75
491 1996 90
492 1996 80
493 1996 78
494 1996 88
495 1996 71
496 1996 92
497 1996 78
498 1996 67
499 1996 73
500 1996 91
501 1996 85
502 1996 68
503 1996 88
504 1996 90
505 1996 74
506 1993 104
507 1993 85
508 1993 80
509 1993 71
510 1993 84
511 1993 94
512 1993 73
513 1993 76
514 1993 67
515 1993 85
516 1993 64
517 1993 85
518 1993 84
519 1993 81
520 1993 69
521 1993 71
522 1993 94
523 1993 59
524 1993 88
525 1993 68
526 1993 97
527 1993 75
528 1993 61
529 1993 82
530 1993 103
531 1993 87
532 1993 86
533 1993 95
534 1992 98
535 1992 89
536 1992 73
537 1992 72
538 1992 78
539 1992 86
540 1992 90
541 1992 76
542 1992 75
543 1992 81
544 1992 72
545 1992 63
546 1992 92
547 1992 90
548 1992 87
549 1992 72
550 1992 76
551 1992 96
552 1992 70
553 1992 96
554 1992 82
555 1992 64
556 1992 72
557 1992 83
558 1992 77
559 1992 96
560 1991 94
561 1991 67
562 1991 84
563 1991 81
564 1991 77
565 1991 87
566 1991 74
567 1991 57
568 1991 84
569 1991 65
570 1991 82
571 1991 93
572 1991 83
573 1991 95
574 1991 71
575 1991 77
576 1991 71
577 1991 84
578 1991 78
579 1991 98
580 1991 84
581 1991 83
582 1991 75
583 1991 84
584 1991 85
585 1991 91
586 1990 65
587 1990 76
588 1990 88
589 1990 80
590 1990 77
591 1990 94
592 1990 91
593 1990 77
594 1990 79
595 1990 75
596 1990 75
597 1990 86
598 1990 74
599 1990 74
600 1990 85
601 1990 91
602 1990 67
603 1990 103
604 1990 77
605 1990 95
606 1990 75
607 1990 77
608 1990 85
609 1990 70
610 1990 83
611 1990 86
612 1989 63
613 1989 87
614 1989 83
615 1989 91
616 1989 93
617 1989 69
618 1989 75
619 1989 73
620 1989 59
621 1989 86
622 1989 92
623 1989 77
624 1989 81
625 1989 80
626 1989 81
627 1989 87
628 1989 74
629 1989 99
630 1989 67
631 1989 74
632 1989 89
633 1989 73
634 1989 92
635 1989 86
636 1989 83
637 1989 89
638 1988 54
639 1988 54
640 1988 89
641 1988 75
642 1988 77
643 1988 71
644 1988 87
645 1988 78
646 1988 88
647 1988 82
648 1988 84
649 1988 94
650 1988 87
651 1988 91
652 1988 81
653 1988 100
654 1988 85
655 1988 104
656 1988 65
657 1988 85
658 1988 83
659 1988 68
660 1988 83
661 1988 76
662 1988 70
663 1988 87
664 1987 69
665 1987 67
666 1987 78
667 1987 75
668 1987 76
669 1987 77
670 1987 84
671 1987 61
672 1987 98
673 1987 76
674 1987 83
675 1987 73
676 1987 91
677 1987 85
678 1987 91
679 1987 92
680 1987 89
681 1987 81
682 1987 80
683 1987 80
684 1987 65
685 1987 78
686 1987 90
687 1987 95
688 1987 75
689 1987 96
690 1986 72
691 1986 73
692 1986 95
693 1986 92
694 1986 70
695 1986 72
696 1986 86
697 1986 84
698 1986 87
699 1986 96
700 1986 76
701 1986 73
702 1986 77
703 1986 71
704 1986 78
705 1986 108
706 1986 90
707 1986 76
708 1986 86
709 1986 64
710 1986 74
711 1986 67
712 1986 83
713 1986 79
714 1986 87
715 1986 86
716 1985 66
717 1985 83
718 1985 81
719 1985 90
720 1985 77
721 1985 85
722 1985 89
723 1985 60
724 1985 84
725 1985 83
726 1985 91
727 1985 95
728 1985 71
729 1985 77
730 1985 84
731 1985 98
732 1985 97
733 1985 77
734 1985 75
735 1985 57
736 1985 83
737 1985 74
738 1985 62
739 1985 101
740 1985 62
741 1985 99
742 1984 80
743 1984 85
744 1984 86
745 1984 81
746 1984 96
747 1984 74
748 1984 70
749 1984 75
750 1984 104
751 1984 80
752 1984 84
753 1984 79
754 1984 67
755 1984 81
756 1984 78
757 1984 90
758 1984 87
759 1984 77
760 1984 81
761 1984 75
762 1984 92
763 1984 74
764 1984 66
765 1984 84
766 1984 69
767 1984 89
768 1983 88
769 1983 98
770 1983 78
771 1983 70
772 1983 71
773 1983 99
774 1983 74
775 1983 70
776 1983 92
777 1983 85
778 1983 79
779 1983 91
780 1983 87
781 1983 70
782 1983 82
783 1983 68
784 1983 91
785 1983 74
786 1983 90
787 1983 84
788 1983 81
789 1983 60
790 1983 79
791 1983 79
792 1983 77
793 1983 89
794 1982 89
795 1982 94
796 1982 89
797 1982 93
798 1982 73
799 1982 87
800 1982 61
801 1982 78
802 1982 83
803 1982 77
804 1982 90
805 1982 88
806 1982 95
807 1982 60
808 1982 86
809 1982 65
810 1982 79
811 1982 68
812 1982 89
813 1982 84
814 1982 81
815 1982 76
816 1982 87
817 1982 92
818 1982 64
819 1982 78
820 1980 81
821 1980 100
822 1980 83
823 1980 65
824 1980 64
825 1980 70
826 1980 89
827 1980 79
828 1980 84
829 1980 93
830 1980 97
831 1980 92
832 1980 86
833 1980 77
834 1980 90
835 1980 67
836 1980 103
837 1980 83
838 1980 91
839 1980 83
840 1980 73
841 1980 59
842 1980 75
843 1980 74
844 1980 76
845 1980 67
846 1979 66
847 1979 102
848 1979 91
849 1979 88
850 1979 80
851 1979 73
852 1979 90
853 1979 81
854 1979 84
855 1979 89
856 1979 85
857 1979 79
858 1979 95
859 1979 82
860 1979 95
861 1979 63
862 1979 89
863 1979 54
864 1979 84
865 1979 98
866 1979 68
867 1979 67
868 1979 71
869 1979 86
870 1979 83
871 1979 53
872 1978 69
873 1978 90
874 1978 99
875 1978 87
876 1978 79
877 1978 71
878 1978 92
879 1978 69
880 1978 86
881 1978 74
882 1978 92
883 1978 95
884 1978 93
885 1978 73
886 1978 76
887 1978 66
888 1978 100
889 1978 69
890 1978 90
891 1978 88
892 1978 84
893 1978 56
894 1978 89
895 1978 69
896 1978 87
897 1978 59
898 1977 61
899 1977 97
900 1977 97
901 1977 74
902 1977 81
903 1977 90
904 1977 88
905 1977 71
906 1977 74
907 1977 81
908 1977 102
909 1977 98
910 1977 67
911 1977 84
912 1977 75
913 1977 64
914 1977 100
915 1977 63
916 1977 101
917 1977 96
918 1977 69
919 1977 64
920 1977 75
921 1977 83
922 1977 94
923 1977 54
924 1976 70
925 1976 88
926 1976 83
927 1976 76
928 1976 75
929 1976 64
930 1976 102
931 1976 81
932 1976 74
933 1976 80
934 1976 90
935 1976 92
936 1976 66
937 1976 85
938 1976 55
939 1976 86
940 1976 97
941 1976 87
942 1976 101
943 1976 92
944 1976 73
945 1976 74
946 1976 72
947 1976 76
948 1975 67
949 1975 90
950 1975 95
951 1975 72
952 1975 75
953 1975 75
954 1975 108
955 1975 79
956 1975 57
957 1975 64
958 1975 91
959 1975 88
960 1975 68
961 1975 76
962 1975 75
963 1975 82
964 1975 83
965 1975 98
966 1975 86
967 1975 92
968 1975 71
969 1975 80
970 1975 82
971 1975 79
972 1974 88
973 1974 91
974 1974 84
975 1974 68
976 1974 66
977 1974 80
978 1974 98
979 1974 77
980 1974 72
981 1974 81
982 1974 77
983 1974 102
984 1974 76
985 1974 82
986 1974 79
987 1974 71
988 1974 89
989 1974 90
990 1974 80
991 1974 88
992 1974 60
993 1974 72
994 1974 86
995 1974 83
996 1973 76
997 1973 97
998 1973 89
999 1973 79
1000 1973 77
1001 1973 77
1002 1973 99
1003 1973 71
1004 1973 85
1005 1973 82
1006 1973 88
1007 1973 95
1008 1973 74
1009 1973 81
1010 1973 79
1011 1973 82
1012 1973 80
1013 1973 94
1014 1973 71
1015 1973 80
1016 1973 60
1017 1973 88
1018 1973 81
1019 1973 57
1020 1971 82
1021 1971 101
1022 1971 85
1023 1971 76
1024 1971 83
1025 1971 79
1026 1971 79
1027 1971 60
1028 1971 91
1029 1971 79
1030 1971 85
1031 1971 89
1032 1971 69
1033 1971 74
1034 1971 71
1035 1971 83
1036 1971 81
1037 1971 101
1038 1971 67
1039 1971 97
1040 1971 61
1041 1971 90
1042 1971 90
1043 1971 63
1044 1970 76
1045 1970 108
1046 1970 87
1047 1970 86
1048 1970 84
1049 1970 56
1050 1970 102
1051 1970 76
1052 1970 79
1053 1970 79
1054 1970 65
1055 1970 87
1056 1970 65
1057 1970 98
1058 1970 73
1059 1970 83
1060 1970 93
1061 1970 89
1062 1970 73
1063 1970 89
1064 1970 63
1065 1970 86
1066 1970 76
1067 1970 70
1068 1969 93
1069 1969 109
1070 1969 87
1071 1969 71
1072 1969 92
1073 1969 68
1074 1969 89
1075 1969 62
1076 1969 90
1077 1969 81
1078 1969 69
1079 1969 85
1080 1969 97
1081 1969 52
1082 1969 100
1083 1969 80
1084 1969 88
1085 1969 63
1086 1969 88
1087 1969 52
1088 1969 64
1089 1969 90
1090 1969 87
1091 1969 86
1092 1968 81
1093 1968 91
1094 1968 86
1095 1968 67
1096 1968 84
1097 1968 67
1098 1968 83
1099 1968 86
1100 1968 103
1101 1968 72
1102 1968 76
1103 1968 79
1104 1968 73
1105 1968 83
1106 1968 82
1107 1968 76
1108 1968 80
1109 1968 88
1110 1968 97
1111 1968 65
1112 1967 77
1113 1967 76
1114 1967 92
1115 1967 84
1116 1967 87
1117 1967 89
1118 1967 87
1119 1967 75
1120 1967 91
1121 1967 69
1122 1967 62
1123 1967 73
1124 1967 91
1125 1967 61
1126 1967 72
1127 1967 82
1128 1967 81
1129 1967 91
1130 1967 101
1131 1967 76
1132 1966 85
1133 1966 97
1134 1966 72
1135 1966 80
1136 1966 59
1137 1966 83
1138 1966 76
1139 1966 81
1140 1966 88
1141 1966 72
1142 1966 74
1143 1966 95
1144 1966 89
1145 1966 66
1146 1966 70
1147 1966 87
1148 1966 92
1149 1966 93
1150 1966 83
1151 1966 71
1152 1965 94
1153 1965 62
1154 1965 75
1155 1965 72
1156 1965 95
1157 1965 89
1158 1965 87
1159 1965 89
1160 1965 65
1161 1965 59
1162 1965 97
1163 1965 102
1164 1965 86
1165 1965 50
1166 1965 77
1167 1965 85
1168 1965 90
1169 1965 95
1170 1965 80
1171 1965 70
1172 1964 97
1173 1964 72
1174 1964 76
1175 1964 98
1176 1964 92
1177 1964 79
1178 1964 85
1179 1964 66
1180 1964 57
1181 1964 82
1182 1964 80
1183 1964 79
1184 1964 88
1185 1964 53
1186 1964 99
1187 1964 92
1188 1964 80
1189 1964 90
1190 1964 93
1191 1964 62
1192 1963 86
1193 1963 76
1194 1963 82
1195 1963 94
1196 1963 86
1197 1963 79
1198 1963 79
1199 1963 66
1200 1963 73
1201 1963 70
1202 1963 99
1203 1963 91
1204 1963 84
1205 1963 51
1206 1963 104
1207 1963 87
1208 1963 74
1209 1963 88
1210 1963 93
1211 1963 56
1212 1962 77
1213 1962 76
1214 1962 59
1215 1962 85
1216 1962 98
1217 1962 80
1218 1962 85
1219 1962 64
1220 1962 72
1221 1962 86
1222 1962 102
1223 1962 91
1224 1962 86
1225 1962 40
1226 1962 96
1227 1962 81
1228 1962 93
1229 1962 103
1230 1962 84
1231 1962 60

In [361]:
for row in df.itertuples():
  i = row.Index
  year = row.Year
  wins = row.W
  
  # Check if rangers made Playoffs (1 means yes; 0 means no)
  if row.Playoffs == 1:
    print(i, year, wins)

1 2012 94
2 2012 93
6 2012 97
9 2012 88
18 2012 95
19 2012 94
24 2012 94
25 2012 88
27 2012 93
29 2012 98
30 2011 94
39 2011 95
45 2011 96
48 2011 97
50 2011 102
55 2011 90
56 2011 91
57 2011 96
61 2010 91
66 2010 91
76 2010 94
78 2010 95
80 2010 97
84 2010 92
86 2010 96
87 2010 90
93 2009 95
98 2009 92
103 2009 97
104 2009 95
106 2009 87
108 2009 103
110 2009 93
115 2009 91
123 2008 95
124 2008 97
125 2008 89
133 2008 100
134 2008 84
135 2008 90
140 2008 92
146 2008 97
150 2007 90
153 2007 96
154 2007 85
157 2007 96
158 2007 90
163 2007 94
168 2007 94
170 2007 89
189 2006 95
194 2006 88
196 2006 96
197 2006 97
198 2006 97
199 2006 93
202 2006 88
205 2006 83
211 2005 90
213 2005 95
215 2005 99
221 2005 89
223 2005 95
228 2005 95
232 2005 82
235 2005 100
240 2004 92
242 2004 96
244 2004 98
252 2004 92
254 2004 93
256 2004 92
259 2004 101
266 2004 105
272 2003 101
274 2003 95
275 2003 88
281 2003 91
286 2003 90
289 2003 101
290 2003 96
295 2003 100
300 2002 99
301 2002 98
302 2002 101
316 2002 94
319 2002 103
320 2002 103
325 2002 95
326 2002 97
331 2001 92
332 2001 88
338 2001 91
342 2001 93
349 2001 95
350 2001 102
354 2001 116
356 2001 93
362 2000 95
366 2000 95
378 2000 94
379 2000 87
380 2000 91
384 2000 91
385 2000 97
386 2000 95
391 1999 100
392 1999 103
394 1999 94
398 1999 97
402 1999 97
408 1999 97
409 1999 98
418 1999 95
422 1998 106
424 1998 92
425 1998 90
428 1998 89
432 1998 102
439 1998 114
443 1998 98
448 1998 88
451 1997 101
452 1997 98
457 1997 86
460 1997 92
461 1997 84
468 1997 96
473 1997 90
474 1997 90
478 1996 96
479 1996 88
485 1996 99
491 1996 90
496 1996 92
500 1996 91
503 1996 88
504 1996 90
506 1993 104
511 1993 94
526 1993 97
533 1993 95
534 1992 98
551 1992 96
553 1992 96
559 1992 96
560 1991 94
573 1991 95
579 1991 98
585 1991 91
588 1990 88
592 1990 91
603 1990 103
605 1990 95
616 1989 93
629 1989 99
634 1989 92
637 1989 89
640 1988 89
649 1988 94
653 1988 100
655 1988 104
672 1987 98
677 1987 85
686 1987 90
687 1987 95
692 1986 95
693 1986 92
699 1986 96
705 1986 108
726 1985 91
727 1985 95
739 1985 101
741 1985 99
746 1984 96
750 1984 104
752 1984 84
762 1984 92
769 1983 98
773 1983 99
779 1983 91
786 1983 90
794 1982 89
797 1982 93
806 1982 95
817 1982 92
829 1980 93
830 1980 97
836 1980 103
838 1980 91
847 1979 102
849 1979 88
852 1979 90
865 1979 98
882 1978 92
883 1978 95
888 1978 100
890 1978 90
908 1977 102
909 1977 98
914 1977 100
916 1977 101
930 1976 102
934 1976 90
940 1976 97
942 1976 101
950 1975 95
954 1975 108
965 1975 98
967 1975 92
973 1974 91
983 1974 102
989 1974 90
991 1974 88
997 1973 97
1002 1973 99
1011 1973 82
1013 1973 94
1021 1971 101
1037 1971 101
1039 1971 97
1041 1971 90
1045 1970 108
1050 1970 102
1057 1970 98
1063 1970 89
1068 1969 93
1069 1969 109
1080 1969 97
1082 1969 100
1100 1968 103
1110 1968 97
1114 1967 92
1130 1967 101
1133 1966 97
1143 1966 95
1162 1965 97
1163 1965 102
1186 1964 99
1190 1964 93
1202 1963 99
1206 1963 104
1226 1962 96
1229 1962 103

In [ ]:
yankees_df=df[df.Team=='NYY']

In [365]:
def calc_run_diff(runs_scored, runs_allowed):

    run_diff = runs_scored - runs_allowed

    return run_diff

In [367]:
run_diffs = []

# Loop over the DataFrame and calculate each row's run differential
for row in yankees_df.itertuples():
    
    runs_scored = row.RS
    runs_allowed = row.RA
    
    run_diff = calc_run_diff(runs_scored, runs_allowed)
    
    run_diffs.append(run_diff)
yankees_df['RD'] = run_diffs
print(yankees_df)

     Team League  Year   RS   RA    W    OBP    SLG     BA  Playoffs  \
18    NYY     AL  2012  804  668   95  0.337  0.453  0.265         1
48    NYY     AL  2011  867  657   97  0.343  0.444  0.263         1
78    NYY     AL  2010  859  693   95  0.350  0.436  0.267         1
108   NYY     AL  2009  915  753  103  0.362  0.478  0.283         1
138   NYY     AL  2008  789  727   89  0.342  0.427  0.271         0
168   NYY     AL  2007  968  777   94  0.366  0.463  0.290         1
198   NYY     AL  2006  930  767   97  0.363  0.461  0.285         1
228   NYY     AL  2005  886  789   95  0.355  0.450  0.276         1
259   NYY     AL  2004  897  808  101  0.353  0.458  0.268         1
289   NYY     AL  2003  877  716  101  0.356  0.453  0.271         1
319   NYY     AL  2002  897  697  103  0.354  0.455  0.275         1
349   NYY     AL  2001  804  713   95  0.334  0.435  0.267         1
379   NYY     AL  2000  871  814   87  0.354  0.450  0.277         1
409   NYY     AL  1999  900  731   98  0.366  0.453  0.282         1
439   NYY     AL  1998  965  656  114  0.364  0.460  0.288         1
468   NYY     AL  1997  891  688   96  0.362  0.436  0.287         1
496   NYY     AL  1996  871  787   92  0.360  0.436  0.288         1
524   NYY     AL  1993  821  761   88  0.353  0.435  0.279         0
550   NYY     AL  1992  733  746   76  0.328  0.406  0.261         0
576   NYY     AL  1991  674  777   71  0.316  0.387  0.256         0
602   NYY     AL  1990  603  749   67  0.300  0.366  0.241         0
628   NYY     AL  1989  698  792   74  0.331  0.391  0.269         0
654   NYY     AL  1988  772  748   85  0.333  0.395  0.263         0
680   NYY     AL  1987  788  758   89  0.336  0.418  0.262         0
706   NYY     AL  1986  797  738   90  0.347  0.430  0.271         0
732   NYY     AL  1985  839  660   97  0.344  0.425  0.267         0
758   NYY     AL  1984  758  679   87  0.339  0.404  0.276         0
784   NYY     AL  1983  770  703   91  0.337  0.416  0.273         0
810   NYY     AL  1982  709  716   79  0.328  0.398  0.256         0
836   NYY     AL  1980  820  662  103  0.343  0.425  0.267         1
862   NYY     AL  1979  734  672   89  0.328  0.406  0.266         0
888   NYY     AL  1978  735  582  100  0.329  0.388  0.267         1
914   NYY     AL  1977  831  651  100  0.344  0.444  0.281         1
940   NYY     AL  1976  730  575   97  0.328  0.389  0.269         1
964   NYY     AL  1975  681  588   83  0.325  0.382  0.264         0
988   NYY     AL  1974  671  623   89  0.324  0.368  0.263         0
1012  NYY     AL  1973  641  610   80  0.322  0.378  0.261         0
1036  NYY     AL  1971  648  641   81  0.328  0.360  0.254         0
1060  NYY     AL  1970  680  612   93  0.324  0.365  0.251         0
1083  NYY     AL  1969  562  587   80  0.308  0.344  0.235         0
1105  NYY     AL  1968  536  531   83  0.292  0.318  0.214         0
1126  NYY     AL  1967  522  621   72  0.296  0.317  0.225         0
1146  NYY     AL  1966  611  612   70  0.299  0.374  0.235         0
1166  NYY     AL  1965  611  604   77  0.299  0.364  0.235         0
1186  NYY     AL  1964  730  577   99  0.317  0.387  0.253         1
1206  NYY     AL  1963  714  547  104  0.309  0.403  0.252         1
1226  NYY     AL  1962  817  680   96  0.337  0.426  0.267         1

      RankSeason  RankPlayoffs    G   OOBP   OSLG    WP   RD
18           3.0           3.0  162  0.311  0.419  0.59  136
48           2.0           4.0  162  0.322  0.399  0.60  210
78           3.0           3.0  162  0.322  0.399  0.59  166
108          1.0           1.0  162  0.327  0.408  0.64  162
138          NaN           NaN  162  0.329  0.405  0.55   62
168          2.0           4.0  162  0.340  0.417  0.58  191
198          1.0           4.0  162  0.326  0.413  0.60  163
228          3.0           4.0  162  0.332  0.422  0.59   97
259          2.0           3.0  162  0.328  0.432  0.62   89
289          1.0           2.0  163  0.314  0.407  0.62  161
319          1.0           4.0  161  0.309  0.395  0.64  200
349          3.0           2.0  161  0.318  0.398  0.59   91
379          5.0           1.0  161  0.336  0.422  0.54   57
409          3.0           1.0  162  0.329  0.400  0.60  169
439          1.0           1.0  162    NaN    NaN  0.70  309
468          3.0           4.0  162    NaN    NaN  0.59  203
496          3.0           1.0  162    NaN    NaN  0.57   84
524          NaN           NaN  162    NaN    NaN  0.54   60
550          NaN           NaN  162    NaN    NaN  0.47  -13
576          NaN           NaN  162    NaN    NaN  0.44 -103
602          NaN           NaN  162    NaN    NaN  0.41 -146
628          NaN           NaN  161    NaN    NaN  0.46  -94
654          NaN           NaN  161    NaN    NaN  0.53   24
680          NaN           NaN  162    NaN    NaN  0.55   30
706          NaN           NaN  162    NaN    NaN  0.56   59
732          NaN           NaN  161    NaN    NaN  0.60  179
758          NaN           NaN  162    NaN    NaN  0.54   79
784          NaN           NaN  162    NaN    NaN  0.56   67
810          NaN           NaN  162    NaN    NaN  0.49   -7
836          1.0           3.0  162    NaN    NaN  0.64  158
862          NaN           NaN  160    NaN    NaN  0.56   62
888          1.0           1.0  163    NaN    NaN  0.61  153
914          3.0           1.0  162    NaN    NaN  0.62  180
940          3.0           2.0  159    NaN    NaN  0.61  155
964          NaN           NaN  160    NaN    NaN  0.52   93
988          NaN           NaN  162    NaN    NaN  0.55   48
1012         NaN           NaN  162    NaN    NaN  0.49   31
1036         NaN           NaN  162    NaN    NaN  0.50    7
1060         NaN           NaN  163    NaN    NaN  0.57   68
1083         NaN           NaN  162    NaN    NaN  0.49  -25
1105         NaN           NaN  164    NaN    NaN  0.51    5
1126         NaN           NaN  163    NaN    NaN  0.44  -99
1146         NaN           NaN  160    NaN    NaN  0.44   -1
1166         NaN           NaN  162    NaN    NaN  0.48    7
1186         1.0           2.0  164    NaN    NaN  0.60  153
1206         1.0           2.0  161    NaN    NaN  0.65  167
1226         2.0           1.0  162    NaN    NaN  0.59  137

C:\Users\Hp\Anaconda3\anac3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

### Pandas .apply() method
- Takes a function and applies it to a DataFrame.
  - Must specify an axis to apply (0 for columns; 1 for rows)
- Just like the map function, pandas .apply()method can be used with anonymous functions or kambdas.

In [369]:
run_diffs_apply=df.apply(
lambda row: calc_run_diff(row['RS'], row['RA']),axis=1)
df['RD']=run_diffs_apply
print(df)

     Team League  Year   RS   RA    W    OBP    SLG     BA  Playoffs  \
0     ARI     NL  2012  734  688   81  0.328  0.418  0.259         0
1     ATL     NL  2012  700  600   94  0.320  0.389  0.247         1
2     BAL     AL  2012  712  705   93  0.311  0.417  0.247         1
3     BOS     AL  2012  734  806   69  0.315  0.415  0.260         0
4     CHC     NL  2012  613  759   61  0.302  0.378  0.240         0
...   ...    ...   ...  ...  ...  ...    ...    ...    ...       ...
1227  PHI     NL  1962  705  759   81  0.330  0.390  0.260         0
1228  PIT     NL  1962  706  626   93  0.321  0.394  0.268         0
1229  SFG     NL  1962  878  690  103  0.341  0.441  0.278         1
1230  STL     NL  1962  774  664   84  0.335  0.394  0.271         0
1231  WSA     AL  1962  599  716   60  0.308  0.373  0.250         0

      RankSeason  RankPlayoffs    G   OOBP   OSLG    WP   RD
0            NaN           NaN  162  0.317  0.415  0.50   46
1            4.0           5.0  162  0.306  0.378  0.58  100
2            5.0           4.0  162  0.315  0.403  0.57    7
3            NaN           NaN  162  0.331  0.428  0.43  -72
4            NaN           NaN  162  0.335  0.424  0.38 -146
...          ...           ...  ...    ...    ...   ...  ...
1227         NaN           NaN  161    NaN    NaN  0.50  -54
1228         NaN           NaN  161    NaN    NaN  0.58   80
1229         1.0           2.0  165    NaN    NaN  0.62  188
1230         NaN           NaN  163    NaN    NaN  0.52  110
1231         NaN           NaN  162    NaN    NaN  0.37 -117

[1232 rows x 17 columns]

In [ ]:
dbacks_df=df[df['Team']=='ARI']

In [373]:
def calc_win_perc(wins, games_played):
    win_perc = wins / games_played
    return np.round(win_perc,2)

In [377]:
# Display the first five rows of the DataFrame
print(dbacks_df.head())

# Create a win percentage Series 
win_percs = dbacks_df.apply(lambda row: calc_win_perc(row['W'], row['G']), axis=1)
print(win_percs, '\n')

    Team League  Year   RS   RA   W    OBP    SLG     BA  Playoffs  \
0    ARI     NL  2012  734  688  81  0.328  0.418  0.259         0
30   ARI     NL  2011  731  662  94  0.322  0.413  0.250         1
60   ARI     NL  2010  713  836  65  0.325  0.416  0.250         0
90   ARI     NL  2009  720  782  70  0.324  0.418  0.253         0
120  ARI     NL  2008  720  706  82  0.327  0.415  0.251         0

     RankSeason  RankPlayoffs    G   OOBP   OSLG    WP   RD
0           NaN           NaN  162  0.317  0.415  0.50   46
30          5.0           4.0  162  0.316  0.409  0.58   69
60          NaN           NaN  162  0.340  0.448  0.40 -123
90          NaN           NaN  162  0.330  0.419  0.43  -62
120         NaN           NaN  162  0.318  0.398  0.51   14
0      0.50
30     0.58
60     0.40
90     0.43
120    0.51
150    0.56
180    0.47
210    0.48
241    0.31
271    0.52
301    0.60
331    0.57
361    0.52
391    0.62
421    0.40
dtype: float64

In [378]:
def text_playoffs(num_playoffs): 
    if num_playoffs == 1:
        return 'Yes'
    else:
        return 'No'

In [379]:
# Convert numeric playoffs to text by applying text_playoffs()
textual_playoffs = dbacks_df.apply(lambda row: text_playoffs(row['Playoffs']), axis=1)
print(textual_playoffs)

0       No
30     Yes
60      No
90      No
120     No
150    Yes
180     No
210     No
241     No
271     No
301    Yes
331    Yes
361     No
391    Yes
421     No
dtype: object

In [380]:
dbacks_df['Textual Playoffs']=textual_playoffs

C:\Users\Hp\Anaconda3\anac3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [385]:
dbacks_df

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG,WP,RD,Textual Playoffs
0,ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415,0.50,46,No
30,ARI,NL,2011,731,662,94,0.322,0.413,0.250,1,5.0,4.0,162,0.316,0.409,0.58,69,Yes
60,ARI,NL,2010,713,836,65,0.325,0.416,0.250,0,NaN,NaN,162,0.340,0.448,0.40,-123,No
90,ARI,NL,2009,720,782,70,0.324,0.418,0.253,0,NaN,NaN,162,0.330,0.419,0.43,-62,No
120,ARI,NL,2008,720,706,82,0.327,0.415,0.251,0,NaN,NaN,162,0.318,0.398,0.51,14,No
150,ARI,NL,2007,712,732,90,0.321,0.413,0.250,1,3.0,3.0,162,0.334,0.420,0.56,-20,Yes
180,ARI,NL,2006,773,788,76,0.331,0.424,0.267,0,NaN,NaN,162,0.335,0.431,0.47,-15,No
210,ARI,NL,2005,696,856,77,0.332,0.421,0.256,0,NaN,NaN,162,0.345,0.455,0.48,-160,No
241,ARI,NL,2004,615,899,51,0.310,0.393,0.253,0,NaN,NaN,162,0.350,0.439,0.31,-284,No
271,ARI,NL,2003,717,685,84,0.330,0.417,0.263,0,NaN,NaN,162,0.322,0.388,0.52,32,No
301,ARI,NL,2002,819,674,98,0.346,0.423,0.267,1,4.0,4.0,162,0.305,0.397,0.60,145,Yes
331,ARI,NL,2001,818,677,92,0.341,0.442,0.267,1,5.0,1.0,162,0.311,0.404,0.57,141,Yes
361,ARI,NL,2000,792,754,85,0.333,0.429,0.265,0,NaN,NaN,162,0.326,0.424,0.52,38,No
391,ARI,NL,1999,908,676,100,0.347,0.459,0.277,1,2.0,4.0,162,0.320,0.402,0.62,232,Yes
421,ARI,NL,1998,665,812,65,0.314,0.393,0.246,0,NaN,NaN,162,NaN,NaN,0.40,-147,No

In [386]:
wins_np=df['W'].values
print(type(wins_np))

<class 'numpy.ndarray'>

In [387]:
print(wins_np)

[ 81  94  93 ... 103  84  60]

### Power of vectorization
- Broadcasting (vectorizing) is extremely efficient!

In [388]:
df['RS'].values-df['RA'].values

array([  46,  100,    7, ...,  188,  110, -117], dtype=int64)

In [389]:
df['RD']=df['RS'].values-df['RA'].values
df.head()

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG,WP,RD
0,ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415,0.50,46
1,ATL,NL,2012,700,600,94,0.320,0.389,0.247,1,4.0,5.0,162,0.306,0.378,0.58,100
2,BAL,AL,2012,712,705,93,0.311,0.417,0.247,1,5.0,4.0,162,0.315,0.403,0.57,7
3,BOS,AL,2012,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428,0.43,-72
4,CHC,NL,2012,613,759,61,0.302,0.378,0.240,0,NaN,NaN,162,0.335,0.424,0.38,-146

### Predicting Win Percentages

In [390]:
def predict_win_perc(RS, RA):
    prediction = RS ** 2 / (RS ** 2 + RA ** 2)
    return np.round(prediction, 2)

In [392]:
win_perc_preds_loop = []

# Use a loop and .itertuples() to collect each row's predicted win percentage
for row in df.itertuples():
    runs_scored = row.RS
    runs_allowed = row.RA
    win_perc_pred = predict_win_perc(runs_scored, runs_allowed)
    win_perc_preds_loop.append(win_perc_pred)

In [394]:
# Apply predict_win_perc to each row of the DataFrame
win_perc_preds_apply = df.apply(lambda row: predict_win_perc(row['RS'], row['RA']), axis=1)

In [398]:
# Calculate the win percentage predictions using NumPy arrays
win_perc_preds_np = predict_win_perc(df['RS'].values, df['RA'].values)
df['WP_preds'] = win_perc_preds_np
print(df.head())

  Team League  Year   RS   RA   W    OBP    SLG     BA  Playoffs  RankSeason  \
0  ARI     NL  2012  734  688  81  0.328  0.418  0.259         0         NaN
1  ATL     NL  2012  700  600  94  0.320  0.389  0.247         1         4.0
2  BAL     AL  2012  712  705  93  0.311  0.417  0.247         1         5.0
3  BOS     AL  2012  734  806  69  0.315  0.415  0.260         0         NaN
4  CHC     NL  2012  613  759  61  0.302  0.378  0.240         0         NaN

   RankPlayoffs    G   OOBP   OSLG    WP   RD  WP_preds
0           NaN  162  0.317  0.415  0.50   46      0.53
1           5.0  162  0.306  0.378  0.58  100      0.58
2           4.0  162  0.315  0.403  0.57    7      0.50
3           NaN  162  0.331  0.428  0.43  -72      0.45
4           NaN  162  0.335  0.424  0.38 -146      0.39

#### Using NumPy arrays was the fastest approach, followed by the .itertuples() approach, and the .apply() approach was slowest.